### ISSUE TITLE
os/fsnotify

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#1]
### Motivation

For some time there has been a desire to provide file system notifications in the standard library. See
https://github.com/golang/go/issues/4068 (was https://code.google.com/p/go/issues/detail?id=4068).

This would allow the tools that ship with Go to use it:

* go/cmd http://golang.org/s/go13fsnotify
* GoDoc https://code.google.com/p/go/issues/detail?id=3386

It may start as an internal package while working to solidify the API. Once exposed in the standard library, fsnotify will need to adhere to the [Go 1.0 guarantee for backwards compatibility](https://golang.org/doc/go1compat). It is not yet ready for that kind of guarantee.

### System requirements

[Go 1.3 requires](http://golang.org/doc/install#requirements) Linux 2.6.23 or OS X 10.6.

* If we use IN_NONBLOCK (#5) fsnotify would require Linux 2.6.27.
* FSEvents supports 10.6, but watching individual files requires 10.7. (`kFSEventStreamCreateFlagFileEvents`)

### CLA

All contributors to fsnotify are asked to sign Google's CLA. @bradfitz added many contributors to Go AUTHORS in the past (see https://github.com/howeyc/fsnotify/issues/85). 

[New AUTHORS](https://github.com/go-fsnotify/fsnotify/compare/537aeb4e98c5741e766e02a80181faa59ae291e7...master#diff-3d350169560e75d0cf9fc8e3574a3639R1) since then will need to be added.

**Comment by PieterD** [comment]
I'll put this here for now. Anyone interested, please comment.

https://docs.google.com/document/d/15MQZlc6S9toF-ikUiLtuA3t8bK51ScX3zED5liAPDSY/edit?usp=sharing

**Comment by nathany** [comment]
Given the improvements to tools to vendor code (GO15VENDOREXPERIMENT) and support for internal/ packages, I see less value in trying to bring this into the standard library. If the go tool or godoc need to use fsnotify, it can be copied in as an internal package.

Maybe an x/ package that uses Gerrit, the builders, and the CLA.
