### ISSUE TITLE
File watcher drivers/bindings (an interface)

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#104]
To support a polling fallback #9 and a step towards splitting out bindings for each OS #75.

From https://godoc.org/github.com/docker/docker/pkg/filenotify

``` go
// FileWatcher is an interface for implementing file notification watchers
type FileWatcher interface {
    Events() <-chan fsnotify.Event
    Errors() <-chan error
    Add(name string) error
    Remove(name string) error
    Close() error
}
```

This could be slightly modified, for example, removing the error channel #2, or that could come later.

**Comment by nathany** [comment]
API changes are using Events() and Errors() instead of fields in the platform-dependent struct and returning a FileWatcher interface instead of a *Watcher struct.

Maybe there is another way to do this that makes the drivers/bindings satisfy an interface, but keeps the existing API as is.

**Comment by psywolf** [comment]
This would also make it easier for clients of this library to inject a mock FileWatcher into their unit tests

**Comment by nathany** [comment]
I'm not sure if I want to see this much API churn in fsnotify itself. At least in the near-term.

Rather, I'd just like to see the fsnotify split into some independent packages (#75) for each OS while keeping the current API more or less the same. Having those low-level packages in place should enable more experimentation at the higher levels in alternatives to fsnotify.

**Comment by nathany** [comment]
Personally, I'd like to keep the fsnotify API as simple as possible, without requiring the user to know which driver to use. This could be an internal implementation detail at all.

For those that need more control, the individual OS-specific packages could be used directly.

**Comment by arp242** [comment]
I'm closing this one as a "duplicate" of #173 as well; it's not really a duplicate as such, but these kind of refactoring are pretty closely related, and I don't think there's too much value keeping this issue open in the "TODO list" separately.
