### ISSUE TITLE
Docker for locally testing Linux on other systems

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#106]
Right now I use [Vagrant Gopher](https://github.com/nathany/vagrant-gopher) to run tests under Linux (from a Mac, but should also work on Windows). While it will still be necessary for testing BSD, using Docker Machine and Docker should prove much faster.
- [ ] add a Dockerfile to perform the build on Linux
- [ ] update CONTRIBUTING.md with instructions

**Comment by tiwaana** [comment]
I recently put a docker based on ubuntu 16.04 with go and git support. If you give me some info, I will give it a try.

**Comment by nathany** [comment]
Hi @tiwaana. Just prepare a Dockerfile in a pull request that can be used to locally test Linux, with some instructions to do so. The tests (`go test`) should pass in the container.

**Comment by nathany** [comment]
See #274 for a starting point. Unfortunately I didn't review it last year and Ahmad Nurus S. has left GitHub.

**Comment by Nols1000** [comment]
Moin,
just for testing there is no need to build a docker image. As I understand, it would be enough to use the official golang image and run the tests in there.

```bash
docker run -it -v "$(pwd):/go/src/github.com/fsnotify/fsnotify/:ro" golang sh -c "cd /go/src/github.com/fsnotify/fsnotify; go test ./... -race"
```
(The volume mounting should work for linux/mac.)
