### ISSUE TITLE
Move away from gopkg.in and rename organization

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#108]
When forking howeyc/fsnotify to modify the API, I decided to use gopkg.in to version the fsnotify library, given that further breaking changes were planned (and still are).

With the success of GO15VENDOREXPERIMENT and vendoring, there is less reason to use gopkg.in. It doesn't really cause any trouble to keep gopkg.in right now, but...

One disadvantage of having a version # in the import path is that internal packages must be specified differently on each branch (v1, v0, master). Right now fsnotify is only a single package, but it would be nice to split out low-level drivers for each OS (see #75). It's certainly doable, but seems like unnecessary complication.

If we made this change, we could do so in a way that leaves the existing import paths in place, while moving the issue tracker and active development to a new import path:

```
import "gopkg.in/fsnotify.v0"
import "gopkg.in/fsnotify.v1"

import "yet-to-be-determined/fsnotify"
```

Additionally, we would continue to tag releases, and tags can be checked out in git whether or not vendoring tools directly support doing so.

For? Against? Proposed new import paths?

**Comment by nathany** [comment]
Part of this move would be to adopt @rjeczalik's notify library as an alternative available from the same organization. Any low-level "drivers" for specific platforms would also exist under the new organization.

**Comment by omeid** [comment]
I am for moving away from gopkg. For reproducible builds as you explained vendoring is the way to go.

This is a very low level library and upgrading shouldn't be a big hassle for those who want to stay up to date.

**Comment by nathany** [comment]
I'm planning to rename the organization as well, since the "go-" prefix is a gopkg.in thing.

**Comment by nathany** [comment]
I'm preparing to rename the organization now.

**Comment by nathany** [comment]
The move to https://github.com/fsnotify/fsnotify is done, though I have to ensure CI is still working and update the website.

GitHub automatically redirects https://github.com/go-fsnotify/fsnotify to https://github.com/fsnotify/fsnotify.

I tested `go get gopkg.in/fsnotify.v1` and it still works, which I did not expect. If we run into any problems, or if we ever need to include github.com/fsnotify/fsnotify in an import path, I can put a repository up at github.com/go-fsnotify/fsnotify with a "maintenance has moved" message in the README.

**Comment by nathany** [comment]
All done.

**Comment by CameronAckermanSEL** [comment]
@nathany FYI https://github.com/githubnemo/CompileDaemon/issues/30

**Comment by nathany** [comment]
https://github.com/go-fsnotify/fsnotify now has a "moved" message in the README.

See https://github.com/go-fsnotify/fsnotify/issues/1

This was implemented rather poorly as compared to prior transitions (#35). Apologies for that, but what's done is done.
