### ISSUE TITLE
file permission affect file watch notification

### ISSUE THREAD

**Issue by prateekgogia** [fsnotify/fsnotify#110]
I am adding some code to watch a file in ubuntu. Whenever I write to a file, based on the permission I get different notifications. 

If the file permissions is 666, I get WRITE and CHMOD.

If the file permission is 644 or 600 I get RENAME, CHMOD, REMOVE (no WRITE).

In both the cases I am root, I am able to edit the file, but notification is not received.

	% uname -a 
	Linux dockerbuild 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

	% cat /etc/os-release:

	NAME="Ubuntu"
	VERSION="15.10 (Wily Werewolf)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 15.10"
	VERSION_ID="15.10"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by nathany** [comment]
That is odd. It would probably be worth digging deeper to see if inotify is the cause or if fsnotify is mangling the event somehow.

Adding some logging in readEvents could help. https://github.com/go-fsnotify/fsnotify/blob/master/inotify.go#L171

**Comment by arp242** [comment]
I cannot reproduce this; I used the `cmd/fsnotify` tool in this repo:

    % mkdir x
    % fsnotify ./x

Then I created some files in another terminal:

	% cd x
	% touch 666 644 600
	% chmod 666 666; chmod 644 644; chmod 600 600
	% print x >> 666; print x >> 644; print x >> 600
	% rm 666 644 600

And go the following output (with the commands added to see which events
correspond to which commands):

	% touch 666 644 600

		16:76:42.7451  16 CREATE                "x/666"
		16:76:42.7451  17 CHMOD                 "x/666"
		16:76:42.7451  18 CREATE                "x/644"
		16:76:42.7451  19 CHMOD                 "x/644"
		16:76:42.7451  20 CREATE                "x/600"
		16:76:42.7451  21 CHMOD                 "x/600"

	% chmod 666 666; chmod 644 644; chmod 600 600

		16:76:25.1692  22 CHMOD                 "x/666"
		16:76:25.1702  23 CHMOD                 "x/644"
		16:76:25.1712  24 CHMOD                 "x/600"

	% print x >> 666; print x >> 644; print x >> 600

		16:76:57.3201  25 WRITE      (modified) "x/666"
		16:76:57.3201  26 WRITE      (modified) "x/644"
		16:76:57.3201  27 WRITE      (modified) "x/600"

	% rm 666 644 600

		16:76:14.9752  28 REMOVE                "x/666"
		16:76:14.9752  29 REMOVE                "x/644"
		16:76:14.9752  30 REMOVE                "x/600"

So seems fine to me.

Since this is a pretty old issue I'll close this for now; please add more information if you can still reproduce this and we can reopen it.
