### ISSUE TITLE
Not able to remove file watcher

### ISSUE THREAD

**Issue by gaplyk** [fsnotify/fsnotify#115]
I need to remove file watcher. Calling method Remove(fileName) when event happened to prevent receive other event's to this file.

And actually this call to remove event is not working. It's waiting for ignoreLinux to remove watcher, but this never happening.

**Comment by Tasssadar** [comment]
Happened to me too, relevant stack trace:

```
goroutine 60 [select, 1 minutes]:
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc82031e000)
        src/gopkg.in/fsnotify.v1/inotify.go:265 +0xa00
created by gopkg.in/fsnotify%2ev1.NewWatcher
       gopkg.in/fsnotify.v1/inotify.go:60 +0x3e2

goroutine 61 [semacquire, 1 minutes]:
sync.runtime_Syncsemacquire(0xc820300850)
       src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820300840)
       src/sync/cond.go:63 +0x9b
gopkg.in/fsnotify%2ev1.(*Watcher).Remove(0xc82031e000, 0xc820482230, 0x4e, 0x0, 0x0)
        src/gopkg.in/fsnotify.v1/inotify.go:157 +0x2db
...
```

The problem is that goroutine 61 is also the one that reads from the `Events` channel, which means no new events can come in and free the condition in `Remove()`. Not sure if that's a bug per se, but definitely something that should be documented (but I honestly haven't checked if it is, so if yes, the joke's on me ^^)

**Comment by nathany** [comment]
I wonder if this is similar to the issues and fixes for kqueue on BSD (#105), except for inotify.

**Comment by jiangytcn** [comment]
@nathany  and @gaplyk i had same issue, and i'm curious about whether i had to manually remove the file/directory watcher when the file/directory removed? will the fsnotify library automatically achieve this ?

**Comment by gaplyk** [comment]
I just hand over in this case and use different workaround without fsnotify.
