### ISSUE TITLE
Events are not triggered when running in background

### ISSUE THREAD

**Issue by thinkclay** [fsnotify/fsnotify#117]
When using nohup or & to suppress a process that leverages fsnotify, the events are no longer received in the background process. Implementation here: https://github.com/wellington/wellington/blob/master/filewatcher.go#L149

**Comment by nathany** [comment]
Which platform are you running into this issue on?

**Comment by thinkclay** [comment]
Mac: 10.11.4 Beta (15E27e)

**Comment by nathany** [comment]
Thanks. 

Were the events happening previously? Do you have any idea of what may have changed in wellington, or if it was an update to fsnotify?

**Comment by drewwells** [comment]
I'd have to build this again on older branches, if you have a guess when this could be a regression that would help track it down. I probably never have tested this as a background process, so not sure if it's a regression or always been a problem.

**Comment by arp242** [comment]
I can't seem to reproduce this; on macOS:

	[~/fsnotify]% go run ./cmd/fsnotify /tmp/watch/ &
	[1] 1130
	[~/fsnotify]% 00:86:46.9177 watching; press ^C to exit
	00:86:49.9164   1 CREATE                "/tmp/watch/asd"
	00:86:52.1444   2 CREATE                "/tmp/watch/asdzxczxc"
	00:86:57.6487   3 CREATE                "/tmp/watch/qwewqezxc"

	[~/fsnotify]% fg
	[1]  + running    go run ./cmd/fsnotify /tmp/watch/
	^Csignal: interrupt

And with nohup:

	1[~/fsnotify]% nohup go run ./cmd/fsnotify /tmp/watch/ &
	[1] 1151
	[~/fsnotify]% appending output to nohup.out

	[~/fsnotify]% cat nohup.out
	00:86:18.8525 watching; press ^C to exit
	00:86:26.0873   1 CREATE                "/tmp/watch/NOHUP"
	00:86:26.8113   2 CREATE                "/tmp/watch/NOHUP2"
	[~/fsnotify]% fg
	[1]  + running    nohup go run ./cmd/fsnotify /tmp/watch/
	^C

Since this is an old issue that I can't reproduce, I'll close this for now; please get back to me if you're still experiencing it and we can reopen and investigate further.
