### ISSUE TITLE
gopkg.in very unreliable

### ISSUE THREAD

**Issue by draxil** [fsnotify/fsnotify#118]
The recommended paths for stable fsnotify are a great idea. However in practice gopkg.in seems to be very unreliable and when I use "go get" to  install projects depending on fsnotify it often freezes thus:

> $ go get -v gopkg.in/fsnotify.v1
> Fetching https://gopkg.in/fsnotify.v1?go-get=1
> Parsing meta tags from https://gopkg.in/fsnotify.v1?go-get=1 (status code 200)
> get "gopkg.in/fsnotify.v1": found meta tag main.metaImport{Prefix:"gopkg.in/fsnotify.v1", VCS:"git", 
> RepoRoot:"https://gopkg.in/fsnotify.v1"} at https://gopkg.in/fsnotify.v1?go-get=1
> gopkg.in/fsnotify.v1 (download)

Perhaps it could be better to maintain a stable mirror on github, or somewhere more reliable?

**Comment by nathany** [comment]
Thanks for reporting this. I haven't noticed gopkg.in being unreliable, but it's another reason to move away from it. See #108.

**Comment by nathany** [comment]
https://github.com/fsnotify/fsnotify is the new home for fsnotify.
