### ISSUE TITLE
File Events Notifications on Solaris

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#12]
@4ad would like fsnotify to support FEN on Solaris.

While each file & directory requires an event source, the [limits are much higher than kqueue](https://groups.google.com/d/msg/golang-dev/bShm2sqbrTY/HMm7Y36uuxIJ):

> The default limit is 64k event sources per event port per process.
> The default limit for the number of event sources per system is
> 2^31.
> 
> The default limit for the number of event ports per process is 8k.
> The default limit for the number of event ports per system is 64k.
### Reference
- [File Events Notification](https://blogs.oracle.com/praks/entry/file_events_notification)
- DTrace on Solaris can watch recursively.

**Comment by nathany** [comment]
@4ad Amit (@amitkris) is currently working on FEN support. Would you be willing to review his pull request when it is ready?

**Comment by xen0l** [comment]
I am trying to build packer on OpenIndiana, but it fails to compile.If PR is published, I'll test it.
