### ISSUE TITLE
Get fsnotify to build on Solaris

### ISSUE THREAD

**Issue by amitkris** [fsnotify/fsnotify#127]
Hi,

This is part of a larger effort to develop a native port of Docker on Solaris.
As fsnotify is one of the dependencies for the Docker Engine we need fsnotify to first build on Solaris.
This issue and the PR that will fix it will be a placeholder for #12.
I have started work on and have a working prototype for FEN support for fsnotify. This will progress as out Docker port comes along and will be integrated in a few weeks time.

**Comment by nathany** [comment]
Thanks.
