### ISSUE TITLE
too many open files on macOS

### ISSUE THREAD

**Issue by armhold** [fsnotify/fsnotify#129]
Adding a watch to a directory containing as few as 300 files results in "too many open files" in OSX. Note that it happens when only a single watch on the containing dir is added.

Here's a quick gist to reproduce: https://gist.github.com/armhold/a7f4d6666dcbcbbe1faf.

I do believe this is related to having a rather low (256) open files limit on OSX, but I don't expect fsnotify to keep an open file on every file in a watched directory. (Maybe that's an unreasonable expectation?)

> ulimit -a
> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> file size               (blocks, -f) unlimited
> max locked memory       (kbytes, -l) unlimited
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 256
> pipe size            (512 bytes, -p) 1
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 709
> virtual memory          (kbytes, -v) unlimited

Corrections appreciated if I am doing something wrong.

**Comment by armhold** [comment]
Almost certainly the same issue from the original project: https://github.com/howeyc/fsnotify/issues/35.

**Comment by nathany** [comment]
Yes, this hasn't changed. kqueue does need to keep a file open for every file it watches, plus the directories itself. On BSD the limits are higher.

There is a way to increase the limit. The FAQ should probably be updated with the commands to do it. https://github.com/fsnotify/fsnotify/wiki/FAQ

You can also ensure that you're not watching files that don't need to be watched, such as hidden .git folders.

**Comment by nathany** [comment]
NOTE: The FAQ is now part of the README to increase visibility: https://github.com/fsnotify/fsnotify#faq

**Comment by jbowens** [comment]
Maybe on Mac OS, it should use the [FSEvents API](https://en.wikipedia.org/wiki/FSEvents) instead of kqueue? I'm not familiar with these APIs, and I'm not sure whether the FSEvents API would require open file descriptors for each file too. But I came across the [fsevents](https://www.npmjs.com/package/fsevents) npm package which makes this claim:
> The FSEvents API in MacOS allows applications to register for notifications of changes to a given directory tree. It is a very fast and lightweight alternative to kqueue.

**Comment by jbowens** [comment]
Oh, sorry, just found fsnotify/fsnotify#11

**Comment by brandur** [comment]
Just a note that on Mac OS, I ran into much lower limits than what was suggested by `kern.maxfiles` and `kern.maxfilesperproc` from the README FAQ, and ended up having to set a new value for allowed open file descriptors for my current session with `ulimit -n`:

```
ulimit -n 2048.
```

The default is a measly 256.

There's more instructions here on how to set that at a system level with `launchctl` too: https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c

**Comment by nathany** [comment]
Thanks @brandur. 

The ulimit tip should be added to the FAQ in the README until such time as we integrate FSEvents.

**Comment by ahuigo** [comment]
It seems that Mac OSX's command fswatch does not rely on file descriptors.

```
# works well
$ fswatch -r node_modules
```

**Comment by arp242** [comment]
As mentioned, this is a limitation of how kqueue works; implements fsevents will fix this, which is tracked in #11 so I'm closing this one.
