### ISSUE TITLE
Detecting a rename from .tmp file to the file I am watching

### ISSUE THREAD

**Issue by nikunjy** [fsnotify/fsnotify#134]
I am trying to do an atomic write to a file that I am watching. Atomic write means that I will make a .tmp file with the new contents and rename it to the file I was watching. 

In case of mac this works fine 

    if ev.Op&fsnotify.Create == fsnotify.Create 

but doesn't work on linux. Advice ?

**Comment by bep** [comment]
I  did some related OSX fixes some time ago, and did some tests on Linux (on Hugo) as well, and it now behaves "better" (at least differently) on OSX.

The reliable cross-platform way regarding atomic saves is to watch directories and not individual files and then just throw away the events you don't care about.

**Comment by arp242** [comment]
This:

    [/tmp/xxx]% print file >!.file.atomic && =mv .file.atomic file

Gives me the following events:

	00:86:47.9479   1 CREATE                "/tmp/xxx/.file.atomic"
	00:86:47.9480   2 WRITE      (modified) "/tmp/xxx/.file.atomic"
	00:86:47.9519   3 RENAME                "/tmp/xxx/.file.atomic"
	00:86:47.9519   4 CREATE                "/tmp/xxx/file"

If you I only watch the file however, I get:

	[~cg/fsnotify]% go run ./cmd/fsnotify /tmp/xxx/file
	00:86:41.9964 watching; press ^C to exit
	00:86:43.4513   1 CHMOD                 "/tmp/xxx/file"
	00:86:43.4514   2 REMOVE                "/tmp/xxx/file"

Which is consistent with what the inotify API gives us:

	[~cg/fsnotify]% inotifywait -m /tmp/xxx/file
	Setting up watches.
	Watches established.
	/tmp/xxx/file ATTRIB
	/tmp/xxx/file DELETE_SELF

In general, I wouldn't recommend watching files unless you really know what you're doing, but watch the directories instead; watching files is basically asking for trouble, especially if you want it to work cross-platform.

I plan to document this and some other things in detail; the work on that is tracked in #372.
