### ISSUE TITLE
fsnotify on previous versions of Go

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#137]
fsnotify should still work on Go 1.3+, which was a change to syscall for Windows. If switched over to x/sys/windows it may even work on earlier versions.

The README currently mentions Go 1.6 for the vendor/ folder. This works for GO15VENDOREXPERIMENT=1 as well, and other approaches could work fine on previous versions of Go.

So the question is which versions of Go should fsnotify support?

And then how do we ensure it still supports those versions? This could be tied to the builders #136 project, as a matrix on Travis CI is only going to cover OS X and Linux.

**Comment by abh** [comment]
These days when vendored dependencies (copied into the project or not) are common I think the project can reasonably just support the last 2-3 versions. If you (for example) are still using Go 1.8 today you effectively have opted out of getting bug fixes or signed up for managing them yourself.

**Comment by arp242** [comment]
Oh, we need Go 1.16 for the retract statements in the go.mod; on Go 1.13 it errors out with:

	Run go test -race ./...
	go: errors parsing go.mod:
	/home/runner/work/fsnotify/fsnotify/go.mod:7: unknown block type: retract
	Error: Process completed with exit code 1.
