### ISSUE TITLE
ppc64* doesn't work after the switch to "x/sys/unix"

### ISSUE THREAD

**Issue by tophj-ibm** [fsnotify/fsnotify#139]
Because it looks like arm has been fixed, I wanted to make a new issue just for power. Currently, the change from "syscall" to "x/sys/unix" has broken fsnotify on power with the following errors when running 'go test -v'
```sh
$ go test -v
# github.com/fsnotify/fsnotify
./inotify.go:39: undefined: unix.InotifyInit
./inotify_poller.go:48: undefined: unix.Pipe2
./inotify_poller_test.go:20: undefined: unix.Pipe
FAIL	github.com/fsnotify/fsnotify [build failed]
```

**Comment by nathany** [comment]
Thanks for the report. ppc wasn't resolved in v1.3.0, see issue #130 for more.

**Comment by nathany** [comment]
Please try updating x/sys/unix.

**Comment by tophj-ibm** [comment]
following along in #130, thanks!
