### ISSUE TITLE
Flaky test TestInotifyStress

### ISSUE THREAD

**Issue by TheTincho** [fsnotify/fsnotify#142]
Hi again,

While testing the changes to fix #130 in arm64,  I noticed that sometimes (specially when the host is very loaded) the TestInotifyStress test would fail.

I can reproduce this consistently if I raise CPU usage artificially and run the tests with nice.

```
=== RUN   TestInotifyStress
--- FAIL: TestInotifyStress (5.02s)
	inotify_test.go:236: Creates and removes should not be off by more than one: 287 creates, 291 removes
```

**Comment by TheTincho** [comment]
Any news on this? Do you know if it is just a flaky test or if there is some real bug in the code?

**Comment by suihkulokki** [comment]
I seem to pass the test more reliably with:

diff --git a/inotify_test.go b/inotify_test.go
index 2527cad..227ac30 100644
--- a/inotify_test.go
+++ b/inotify_test.go
@@ -217,7 +217,7 @@ func TestInotifyStress(t *testing.T) {
                                        t.Fatalf("Create failed: %v", err)
                                }
                                handle.Close()
-                               time.Sleep(time.Millisecond)
+                               time.Sleep(2*time.Millisecond)
                                err = os.Remove(testFile)
                                if err != nil {
                                        t.Fatalf("Remove failed: %v", err)

That works on my machine, but I still get goroutine panic on asachi.debian.org (possibly a differrent, go issue)

**Comment by TheTincho** [comment]
The patch got scrambled by github, can you paste that again in a code block?

**Comment by suihkulokki** [comment]
@TheTincho  Repasted:

```
diff --git a/inotify_test.go b/inotify_test.go
index 2527cad..227ac30 100644
--- a/inotify_test.go
+++ b/inotify_test.go
@@ -217,7 +217,7 @@ func TestInotifyStress(t *testing.T) {
                                        t.Fatalf("Create failed: %v", err)
                                }
                                handle.Close()
-                               time.Sleep(time.Millisecond)
+                               time.Sleep(2*time.Millisecond)
                                err = os.Remove(testFile)
                                if err != nil {
                                        t.Fatalf("Remove failed: %v", err)
```

**Comment by TheTincho** [comment]
Still seems to be too sensible to timing.. For now I am disabling this test in the debian package..

**Comment by nathany** [comment]
@pattyshack provided a patch which has been merged to master. 

please (re)open the issue if you see any further flakiness.

**Comment by suihkulokki** [comment]
I've tested and didn't get a race so far. @TheTincho I think it should be safe to re-enable the test in debian again. Thanks @pattyshack for the fix!
