### ISSUE TITLE
Close on mac doesn't return

### ISSUE THREAD

**Issue by nikunjy** [fsnotify/fsnotify#146]
If you checkout kqueue.go 
https://github.com/fsnotify/fsnotify/blob/master/kqueue.go#L93

This statement will never execute because there is a blocking call in the event loop 
https://github.com/fsnotify/fsnotify/blob/master/kqueue.go#L323

Created a pull request, will add the fix
https://github.com/fsnotify/fsnotify/pull/145

**Comment by prashantv** [comment]
One option is to make the blocking call also check the `w.done` channel in a `select`,

``` go
select {
case w.Events <- event:
case <-w.Done:
  // quit logic here
}
```

**Comment by arp242** [comment]
The test case in #145 seems to work now for FreeBSD and macOS, so it seems that this has been fixed now.
