### ISSUE TITLE
Data race in test on tip/Linux

### ISSUE THREAD

**Issue by bep** [fsnotify/fsnotify#150]
Since tip is now 1.7beta we should look into this and report any real issue to the Go people:

https://travis-ci.org/fsnotify/fsnotify/jobs/135335818
https://travis-ci.org/fsnotify/fsnotify/jobs/124355194

I have not looked closely into this, but I tried to rebuild it once with the same error.

**Comment by bep** [comment]
OK, it is established that this is a faulty test.

**Comment by nathany** [comment]
Thanks @bep. It seems all the current pull requests are failing in odd ways. We should really look into fixing or removing faulty tests.

**Comment by nathany** [comment]
This may be related to #142.

> panic: Fail in goroutine after TestInotifyStress has completed
