### ISSUE TITLE
One backslash too much when watching files from a root directory

### ISSUE THREAD

**Issue by brunoqc** [fsnotify/fsnotify#151]
On Windows.

If I watch "c:\", the event name will be "c:\\\\something" instead of "c:\something".

If I watch a directory like "c:\test", the event name is correctly "c:\test\something".

**Comment by bep** [comment]
>If I watch "c:\", the event name will be "c:\something" instead of "c:\something".

What is the difference between the two?

**Comment by brunoqc** [comment]
Sorry about that. I fixed the comment. The source of the comment looked fine but github removed the extra backslash.

**Comment by ppknap** [comment]
Most likely we should replace `watch.path+"\\"+name` with `filepath.Join(watch.patch. name)`

https://github.com/fsnotify/fsnotify/blob/master/windows.go#L309
https://github.com/fsnotify/fsnotify/blob/master/windows.go#L319
https://github.com/fsnotify/fsnotify/blob/master/windows.go#L456
https://github.com/fsnotify/fsnotify/blob/master/windows.go#L494

**Comment by nathany** [comment]
Yes, we should be using `filepath.Join`.

For the moment, does it work to just watch "c:"?
