### ISSUE TITLE
Vagrant + Docker File Notification not working

### ISSUE THREAD

**Issue by HeathNaylor** [fsnotify/fsnotify#152]
My setup:
- Windows Host
  - Ubuntu Vagrant box
    - Ubuntu Docker Container
      - Go app

When I change a file on the windows host it is not detected by the app.

When I change a file on the vagrant virtualbox it is detected by the app.

Additionally, instead of a `Write` event being passed, two events fire, `chmod` and `rename`. This happens when I change the file on the vagrant virtualbox.

**Comment by nathany** [comment]
Hi. File notifications have a tendency of not working across shares (NFS, Vagrant mounts), but it is curious that changing a file in virtualbox worked in the container. I haven't tested this myself.

As far as the events passed, how are you changing the file? That may be related to how a text editor makes the change. See #17.

What are you hoping to accomplish? If you need to detect changes to files on the Windows host, you will most likely need to watch the files in Windows and then trigger whatever action you need. This seems to be the case.

If instead you are looking to watch files inside the vagrant box, it's best to use a directory that isn't shared from the Windows host, as that usually won't work (as you've seen).

**Comment by HeathNaylor** [comment]
I am using vim from within the vagrant machine to edit the file and the `:wq` command to save and quit vim. I suppose I could have my provision script move the .env file but then it is outside of my application and I will need to experiment with symlinking for my Go application's dotenv implementation to be able to find the file, hacky at best. My expectation would be to have the same code express the same behavior on my vagrant / docker as production /docker, and this is looking to not be the case. My last true step will be to deploy the compiled application to an actual Ubuntu instance and see if I get the same behavior. Not looking too good though.

**Comment by nathany** [comment]
Thanks for investigating this further. Unfortunately the underlying file notification systems have some limitations and differences, which make it difficult to get the consistent behaviour we would all like to have. If we can improve something though, we'll certainly try.

**Comment by arp242** [comment]
Tracking issue for saving with editors is #372.

The events not being detected doesn't really have enough information; how are the volumes mounted? As mentioned, things don't always work well with remote filesystems; a polling fallback could fix that, which is #9.
