### ISSUE TITLE
watchers leak inotify file descriptor when process fork/execs a child

### ISSUE THREAD

**Issue by msolo-dropbox** [fsnotify/fsnotify#155]
`inotify.go` needs a tiny patch in NewWatcher.

```
  // Set IN_CLOEXEC by default. The majority of use cases should not
  // pass this descriptor down.
  fd, errno := syscall.InotifyInit1(syscall.IN_CLOEXEC)
```

**Comment by nathany** [comment]
> IN_CLOEXEC
> Set the close-on-exec (FD_CLOEXEC) flag on the new file descriptor. See the description of the O_CLOEXEC flag...

> O_CLOEXEC (Since Linux 2.6.23)
> Enable the close-on-exec flag for the new file descriptor. Specifying this flag permits a program to avoid additional fcntl(2) F_SETFD operations to set the FD_CLOEXEC flag. Additionally, use of this flag is essential in some multithreaded programs since using a separate fcntl(2) F_SETFD operation to set the FD_CLOEXEC flag does not suffice to avoid race conditions where one thread opens a file descriptor at the same time as another thread does a fork(2) plus execve(2).

@pattyshack is working on a pull request.

What about support on ARM and PPC64? /cc @suihkulokki @TheTincho @clnperez @laboger @tophj-ibm?

**Comment by TheTincho** [comment]
@nathany You mean support for inotify_init1? I can test building this on those arches if it is just that.

**Comment by nathany** [comment]
@TheTincho That would be very helpful. inotify_init1 and the flags it takes.

I wonder if we should be using `IN_NONBLOCK` as well? https://github.com/fsnotify/fsnotify/blob/master/inotify_poller.go#L48

**Comment by nathany** [comment]
Is there any reason why someone would want the child process to have the inotify file descriptor carried over? 

Presumably a new one would be created in the child process instead if needed.

**Comment by pattyshack** [comment]
If you're share the inotify fd between between processes, the event
notifications may end up in either process.  In general, this behavior does
not seem particularly useful.

kqueue behaves the same way (i.e., child do not inherit kqueue) for the
same reason.

**Comment by TheTincho** [comment]
I have just tried PPC64 and ARMel, and it compiles and passes the tests correctly with this patch applied. Do you need me to test somewhere else too?
