### ISSUE TITLE
use absolute paths

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#160]
@jonasfj brought up an issue that "relative" paths are difficult to explain in the docs -- see #158 
and relative paths could also be confusing with multiple watches going on.

How about using `filepath.Abs` to make all the paths returned by the watcher absolute?

In terms of cost, it may be possible to use `filepath.Abs` on the input to `Watch` for all or most platforms, and let the OS return absolute paths. This would avoid calling `filepath.Abs` on every notification.

Would switching paths from relative to absolute be a breaking a change for some users?

**Comment by esiqveland** [comment]
I would prefer this.

The current situation is very confusing with the path being relative to the path of the directory watched.
So as when I watch `/home/username/src`, the so-called relative path results in `/home/username/src/created.txt`, yet if I am standing in `/home/username` and tell it to watch `src/`, it will be relative to this...

If the path was always absolute, it would be easier to know how to deal with it in all cases and much easier to create precise documentation.

**Comment by bep** [comment]
>Would switching paths from relative to absolute be a breaking a change for some users?

Yes, it would be a breaking change (one example would be Hugo). I do agree, though, that absolute paths would be a cleaner solution (and I'm willing to fix Hugo and relatives if you switch), but I also suspect there are other cross-platform gotchas in here somewhere.

**Comment by arp242** [comment]
Personally I think the current behaviour is okay; it's identical to how most tools work:

	[~cg/fsnotify]% ls README.md
	README.md

	[~cg/fsnotify]% ls ./README.md
	./README.md

	[~cg/fsnotify]% ls $PWD/README.md
	/home/martin/code/Golib/fsnotify/README.md

	[~cg/fsnotify]% ls *.md $PWD/*.md
	/home/martin/code/Golib/fsnotify/CHANGELOG.md     /home/martin/code/Golib/fsnotify/README.md  CONTRIBUTING.md
	/home/martin/code/Golib/fsnotify/CONTRIBUTING.md  CHANGELOG.md                                README.md

And many more.

Always having the full path is sometimes more awkward than helpful and you'll end up having to manually trim paths, for example for a `tail -F` written with fsnotify:

	[~cg/fsnotify]% tail -Fn1 *.md
	==> CHANGELOG.md <==
	[#21]: https://github.com/howeyc/fsnotify/issues/21

	==> CONTRIBUTING.md <==
	Releases are tagged using [Semantic Versioning](http://semver.org/).

	==> README.md <==

Printing the full path there doesn't make much sense. There are probably lots of other cases.

If you want absolute paths, you can pass absolute paths to `Add()`.

#466 clarifies the documentation on this.

**Comment by arp242** [comment]
Since this is an old issue which changes the API in an incompatible way, there isn't much feedback on this, and I'm not sure if we really need to change it in the first place, I'll close this for now. If people have strong feelings it should be changed we can always investigate further in the future based on feedback if people feel this should be changed.
