### ISSUE TITLE
Migrate tests to ginkgo

### ISSUE THREAD

**Issue by oozie** [fsnotify/fsnotify#167]
I was writing some concurrent tests that induce panic and I wanted wanted to propose something.

How do the maintainers feel about testing fsnotify with http://onsi.github.io/ginkgo/ ?

The framework offers superior BDD facilities. I believe that in the long run the project would benefit  from adopting this testing framework with better testability and highly-readable tests, concise tests.

**Comment by nathany** [comment]
HI Slawek. I would rather not introduce a testing dependency in fsnotify or other libraries I work on. I believe it's easier for contributors to use the baseline standard library tests that everyone should be familiar with. Personally I'm not a fan of BDD-style DSLs in Go. Nathan.
