### ISSUE TITLE
Is the poller really needed in inotify ? 

### ISSUE THREAD

**Issue by chmike** [fsnotify/fsnotify#171]
After inspecting the inotify code, I don't understand the need of the poller. Note that I'm an inexperienced go programmer. 

The poller is a complex thing with a method wake() that can be called to suspend a blocking wait. This wake is only used by the Close() method to suspend a wait on the inotify fd. 

Why not simply perform a blocking read and using a close of the inotify fd as the notification method ? The read will return 0 on a closed fd. In this case the the goroutine would terminate gracefully.

**Comment by chmike** [comment]
I found the answer to my own question. Closing the socket allows the kernel to reuse it. 
If the goroutine is blocked on the read when the fd is closed, things work as expected. But if the goroutine was doing something else, there is a time gap where the kernel can reuse the fd so that when the goroutine reaches the read it will be performed on the reassigned fd. You may then read from a file or a socket. 
Even if you add a bool flag that you test just before performing the read, there will still be a time gap between the test and the read where the Close can be performed and the fd reused by the kernel.  
This implies thus that another mechanism is used to inform the goroutine that it must stop. The use of epoll or equivalent is then required.

**Comment by nathany** [comment]
FYI, epoll was added in #66. It certainly complicates the code quite a lot.

**Comment by am11** [comment]
@chmike, just curious, if we are in control of `inotify_init`, `inotify_add_watch`, `inotify_rm_watch` and `close` calls, how/when would the 'unexpectedly closing of socket' happen?

ps: I gather that is the justification of epoll-with-inotify here, but two are not commonly used together this way in other projects; hence my curiosity. :)

**Comment by chmike** [comment]
Sorry, that problem is too old. I don't remember anything. I can't help.
