### ISSUE TITLE
Problem when moving watched directory with inotify

### ISSUE THREAD

**Issue by chmike** [fsnotify/fsnotify#172]
When renaming/moving a watched directory that is not inside a watched directory, fsnotify informs of the renaming, but:
1. doesn't update the name stored internally
2. keeps tracking changes inside the directory
3. report names starting with the old name for changes inside it 
4. attempt to remove the watch will fail wit an error

This is deduced from reading the code and testings with inotify. I didn't verify if this happens and how fsnotify would precisely behave (e.g 4).  I'm confident that this is the case.

The reason is due to inotify not returning the new name of the watched directory (IN_MOVE_SELF). If the watched directory is inside a watched directory than the new name may be obtained, but this needs some smart operation. If that watched directory is moved out of the watched directory, it is still watched, bu the new name is unknown and the watcher can't be removed. 

One possible fix is to automatically unwatch moved/renamed directories that aren't inside a watched directory. Watched directories inside another watched directories should be unwatched only when moved out of the enclosing watched directory. This is required because it is not possible to know their new name. 

It is yet unclear if it is possible to track directory moves from one watched directory to another watched directory (could be a subdirectory ) I need to do further tests.

**Comment by chmike** [comment]
If fact point 4 is not correct. It is possible to remove the watch but by using the name used to register the directory.

The problem is due to a limitation of inotify. 

One of the consequences of a rename/move of a watched dir is that the returned path is invalid. So you may be informed of modifications inside the directory, but you wouldn't be able to access the files to get the stats for instance because the path is wrong. It requires more work to properly keep track of subdirectory moves.

**Comment by nathany** [comment]
related #170
