### ISSUE TITLE
proposal: low-level platform-specific packages

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#173]
I'd like to suggest extracting an **inotify** package from fsnotify. It could be greenfield implementation using fsnotify as a reference or involve some actual copy/paste.

It would wrap syscall's `InotifyInit` and epoll with a idiomatic Go API (e.g. `inotify.MovedTo` rather than IN_MOVED_TO) for all the Inotify events available on Linux. 

Once created, inotify would become a dependency of fsnotify. Fsnotify would be focused on a common cross-platform API and smoothing out the differences between operating systems.

The [golang.org/x/sys/unix](https://godoc.org/golang.org/x/sys/unix) package doesn't provide integration tests -- a key goal is to have a **reliable test suite**. Ideally the test suite will be exercised across all architectures that Go supports Linux on by utilizing the Go builders (Go issue https://github.com/golang/go/issues/17312).

NOTE: The same extraction can and should be applied to kqueue and "winfsnotify" in the future. I think it will be most beneficial for inotify, due in part to the [number of architectures that Linux supports](https://build.golang.org/).

A secondary goal is to fully understand and **document the behaviours** of inotify without the added layers that fsnotify provides.

I think this would be placed in a separate repository `fsnotify/inotify` though the issue tracker may be shared (as with the Go project). Inotify would:
- Offer a well-maintained replacement for [golang.org/x/exp/inotify](https://godoc.org/golang.org/x/exp/inotify) for anyone using inotify directly.
- Provide a low-level library that could be used by https://github.com/rjeczalik/notify or other alternatives to fsnotify.
- Becomes a dependency of fsnotify -- though it can be vendored as a internal package of fsnotify if desired. (NOTE: this may impact the old gopkg.in import paths)

~~Before beginning~~ As part of this endeavour, I think it makes sense to address any [open pull requests](https://github.com/fsnotify/fsnotify/pulls?q=is%3Aopen+is%3Apr+label%3A%22Linux+%28inotify%29%22) and [open bugs](https://github.com/fsnotify/fsnotify/issues?q=is%3Aopen+is%3Aissue+label%3A%22Linux+%28inotify%29%22+label%3Abug) with inotify. 

Any volunteers interested in working on this? To proceed, we need enough involvement to have good code review processes in place.

**Comment by nathany** [comment]
Please add your name here if you're interested in building and maintaining an inotify lib that fsnotify uses.

**Comment by tiwaana** [comment]
I would love to work on this

**Comment by nathany** [comment]
Should this effort include fanotify on Linux as well? #114

**Comment by tiwaana** [comment]
Yes, I like the idea of including fanotify, but to get things going, I want to resist it. Couple of people in our Go meetup (DTC - Denver) have interest in working on it. I will be doing a presentation on inotify subsystem in our next meetup to bring people up to speed and see how far we can go as a group.

**Comment by nathany** [comment]
@tiwaana Sounds awesome. Is the next DTC meetup the Feb 16 launch party for Go 1.8?

**Comment by tiwaana** [comment]
its after that, this one is more so for 1.8 release. All 3 meetups are coming together boulder, denver and DTC and doing a combined one.

**Comment by arp242** [comment]
My main concern with "just" splitting off packages is that people will use them when they shouldn't. What I mean is that someone will search for "inotify golang", find the fsnotify/inotify, and then use it when they really "should" be using fsnotify/fsnotify.

Not only will this cause the program to be needlessly broken on non-Linux platforms, it also means it won't work optimally on Linux: if we add fanotify API support then you will "automatically" get this if you update fsnotify, but not if you update inotify. Possible fixes/workaround for things like Docker volumes or NFS drives also won't be available, etc.

All of that being said, there are certainly use cases where using inotify "directly" is useful; at $dayjob we write Go code and will only ever run it on Linux, and I can see us using some more advanced stuff that the cross-platform fsnotify can't offer us.

A second reason is that we'll forever be updating go.mod in fsnotify, and that the code becomes harder to work with (need to replace in go.mod or use a workspace); fsnotify and inotify will still be deeply related. Some patches will touch on multiple backends, and before you know it you're dealing with 5 PRs in 5 repos for one "change".

---

What I think would be better is to create github.com/fsnotify/fsnotify/{inotify,kqueue,...} subpackages here, which don't really need documentation beyond the godoc API docs. This way, it's still fairly easy to find for folks who need it, but not so "obvious" that people will start using it when they probably shouldn't.

A good first step would be to move some of the code to internal/inotify etc. This gives us some time to work out things over time without worrying about compatibility (it may be required to have a slightly different API from the main fsnotify package).

**Comment by nathany** [comment]
An internal subpackage that may eventually become a public sub package sounds good.

>  I can see us using some more advanced stuff that the cross-platform fsnotify can't offer us

At one point there was a proposal to do something similar to [os.FileInfo.Sys()](https://pkg.go.dev/io/fs#FileInfo) to expose platform-specific flags for people who need it. I'm not sure if that's a good idea or whether a few flags would be sufficient, but it may worth exploring ways to expose platform-specific features instead of exposing an entire sub package.

**Comment by arp242** [comment]
Yeah, something like `.Sys()` may also be a good idea; pretty sure there's an open issue for that. I'm not 100% sure what the best approach is here. For starters, need to look if a `.Sys()` can do everything that we want.

**Comment by arp242** [comment]
Still, I like the idea of at least `internal/inotify` purely for development reasons and splitting the code out a bit, regardless of whether we ever actually more that anywhere else.

**Comment by arp242** [comment]
At some point things may get refactored, but I don't think there's much point in keeping an issue open for this.
