### ISSUE TITLE
Monitoring access to device files is not working

### ISSUE THREAD

**Issue by botherder** [fsnotify/fsnotify#182]
I am using Debian:

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:    testing
Codename:   stretch

I am noticing that if I create watchers on device files (e.g. `/dev/video0`), fsnotify is not able to observe any events while inotify-tools does. Is there any particular reason why that would happen?

Are there changes that can be implemented to add support for it?

**Comment by nathany** [comment]
Thanks for reporting the issue. Would you mind elaborating with specifically what you do with inotify-tools that does work for those not familiar with it?

**Comment by botherder** [comment]
Given the following snippet of code:

`package main

import (
    "log"
    "github.com/mqu/go-notify"
    "github.com/botherder/fsnotify"
)

func main() {
    watcher, err := fsnotify.NewWatcher()
    if err != nil {
        log.Fatal(err)
    }
    defer watcher.Close()

    done := make(chan bool)
    go func() {
        for {
            select {
            case event := <-watcher.Events:
                if event.Op&fsnotify.Access == fsnotify.Access {
                    log.Println("ACCESS!")

                    notify.Init("ALERT")
                    warning := notify.NotificationNew("ALERT", "Something is trying to access the webcam!", "")
                    notify.NotificationShow(warning)
                }
            case err := <-watcher.Errors:
                log.Println("error:", err)
            }
        }
    }()

    err = watcher.Add("/dev/video0")
    if err != nil {
        log.Fatal(err)
    }
    <-done
}`

It is not able to observe access events on `/dev/video0`. Given, this is using my fork with ACCESS events enabled, but I know that it works fine on other regular files.
Instead using for example `inotifywait /dev/video0`, it does correctly trigger an event if the device is opened (e.g. by capturing the webcam using VLC):

`Setting up watches.
Watches established.
/dev/video0 OPEN.`

**Comment by TheZ3ro** [comment]
Any news about this?

**Comment by botherder** [comment]
Not that I know, still not working for me.

**Comment by TheZ3ro** [comment]
I'm working on detecting `/dev/video*` and `/dev/bus/usb` for a Go version of https://github.com/thez3ro/nsaway

It seems that the event on `/dev/video*` is an IN_OPEN and not IN_ACCESS.
(you can test it with `inotifywait /dev/video0` from `inotify-tools`1 package)

I've made this patch https://github.com/TheZ3ro/fsnotify/commit/ed469fb0372648da575ad821e79fc0b607e33cc0 that works like a charm :wink:

**Comment by botherder** [comment]
@TheZ3ro it seems like you're doing exactly what I was setting out to do. I would be happy to collaborate on this project instead of duplicating efforts. Contact me if you want.

**Comment by thockin** [comment]
It looks like nothing happened with this - does this project want to be aware of OPEN events?

**Comment by cpuguy83** [comment]
I'm honestly not seeing a good reason not to, maybe it will need to be documented that open is only supported on whatever backend.

**Comment by thockin** [comment]
It could either be a new Op of its own, or maybe a more more general
"Access" Op which captures other impl-specific events?
