### ISSUE TITLE
Is it possible to obtain EVENT of a file which has been removed or moved?

### ISSUE THREAD

**Issue by headwindfly** [fsnotify/fsnotify#184]
I am using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

### Please describe the issue that occurred.
I use the example code of [Documentation](https://godoc.org/github.com/fsnotify/fsnotify) to watch a file(named `test.txt`).

Is it possible to obtain EVENT of a file which has been removed or moved?

See reproduction.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

1. Create a file named `test.txt`.

2. Run the watcher.go

3. Remove/Move this file. 
```
event: ..... REMOVE
```

4. Create a new file named test.txt

command:`echo content > a`

```
// no event.
```

But I expect to obtain `Create` Event.

**Comment by vahe** [comment]
See the first question in the FAQ, quoted below:

> When a file is moved to another directory is it still being watched?
No (it shouldn't be, unless you are watching where it was moved to).

You're watching the file instead of watching for the directory the file is in. Watch the parent directory, and check if the event `Name` matches `test.txt`.

**Comment by headwindfly** [comment]
thanks

**Comment by nathany** [comment]
thanks @vahe. 

Maybe the FAQ and other documentation would be more visible if it were moved from the GitHub Wiki to the website? What do you two think?

https://github.com/fsnotify/fsnotify.org

**Comment by headwindfly** [comment]
Sorry, this is my mistake, I did not notice the FAQ.

@nathany I prefer to add **FAQ** in **README** (in my opinion, that will be more convenient and conspicuous):

```
## FAQ
1. [question1](link-to-question1)
2. [question2](link-to-question2)
....
```

**Comment by vahe** [comment]
@nathany @headwindfly I think copy/pasting FAQ contents into the README would be the most convenient since readme gets the most visibility. I had no idea that there was an fsnotify.org website, but I guess it wouldn't hurt to have it there too.

**Comment by nathany** [comment]
Moving the FAQ to the README sounds good. Let's do it.
