### ISSUE TITLE
Example is outdated

### ISSUE THREAD

**Issue by Allendar** [fsnotify/fsnotify#185]
The example of the project on https://godoc.org/github.com/fsnotify/fsnotify#example-NewWatcher seems outdated:

```
if event.Op&fsnotify.Write == fsnotify.Write {
```

should be:

```
if event.IsModify() {
```

and:

```
err = watcher.Add("/tmp/foo")
```

should be:

```
err = watcher.Watch("/tmp/foo")
```

Nice project 👍

**Comment by hekaldama** [comment]
I am not seeing that API. Maybe you are confused with: https://godoc.org/github.com/howeyc/fsnotify ?

**Comment by Allendar** [comment]
It doesn't seem to be that. When expanding the example this is the example code (as directly linked on the README of this project's Github page):

```
watcher, err := fsnotify.NewWatcher()
if err != nil {
    log.Fatal(err)
}
defer watcher.Close()

done := make(chan bool)
go func() {
    for {
        select {
        case event := <-watcher.Events:
            log.Println("event:", event)
            if event.Op&fsnotify.Write == fsnotify.Write {
                log.Println("modified file:", event.Name)
            }
        case err := <-watcher.Errors:
            log.Println("error:", err)
        }
    }
}()

err = watcher.Add("/tmp/foo")
if err != nil {
    log.Fatal(err)
}
<-done
```

**Comment by nathany** [comment]
Hi @Allendar. The example we have is correct and tested by the test suite. I'm not sure what the confusion is here, but I'm closing this issue.
