### ISSUE TITLE
Need an Operation for Linux - IN_CLOSE_WRITE

### ISSUE THREAD

**Issue by radu-munteanu** [fsnotify/fsnotify#191]
The real world scenario I have is about knowing when a file is fully copied to a location via FTP, SMB or other means, on Linux. The existing Create doesn't do fully justice to files, only to directories. The Write (IN_MODIFY) operation is not fully helpful in this case, because I can get a lot of these messages, but not knowing exactly when the transfer has finished.

I don't know if there is something similar to IN_CLOSE_WRITE on other systems, that's why I made this issue, to create the base for a discussion.

One way to solve this problem is to create a new cross-platform operation, which on some systems might have the same meaning with Write.

Another way, that is a bit ugly, but will fix any similar issues in the future, is to add the uint32 Mask to the Event. This way any developer could handle the Mask itself, in case it builds a platform specific software.

**Comment by radu-munteanu** [comment]
I've created a new Op called "Update" on my fork, and used it on inotify to represent  unix.IN_CLOSE_WRITE  and unix.IN_MOVED_TO. I didn't write any tests. 

[https://github.com/radu-munteanu/fsnotify/commit/6638bfdb7939ba8a4687a44cdff21906d9b547c9](https://github.com/radu-munteanu/fsnotify/commit/6638bfdb7939ba8a4687a44cdff21906d9b547c9)

Warning: I didn't write any tests for this Op.

**Comment by radu-munteanu** [comment]
I've created a new Op called "Update" on my fork, and used it on inotify to represent  unix.IN_CLOSE_WRITE  and unix.IN_MOVED_TO. I didn't write any tests. 

[https://github.com/radu-munteanu/fsnotify/commit/a52516bed152ed36854ef441dce07b0c4dfce458](https://github.com/radu-munteanu/fsnotify/commit/a52516bed152ed36854ef441dce07b0c4dfce458)

Warning: I didn't write any tests for this Op.

**Comment by nathany** [comment]
related: #22, #131

**Comment by hallyn** [comment]
Hi, (1) are you planning on doing a pull request from your fork, and (2) would you by any chance consider adding a purer CLOSE (IN_CLOSE_WRITE|IN_CLOSE_NOWRITE) op?

**Comment by nathany** [comment]
I think this needs more discussion before opening any pull requests, as it likely involves an addition or change to the API, and fsnotify is a cross-platform API.

The suggestion of exposing a file-system specific mask might not be such a bad idea. See [FileInfo](https://golang.org/pkg/os/#FileInfo) as an example:

```
Sys() interface{}   // underlying data source (can return nil)
```

Also see #173 regarding the spinning out of a stand-alone package specifically for Linux.

**Comment by radu-munteanu** [comment]
@hallyn (1) As @nathany said, the fsnotify is more about being cross-platform than anything. The pull would only make this operation be useful on unix. (2) That I can do, if people need it. It's pretty easy to expand up to 32 Ops.

@nathany The ugly part about exposing the mask is that, how it's written now, the watcher is filtering the notifications by those agnosticEvents, and we would need either to remove this part, or have a flags parameter. The first option will generate a lot of unwanted messages, the second option would make the fsnotify less cross-platform code friendly.

@nathany I read that part about the spin-off. It's a great idea, but I saw that the project is empty. If someone who knows what they're doing the basic code there, I'd try to expand it with any functionality I need.

**Comment by radu-munteanu** [comment]
@hallyn I've enabled the issues option on my fork. If you need that Op, write a new issue there. Thanks.

**Comment by nathany** [comment]
@radu-munteanu I'm hoping a few people step up to build and maintain the inotify spin-off. Then there is still some amount of work to integrate that back into fsnotify with a cross-platform API.

I'm not sure if > 32 or > 64 ops would really be necessary, but it is certainly worth considering alternative approaches to the API for the spin-off. 

Hoping to keep the cross-platform fsnotify API itself fairly stable.

**Comment by nathany** [comment]
kqueue (BSD) also has NOTE_CLOSE_WRITE and NOTE_CLOSE.

**Comment by matthias-stone** [comment]
This duplicates #22, trying to centralize discussion their.

This will likely be addressed by pulling inotify out to a separate package people can use, as proposed in #173.
