### ISSUE TITLE
When used continuously and frequently fsnotify appears to cause total Operating System crash on Ubuntu 14 LTS

### ISSUE THREAD

**Issue by ben-greco** [fsnotify/fsnotify#192]
### Before reporting an issue, please ensure you are using the latest release of fsnotify:

I have the most recent version of fsnotify and dependencies in the golang.org/x/sys package

### Which operating system (GOOS) and version are you using?

I am running a virtualized Ubuntu server on VMWare VCenter Enterprise, but the code was compiled on Mac OSX (using the correct command for the destination operating system).

OUTPUT:

Linux: lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Compiled with:
`GOOS=linux GOARCH=amd64 go build`

### Please describe the issue that occurred.

I created a goroutine to monitor for the creation of files using fsnotify. If the file created from the create event matches a certain name, it is given a new name with an id generation function. 

When this program is run continuously and a new file matching the criteria is created **exactly every two seconds** the operating system eventually completely crashes. The output in the terminal is a series of hexadecimal memory addresses. A picture of the output is attached. 
![screen shot 2016-12-15 at 4 26 41 pm](https://cloud.githubusercontent.com/assets/14946747/21242670/662100d0-c2e3-11e6-9782-8724cbe48b82.png)

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

I can reproduce the issue repeatedly, even after completely erasing and spinning up a new Ubuntu 14 LTS virtual machine from installation media. 

Here is the code used ~~(for some reason only parts of it format correctly in my preview)~~: 
```go
// CheckFileForChanges notifies immediately upon report receipt and moves it to a new file with id and processing tag
func CheckFileForChanges(location, filename string) {

	// initializations
	cli := slackOutput.MyClient
	watcher, err := fsnotify.NewWatcher()
	utils.HandleError(err, "Could not open new file watcher")
	defer watcher.Close()
	done := make(chan bool)

	// this code is extrapolated from fsnotify examples
	go func() {
		for {
			select {
			case event := <-watcher.Events:
				if event.Op&fsnotify.Create == fsnotify.Create {

					// upon new report creation, send slack notify and move it with new id
					id := utils.IDGenerator()
					err := os.Rename(location+filename, location+"toBeProcessed_"+id)
					if err == nil {
						utils.MyLogger.Info("Report received and converted to processing to do list!")
						cli.SendAnySlack("New report received")
						//TODO make slack output say that a report was received, who it was from
						//and what exact dir it is in within one slack message
					}
				}
			case err := <-watcher.Errors:
				utils.HandleError(err, "Error has been thrown by watcher function")
			}
		}
	}()
	err = watcher.Add(location)
	utils.HandleError(err, "Problem adding file to watcher")
	<-done
}
```

**Comment by arp242** [comment]
Since this issue is over six years old and 1) many things changed in the meanwhile (this library, Go, Linux, etc.), 2) no one else seems to have reported this issue, so it doesn't seem like a common problem, and 3) a kernel panic is *probably* not due to this library as such but a problem in Linux or VMWare, I'll close this for now. We can reopen if you're still experiencing this issue.

**Comment by ben-greco** [comment]
Ha yeah I forgot about this and haven't used fsnotify for 5 years
