### ISSUE TITLE
watcher on unc does not work on dos prompt but works in cygwin ?

### ISSUE THREAD

**Issue by cesara** [fsnotify/fsnotify#198]
Windows 7

I have a watcher set on a UNC location \\servera\share\watchme when I try to run my code in a dos window I get GetFileAttributes: The specified path is invalid. However, if i run the exact same code in cygwin everything works fine.  Anyone know why this maybe ? Im using properly escaped strings for the UNC locations.

**Comment by arp242** [comment]
It calls `syscall.GetFileAttributes()` on the exact path that was passed in. Shouldn't UNC paths start with two backslashes (`\\server\...`)? Also make sure you're using backtick strings and not `""` strings (or use double backslashes in `""` strings) to avoid escaping.

Closing this for now as it's very old and not clearly reproducible.
