### ISSUE TITLE
Cannot go get -u golang.org/x/sys/...

### ISSUE THREAD

**Issue by dmonay** [fsnotify/fsnotify#204]
### Which operating system (GOOS) and version are you using?
```
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

Darwin MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

go version go1.8 darwin/amd64
```
### Please describe the issue that occurred.
Cannot `go get -u golang.org/x/sys/...` Go get cannot resolve the address:
```
$ go get -v -u golang.org/x/sys/...
Fetching https://golang.org/x/sys?go-get=1
https fetch failed: Get https://golang.org/x/sys?go-get=1: net/http: TLS handshake timeout
package golang.org/x/sys/...: unrecognized import path "golang.org/x/sys/..." (https fetch: Get https://golang.org/x/sys?go-get=1: net/http: TLS handshake timeout)
```
### Are you able to reproduce the issue?
Yes. Same thing happens every time I try to `go get` the dependency.
I believe this is related to https://github.com/tools/godep/issues/377 and the fact that this is redirected to godoc.

**Comment by bep** [comment]
Cannot what?

**Comment by dmonay** [comment]
Apologies - sent the issue before typing it out.

**Comment by dmonay** [comment]
Closing the issue as this is not a problem with `fsnotify`. Turns out this was caused by OpenDNS - I set two of their servers as my default DNS resolution servers and this led to system-wide issues with https. `go get` failed for a number of go packages that are hosted over https, including `golang.org/x/sys`.

**Comment by 359274651** [comment]
@dmonay  Hi, now i miss the problem , Can you tell me solution method?

**Comment by gundamlh** [comment]
create a directory (like in golang.org/x) yourself and then
git clone https://github.com/golang/sys.git  
the credit goes to https://zhuanlan.zhihu.com/p/30964604

**Comment by dmonay** [comment]
@jokerbo1 as I mentioned in an above comment, this was caused by system-wide DNS settings on my machine.

**Comment by DataDea** [comment]
clone from github
