### ISSUE TITLE
Trigger write event twice

### ISSUE THREAD

**Issue by l108103t** [fsnotify/fsnotify#206]
OS: Windows 7, 64bit
GOOS: go1.8 windows/amd64

Every time, i write somthing to a file, the write event will be triggered twice. Is this a bug or i did something wrong?

**Comment by bep** [comment]
I think you will find that this is a limitation in the file change notification systems on the different OSs, and the events created also depends on the editor used; in Hugo we handle this by throwing away events we don't care about, including duplicate WRITE.
