### ISSUE TITLE
Cannot remove watch for deleted directory on windows

### ISSUE THREAD

**Issue by charlie103** [fsnotify/fsnotify#208]
After i delete a directory,i want to remove the watch for it ,i write the code like this
`if err := watcher.Remove(dire); err != nil{
						fmt.Println("Something wrong happened when remove watch ",dire,"err=",err)
} `

but i got error 
"GetFileAttributes:The system cannot find the file specified"

GOOS: go1.8 windows/amd64
Windows7 64bit

**Comment by nc-mcarter** [comment]
For the record, this is still an issue on Windows as of v1.9.0 fsnotify release. 

https://github.com/fsnotify/fsnotify/pull/494 was marked as fixing the linked issue #268 but https://github.com/fsnotify/fsnotify/pull/494#issue-1331109851 makes clear that Windows issues were not addressed in that commit
