### ISSUE TITLE
I want to change code to support IN_CLOSE_WRITE in linux, but it don't work, please help.

### ISSUE THREAD

**Issue by runner365** [fsnotify/fsnotify#209]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### I have changed some code, want to support IN_CLOSE_WRITE in linux.
func (w *Watcher) Add(name string) error {
        name = filepath.Clean(name)
        if w.isClosed() {
                return errors.New("inotify instance already closed")
        }
        const agnosticEvents = unix.IN_MOVED_TO | unix.IN_MOVED_FROM |
                unix.IN_CREATE | unix.IN_ATTRIB | unix.IN_MODIFY |
                unix.IN_MOVE_SELF | unix.IN_DELETE | unix.IN_DELETE_SELF |
                **unix.IN_CLOSE_WRITE | unix.IN_CLOSE**
.............
}

func (w *Watcher) readEvents() {
..............
                        mask := uint32(raw.Mask)
                        nameLen := uint32(raw.Len)
                        **fmt.Printf("raw.Mask=0x%08x\r\n", mask)**
..............
}
but, the raw.Mask doesn't have unix.IN_CLOSE_WRITE | unix.IN_CLOSE.

### the test is made of python:
import os
import time

def Main():
    path = '/mytest_dir/'
    index = 0;
    while 1:
        filepath = path + 'test' + str(index) + '.txt'

        pFile = open(filepath, 'wb')
        print 'open file: ', filepath
        time.sleep(2)
        pFile.write(filepath)
        print 'write file:', filepath
        time.sleep(2)
        pFile.close()
        index = index + 1

        print 'close file: ', filepath
        time.sleep(2)

if __name__ == '__main__':
    Main()

**Comment by radu-munteanu** [comment]
HI,

You're missing the part where you identify  unix.IN_CLOSE_WRITE with an operation.


Look for the lines similar to this, and add your unix.IN_CLOSE_WRITE and unix.IN_CLOSE:
```

if mask&unix.IN_ATTRIB == unix.IN_ATTRIB {
 		e.Op |= Chmod
}
```

You can check my fork commit, where I add a totally new operation: https://github.com/radu-munteanu/fsnotify/commit/f8f617d6740c0f6861cebcf926c4c133aa3ba129

**Comment by jlory** [comment]
Any updates on that? I'm having errors using trigger on large file being written because IN_CLOSE_WRITE  is not yet implemented.

**Comment by matthias-stone** [comment]
We're hoping to support write_close by making using inotify directly an option (#173), but for now questions like this are better suited for the fsnotify channel on the gophers slack. Invites available from https://invite.slack.golangbridge.org/.
