### ISSUE TITLE
how to forbid a file been changed in windows under fsnotify's watching

### ISSUE THREAD

**Issue by yankunsam** [fsnotify/fsnotify#213]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: lsb_release -a
macOS: sw_vers
Windows: systeminfo | findstr /B /C:OS

**Comment by dylan-bourque** [comment]
Not really sure about what you're asking, but preventing changes to the files being watched is out of scope for this project.  Please re-open with more details if I misunderstood.
