### ISSUE TITLE
Suggestion: keep watching file on rename

### ISSUE THREAD

**Issue by horsley** [fsnotify/fsnotify#214]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

macOS: 10.12.6

### Please describe the issue that occurred.

Now fsnotify remove watcher on file rename events, why we can't keep it? It's a normal operation in some scenario. The editor VIM save file by renaming origin file to a backup first, then create the file with the old name and write the new content. Currently fsnotify remove the watcher internally, the program will miss some events even if you re-watch that file.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

Use example_test.go watch a specific file and vim to edit and save, easy to reproduce

**Comment by swift1911** [comment]
+1

**Comment by radu-munteanu** [comment]
It's not as easy as it seems. fsnotify is based on the file system and OS features. For example, on GNU/Linux, inotify is takeing the info based on the inode of the file, and not the file name. If a file is deleted and it is created again, it may have a different inode.

If you really need to closely watch a certain file, always check its parent directory. And to be 100% sure you should check all the parents until the root directory. If you don't need this kind of precision, you can just do enable a timer/ticker when a file is deleted and check from time to time when it appears again and recreate the watcher.

**Comment by omeid** [comment]
> The editor VIM save file by renaming origin file to a backup first, then create the file with the old name and write the new content.
From the filesystem point of view, the newly created file has no relation with the original file at all, and so keeping track of that is outside the scope of fsnotify.

Strictly speaking the book keeping you're asking for is not concern of filesystem notification directly and so such functionality is better implemented on top of fsnotify as it's own independent package.

**Comment by stu-b-doo** [comment]
I'm using vim to modify a file I want to watch. Watching the parent directory and checking only for write events of the original filename. Doesn't include @radu-munteanu's suggestion of checking all parent directories. It also seems to return multiple WRITE events each time I save the file from the editor. It's simple but works for what I need. 

adapted from https://github.com/fsnotify/fsnotify/blob/master/example_test.go
```
package main

import (
	"log"
	"os"
	"path/filepath"

	"github.com/fsnotify/fsnotify"
)

func main() {

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	// file name from first arg
	if len(os.Args) < 2 {
		log.Fatal("No file path provided")
	}
	fileNamePath := os.Args[1]
	_, fileName := filepath.Split(fileNamePath)

	// listen for watcher events
	done := make(chan bool)
	go func() {
		for {
			select {
			case event := <-watcher.Events:

				// only work on WRITE events of the original filename
				if event.Op&fsnotify.Write == fsnotify.Write && event.Name == fileName {

					log.Println("modified file:", event.Name)

				}
			case err := <-watcher.Errors:
				log.Println("error:", err)
			}
		}
	}()

	// watch the parent dir of the file to catch changes
	err = watcher.Add(filepath.Dir(fileNamePath))
	if err != nil {
		log.Fatal(err)
	}

	// wait indefinitely so the go routine continues
	<-done
}
```

**Comment by gdey** [comment]
dup #17

**Comment by gorpher** [comment]
If you don't want to listen to a folder and just want to listen to files, you can use the following method.

```go
package main

import (
	"log"
	"os"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()
	if len(os.Args) < 2 {
		log.Fatal("No file path provided")
	}

	fileNamePath := os.Args[1]
	done := make(chan bool)
	go func() {
		for {
			select {
			case event := <-watcher.Events:
				log.Printf("event:%s,%s", event.Name, event.Op)
				if event.Op&fsnotify.Remove == fsnotify.Remove {
					if FileExist(fileNamePath) {
						log.Printf("reread  file:%s ", fileNamePath)
						err := watcher.Add(fileNamePath)
						if err != nil {
							log.Println("error:", err)
						}
					}
				}
				// only work on WRITE events of the original filename
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err := <-watcher.Errors:
				log.Println("error:", err)
			}
		}
	}()
	err = watcher.Add(fileNamePath)
	if err != nil {
		log.Fatal(err)
	}
	// wait indefinitely so the go routine continues
	<-done

}
func FileExist(file string) bool {
	_, err := os.Stat(file)
	if err != nil {
		if os.IsExist(err) {
			return true
		}
		if os.IsNotExist(err) {
			return false
		}
		return false
	}
	return true
}
```
