### ISSUE TITLE
keep relax . not bug

### ISSUE THREAD

**Issue by SilenMark** [fsnotify/fsnotify#217]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

>sure.i'm using the latest release of fsnotify

### Which operating system (GOOS) and version are you using?

>Linux: ubuntu16.04
>macOS: sierra

### Please describe the issue that occurred.

>i want to watch the go file change for build project.
but it not work on macos. i find when i use vim to edit file this problam will happen ，but use sublime work well. when use vim (with swapfile)on save. the event.op is chmod on macos. the same vim config on ubuntu16.04 .will fire chmod and write event.

[stackoverflow](https://stackoverflow.com/questions/7591527/writing-a-file-with-vim-doesnt-fire-a-file-change-event-on-os-x)

>suggest put it on readme.

**Comment by gdey** [comment]
Dup of #17
