### ISSUE TITLE
Event message is lost

### ISSUE THREAD

**Issue by jokerbo1** [fsnotify/fsnotify#220]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
macOS: 10.11.5

### Please describe the issue that occurred.
I edit a code ,i want test this program real time print event message ,but the log print is lost part,follow this:
2017/09/26 17:08:47 0
2017/09/26 17:08:47 新建文件
2017/09/26 17:08:47 1
2017/09/26 17:08:47 新建目录
2017/09/26 17:08:47 2
2017/09/26 17:08:47 删除文件
2017/09/26 17:08:47 删除文件 ./testdir/file0
2017/09/26 17:08:47 3
2017/09/26 17:08:47 新建文件
2017/09/26 17:08:47 4
2017/09/26 17:08:47 新建目录
2017/09/26 17:08:47 5
2017/09/26 17:08:47 event: "testdir/dir1": CREATE
2017/09/26 17:08:47 删除文件
2017/09/26 17:08:47 删除文件 ./testdir/dir1
2017/09/26 17:08:47 event: "testdir/dir4": CREATE
2017/09/26 17:08:47 event: "testdir/file3": CREATE
2017/09/26 17:08:47 event: "testdir/dir1": REMOVE

another this is my code:

```go
func ExampleNewWatcher() {
	flist := list.New()
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	//filepath.Walk()
	defer watcher.Close()
	//files := []string{}
	done := make(chan bool)
	go func() {
		for {
			select {
			case event := <-watcher.Events:
				log.Println("event:", event)
				//event.
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err := <-watcher.Errors:
				log.Println("error:", err)
				time.Sleep(10 * time.Second)
			}
		}
	}()

	err = watcher.Add("./testdir")
	if err != nil {
		log.Fatal(err)
	}
	time.Sleep(3 * time.Second)
	for j := 0; j < 6; j++ {
		log.Println(j)
		//新建
		if j%3 == 0 {
			log.Println("新建文件")
			s := strconv.Itoa(j)
			f, e := os.Create("./testdir/file" + s)

			if e != nil {
				log.Fatal(e.Error())
			}
			f.Close()
			flist.PushBack("./testdir/file" + s)
		}
		// 新建目录
		if j%3 == 1 {
			log.Println("新建目录")
			s := strconv.Itoa(j)
			e := os.MkdirAll("./testdir/dir"+s, os.ModePerm)
			//ioutil.
			if e != nil {
				log.Fatal(e.Error())
			}
			flist.PushBack("./testdir/dir" + s)
			//f.Close()
		}
		//删除目录或文件
		if j%3 == 2 {
			//s :=strconv.Itoa(j)
			log.Println("删除文件")
			ele := flist.Front()

			//f,e:=  os.Open()
			if v, ok := ele.Value.(string); ok {
				os.RemoveAll(v)
				log.Println("删除文件", v)
			}
			flist.Remove(ele)

			//if e!=nil{
			//log.Fatal(e.Error())
			//}

			//f.Close()
		}

	}
	<-done
}
```

please .help solution the problem ,thanks.
### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.
 
actually ,if you can run me paste the code ,you can view the log ,print is lost  create file or remove dir .

@evanphx @markbates @paulhammond @tmc @nathany   excuse me.

**Comment by dylan-bourque** [comment]
Confirmed that only 5 events are generated for the 6 operations (2 file creations, 2 directory creations, 2 deletes) on Linux

Slightly modified repro steps:
```
package main

import (
	"container/list"
	"log"
	"os"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
)

func main() {
	flist := list.New()
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	//filepath.Walk()
	defer watcher.Close()
	//files := []string{}
	var wg sync.WaitGroup
	wg.Add(6)
	go func() {
		for {
			select {
			case event := <-watcher.Events:
				log.Println("event:", event)
				//event.
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err := <-watcher.Errors:
				log.Println("error:", err)
				time.Sleep(10 * time.Second)
			}
			wg.Done()
		}
	}()

	_ = os.Mkdir("testdir", os.ModePerm)
	defer os.RemoveAll("testdir")

	err = watcher.Add("./testdir")
	if err != nil {
		log.Fatal(err)
	}
	time.Sleep(3 * time.Second)

	f, _ := os.Create("testdir/file0")
	f.Close()
	flist.PushBack("testdir/file0")

	_ = os.MkdirAll("testdir/dir1", os.ModePerm)
	flist.PushBack("./testdir/dir1")

	ele := flist.Front()
	_ = os.RemoveAll(ele.Value.(string))
	flist.Remove(ele)

	f, _ = os.Create("testdir/file3")
	f.Close()
	flist.PushBack("testdir/file3")

	_ = os.MkdirAll("testdir/dir4", os.ModePerm)
	flist.PushBack("./testdir/dir4")

	ele = flist.Front()
	_ = os.RemoveAll(ele.Value.(string))
	flist.Remove(ele)

	wg.Wait()
}
```

**Comment by nathany** [comment]
@dylan-bourque Do you want to reopen this and continue to investigate this?

Suppose the question is whether this is inotify behaviour or if fsnotify's particular implementation is losing an event.

**Comment by dylan-bourque** [comment]
Someone probably should, but I won't have time to look at it for at least a couple of weeks. I'll assign it to myself and see what I can find.

**Comment by arp242** [comment]
This code:

	func TestXXX(t *testing.T) {
		w := newWatcher(t)
		defer w.Close()

		go func() {
			for {
				select {
				case event := <-w.Events:
					log.Println("event:", event)
				case err := <-w.Errors:
					log.Println("error:", err)
				}
			}
		}()

		tmp := os.TempDir()
		addWatch(t, w, tmp)
		time.Sleep(3 * time.Second)

		touch(t, tmp, "file0")
		mkdir(t, tmp, "dir1")
		rm(t, tmp, "file0")
		touch(t, tmp, "file3")
		mkdir(t, tmp, "dir4")
		rm(t, tmp, "dir1")
	}

Generates:

	"/tmp/file0": CREATE      # touch file0
	"/tmp/dir1":  CREATE      # mkdir dir1
	"/tmp/file0": REMOVE      # rm file0
	"/tmp/file3": CREATE      # touch file3
	"/tmp/dir4":  CREATE      # mkdir dir4
	"/tmp/dir1":  REMOVE      # rm dir1

Which seems alright to me?

The original example code is difficult to follow and needlessly complex; I think I converted it to the much simpler case correct though.

I'll close this for now, but please let me know if you can reproduce with a simpler example and we can reopen.
