### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by cpuguy83** [fsnotify/fsnotify#222]
The last release was tagged a year ago.
I'm not sure what the current state of the repo is wrt API changes but was wondering if we can get a new tagged release?

Users are reporting a deadlock that is supposedly fixed on master but not in any tagged release: moby/moby#35332

If it's safe to take master I can just take that but figured it would be worth checking if there can be a new tag.

Thanks! 🙇

**Comment by thaJeztah** [comment]
ping @markbates @nathany ptal 🤗

**Comment by markbates** [comment]
I agree a new version is probably warranted. I don't have the insight into the package to determine if that's ok or not. @nathany is probably in the best position to make that call.

**Comment by thaJeztah** [comment]
Thanks! I'll await @nathany's input 👍

**Comment by nathany** [comment]
Sounds like a mighty good idea, though I have no insight into what has changed since the last release, or if it's "safe" to tag a new release.

As per [my comment here](https://github.com/fsnotify/fsnotify/issues/183#issuecomment-286456045), I haven't been following the project since March.

**Comment by thaJeztah** [comment]
Ah, I see (apologies; haven't really followed this project myself, only arrived here because of the linked issue); number of changes since March isn't huge; https://github.com/fsnotify/fsnotify/compare/v1.4.2...master

Let me look around as well if there's maintainers, or contributors in the Moby project that would be able to help out on this project

**Comment by nathany** [comment]
Thanks @thaJeztah.

Unfortunately I haven't gotten around to #201 to describe how releases have been done in the past.

**Comment by nathany** [comment]
Should we also suggest the use of dep for the next release? https://github.com/golang/dep

It may not change the actual release process beyond initial updates to the README.
