### ISSUE TITLE
allow use of handed-in/mock file system (for testing)

### ISSUE THREAD

**Issue by HJFinch** [fsnotify/fsnotify#231]
While developing a small project using fsnotify I stumbled about how to test this at best to keep up our coverage and ensure code quality.

We are now evaluating the use of https://github.com/spf13/afero for this, which would allow us to mock the filesystem just as we need it for testing.
The issue here is, that this requires some change in the main application code no stop using os and switch to wrapped calls.

Do you have any plans on doing this for fsnotify or would you be interested in doing this?

**Comment by omeid** [comment]
Why do you need to mock the filesystem? it is everywhere.

**Comment by HJFinch** [comment]
For testing without making modifications to a local fs?
To have a simple layer for file actions or temp-files that can easily be reset after the test is finished without tedious cleanup work.

Testing with the fs directly seams like a bad practice.

**Comment by omeid** [comment]
It is not bad practice. Test with a real filesystem. Mock only when you can't afford the real thing.

**Comment by bep** [comment]
I maintain Hugo which uses both fsnotify + afero, and while the file watching may be a black spot in our test coverage, any mocking in fsnotify would not help, at all. I have currently tested the logic by manually creating the different events, and that has worked fairly well. The hardest issues with fsnotify is subtle differences between OSes/file editors etc., and that would have to be handled on the lowest possible level anyway (in fsnotify).

**Comment by HJFinch** [comment]
Hm, then thanks for the feedback and for clearing this up.
We already saw, that full coverage is nothing worth spending too much time on, as it's not always practicable.
