### ISSUE TITLE
Generate artificial Init event to ease race free setup of new watches

### ISSUE THREAD

**Issue by ijc** [fsnotify/fsnotify#236]
Beginning to monitor a file/directory in a race free way is a bit tricky. For example you need to sample the initial state without missing events which occur between that initial sampling and starting to watch. The change I made in https://github.com/cri-o/ocicni/pull/13 (and the associated comment) are an example of this.

This could all be made simpler for callers if during `watcher.Add()` an artificial `Init` event was introduced into the event stream after the watch was added internally but before any events are generated for it. Then users could handle the first time initialisation from within the usual event stream which ought to usually be simpler than figuring out where/how to do it racelessly from outside.

So code which today has (hacked up/simplified derivation of the code in the PR I link above, which instead just keeps a "sum" of a given file in a global for some unknowable reason):
```go
var mu sync.Mutex
var sum string
[...]
func Init(... {
	dir := "/some/path"
	file := filepath.Join(dir, "i-am-interesting")

	watcher, err := fsnotify.NewWatcher()
        // if err != nil
	defer watcher.Close()

	go func() {
		for {
			select {
			case event := <-watcher.Events:
				if event.Op&fsnotify.Create != fsnotify.Create &&
					event.Op&fsnotify.Write != fsnotify.Write {
					continue
				}

				mu.Lock()
 				sum = do_sum_of(file)
				mu.Unlock()

			case err := <-watcher.Errors:
				// Oh no!
				return
			}
		}
	}()

	if err = watcher.Add(dir); err != nil {
		return err
	}

	// Now that `watcher` is running and watching the `dir`
	// gather the initial sum. It has to be done in this
	// order to avoid missing any updates which might otherwise
	// occur between gathering the initial configuration and
	// starting the watcher.
	//
	// This is races with the goroutine above which consumes
	// events, but the use of the lock avoids anything bad happening
	// (at worst we pointlessly calculate the sum a second time).
	mu.Lock()
 	sum = do_sum_of(file)
	mu.Unlock()
```
Becomes:
```go
var mu sync.Mutex
var sum string
[...]
func Init(... {
	dir := "/some/path"
	file := filepath.Join(dir, "i-am-interesting")

	watcher, err := fsnotify.NewWatcher()
        // if err != nil...
	defer watcher.Close()

	go func() {
		for {
			select {
			case event := <-watcher.Events:
				if event.Op&fsnotify.Create != fsnotify.Create &&
					event.Op&fsnotify.Write != fsnotify.Write && {
					event.Op&fsnotify.Init != fsnotify.Init && {
					continue
				}

				mu.Lock()
 				sum = do_sum_of(file)
				mu.Unlock()

			case err := <-watcher.Errors:
				// Oh no!
				return
			}
		}
	}()

	if err = watcher.Add(dir); err != nil {
		return err
	}
```
Where there is no need to handle the initial sum specially, it is handled by the normal event handling.

**Comment by nhooyr** [comment]
Unrelated but I wanted to let you know that your code has an error. You should check if the watcher.Events channel is closed by receiving from the channel into a second variable. Otherwise, that goroutine will may never exit. Usually it does though because of the second select clause, but still, its not guaranteed.

Will think about this.

**Comment by arp242** [comment]
I'm not sure that I understand why you can't do:

    sum := do_sum_of(file)

    watcher, err := fsnotify.NewWatcher()
    [ setup watcher, start goroutine, etc. ]

I read through your issue a few times, but it's still not entirely clear to me what problem exactly you're facing to be honest.

**Comment by ijc** [comment]
This is from some time ago and I haven't been involved in the related projects for several years so I've lost most of the context apart from what is written here.

But I think @arp242 your proposal has exactly the bug I was talking about: if the file is changed between the first `do_sum_of` and the call to `NewWatcher` then that change event will be lost, there will be no event until the file changes a second time.

**Comment by arp242** [comment]
> This is from some time ago and I haven't been involved in the related projects for several years so I've lost most of the context apart from what is written here.

Yeah, it was unmaintained/sporadically maintained for a few years; I've been going through all of the (old) issues in the last few weeks 

Anyway, I follow your problem now; the state of your `sum` variable may not accurately represent the actual sum of the file on disk. In many cases, I think that's probably not an issue, but in some cases it may be.

The way I'd fix it is with `sync.Once`; e.g. something like:

    var (
        firstSum sync.Once
        sum      string
    )
    go func() {
        for {
            select {
                case e := <-w.Events:
                    firstSum.Do(func() { sum = do_sum_of_file(file) })

                    if e.Has(fsnotify.Create) || e.Has(fsnotify.Create) {
                        sum = do_sum_of_file(file)
                    }
            }
        }
    }()

This is basically the same as the proposed `fsnotify.Init` event; only the first call to `firstSum.Do` will run, and subsequent calls will block while it's running.

I'll tag this as "documentation" and add an example for this at some point.

**Comment by arp242** [comment]
Actually, that's not identical as an INIT event, since it may never get triggered if there are no changes.

But I don't know what the actual real-world use case for this is. This is what I didn't (and still don't) really follow: why is it important to get the initial sum in the first place? I would not assign a value to `sum` at all on startup 🤔

Since there has been no demand outside of this for years, and since you don't recall the context either, I'll just close this for now; we can always revisit it later.
