### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Cosby86** [fsnotify/fsnotify#237]
Hello all,
I have a file, monitored by fsnotify, in used from another process and I have a leak of CPU (attached pprof diagram). What do you think about it?
![capture](https://user-images.githubusercontent.com/28059569/36551177-493072fc-17f7-11e8-9840-69d17eacf570.PNG)

**Comment by hwhe** [comment]
no idea

**Comment by paulquerna-okta** [comment]
fixed by https://github.com/fsnotify/fsnotify/pull/262 as well

**Comment by dmt0** [comment]
Would be great if this issue would get a bit of attention. `fsnotify` is pretty much unusable for me on Mac. Bump!
