### ISSUE TITLE
kqueue improvements

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#24]
What have I learned from experimenting with kqueue directly (primarily on OS X)? #23 

- [x] fsnotify doesn't watch for Extend, Link or Revoke events (tracked in #519 now).

- [x] fsnotify has a 100ms timeout on reads, but instead we may be able to just block until kqueue has events available (nil timespec). this could save a little CPU time when idle, see: https://github.com/howeyc/fsnotify/issues/58
  - closing the kq (on OS X) results in the read failing with _Kevent: interrupted system call_, so blocking in a goroutine shouldn't delay shutdown.

- [x] fsnotify could add multiple file descriptors at once (such as all files in a directory), which may be a little more efficient then adding each one individually.

- [x] investigated `Udata` which C programs sometimes use to point to the watched filename, but it's probably not worthwhile from Go (and NetBSD defines Udata differently than the other BSDs).

Other improvements are specific to fsnotify, such as less mutexes #13 and bug fixes #14.

**Comment by Platin21** [comment]
I always wondered how it deals with atomic writes as i cannot get it to fire again when such a write happens.

**Comment by arp242** [comment]
> fsnotify could add multiple file descriptors at once (such as all files in a directory), which may be a little more efficient then adding each one individually.

`Add()` + `Remove()` takes 10078ns on my slow VM inside my slow laptop, and I bet most of that is in file operations rather than the syscall:

    BenchmarkAddRemove-2      128599             10078 ns/op             848 B/op         13 allocs/op

Not really worth optimizing IMO.
