### ISSUE TITLE
Linux inotify poller wastes an OS thread

### ISSUE THREAD

**Issue by WGH-** [fsnotify/fsnotify#240]
Every `Watcher` instance does `unix.EpollWait` in a loop inside a goroutine. Since this is direct syscall, which circumvents Go runtime poller, it wastes entire OS thread. If you create `N` watchers, `N` OS threads will be doing nothing except waiting in `epoll_wait` syscall.

This can be theoretically fixed, because both inotify fd and even epoll fd are pollable.

There's even convenient method in `internal/poll` (https://golang.org/pkg/internal/poll/#FD.RawRead) which does what we want. However, internal packages are not acessible from third-party code.

I'm not sure it's even fixable in current Go. There're many related issues in the Go bug tracker which are not yet resolved (probably not a complete list): golang/go#15021 golang/go#24331 golang/go#22939

**Comment by WGH-** [comment]
It's already fixable in modern Go, by the way.

**Comment by horahoradev** [comment]
I'm working on this. I currently have a basic implementation, will see if I can improve it tomorrow.

**Comment by arp242** [comment]
Fixed with #434
