### ISSUE TITLE
Does not work in mips64el

### ISSUE THREAD

**Issue by NightTsarina** [fsnotify/fsnotify#241]
Hi,

In a very similar case to #130, I am seeing failures in Prometheus in mips64el due to fsnotify not getting any notifications.

```
=== RUN   TestEventStringWithValue
--- PASS: TestEventStringWithValue (0.00s)
=== RUN   TestEventOpStringWithValue
--- PASS: TestEventOpStringWithValue (0.00s)
=== RUN   TestEventOpStringWithNoValue
--- PASS: TestEventOpStringWithNoValue (0.00s)
=== RUN   TestWatcherClose
=== PAUSE TestWatcherClose
=== RUN   TestPollerWithBadFd
--- PASS: TestPollerWithBadFd (0.00s)
=== RUN   TestPollerWithData
--- FAIL: TestPollerWithData (0.00s)
	inotify_poller_test.go:86: expected poller to return true
=== RUN   TestPollerWithWakeup
--- PASS: TestPollerWithWakeup (0.00s)
=== RUN   TestPollerWithClose
--- FAIL: TestPollerWithClose (0.00s)
	inotify_poller_test.go:120: expected poller to return true
=== RUN   TestPollerWithWakeupAndData
--- FAIL: TestPollerWithWakeupAndData (0.00s)
	inotify_poller_test.go:141: expected poller to return true
=== RUN   TestPollerConcurrent
--- FAIL: TestPollerConcurrent (0.05s)
	inotify_poller_test.go:198: expected true
=== RUN   TestInotifyCloseRightAway
--- PASS: TestInotifyCloseRightAway (0.05s)
=== RUN   TestInotifyCloseSlightlyLater
--- PASS: TestInotifyCloseSlightlyLater (0.10s)
=== RUN   TestInotifyCloseSlightlyLaterWithWatch
--- PASS: TestInotifyCloseSlightlyLaterWithWatch (0.10s)
=== RUN   TestInotifyCloseAfterRead
--- PASS: TestInotifyCloseAfterRead (0.10s)
=== RUN   TestInotifyCloseCreate
--- FAIL: TestInotifyCloseCreate (0.05s)
	inotify_test.go:136: Took too long to wait for event
=== RUN   TestInotifyStress
--- FAIL: TestInotifyStress (0.26s)
	inotify_test.go:270: Expected at least 50 creates, got 0
=== RUN   TestInotifyRemoveTwice
--- PASS: TestInotifyRemoveTwice (0.00s)
=== RUN   TestInotifyInnerMapLength
(times out..)
```

Doing an strace of the prometheus test that is failing, I get the impression that the wrong filedescriptor is being used..

```
[25779] inotify_init1(IN_CLOEXEC)               = 3
[25779] inotify_add_watch(3, "fixtures", IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = 1

[25775] _newselect(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=80}) = 0 (Timeout)
```

I am running golang 1.10. 

Can you guys take a look? Thanks!

**Comment by xieyanker** [comment]
@TheTincho Do you have resolved this issue? I meet the same issue on mips64el, I build kubernetes on mips64el, but the `kubectl logs -f` not work, it uses fsnotify's watch method.

**Comment by TheTincho** [comment]
@xieyanker Hi!

Not from the Debian side. We have not updated the package since 1.4.7, so my workaround for mips64el is still in place. Looking at the commit history I see no changes either (or much other activity, sadly)

**Comment by xieyanker** [comment]
@TheTincho Thanks for your reply, in my opinion, your `debian/sid` branch cancel the test for fsnotify, but I wonder is there exist any question when you use the prometheus on mips64el?

**Comment by TheTincho** [comment]
I am not sure if anybody is actually using the debian package on that arch.. But in theory it should work, as files are checked once in a while based on a timeout (as far as I remember)

**Comment by nathany** [comment]
@TheTincho Thanks for the report.

I don't personally have access to any MIPS computers to debug this on.

Any idea if the file descriptor issue is in fsnotify or the underlying golang.org/x/sys/unix package?

**Comment by liupeng0518** [comment]
@nathany the `golang.org/x/sys/unix` problems, but the latest `golang.org/x/sys/unix` package is ok, work fine.

**Comment by arp242** [comment]
If I understand things correctly it should be solved now?

**Comment by arp242** [comment]
Closing due to lack of feedback and I think it should be fixed?
