### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by Nhoya** [fsnotify/fsnotify#245]
Is this project still maintained? I see multiple pull requests that are fixing game breaking bugs [like this one](https://github.com/fsnotify/fsnotify/pull/202) that are completely ignored.. I would like to contribute but if this project is not active anymore at least let the community fork it and maintain it..

I read a bit about this in #235 I don't think this is the correct way. You can easily ignore that event on certain platform. I like this project (and is the only one atm) so I would prefer something solid with a full coverage instead of something "multi platform" but that is only working partially

**Comment by bep** [comment]
>Is this project still maintained? 

I think this should be in the Go stdlib. 

I don't think that will happen, so the second option would be for some big Go shop to pick up the project. I have not seen any one person stepping up to the task.

**Comment by Nhoya** [comment]
Well @bep I saw multiple forks that were done because some useful PR were ignored so I think that is something the community can deal with. The problem is that we should receive an official response. I don't really get the point on ignoring PR and still leave the project open

**Comment by bep** [comment]
>I don't really get the point on ignoring PRs and still leave the project open

Which is kind of my main point of my post. Noone really "owns" this project, hence the neglection. And it is a core component in the Go communitny, and deserves better.

**Comment by nathany** [comment]
I’ve been handing out commit access and asking for someone to step up as project maintainer for years now.

https://github.com/fsnotify/fsnotify/issues/183#issuecomment-286456045

**Comment by gdey** [comment]
At Gophercon 2018 we got a few more people interested in helping maintain this project. Hopefully, this will allow up to catch up and improve this project. I have, also, set up a channel on the Gopher Slack to help coordinate development effort.
