### ISSUE TITLE
CI needs a fix

### ISSUE THREAD

**Issue by nhooyr** [fsnotify/fsnotify#246]
Something is wrong with CI, preventing any new PRs from being merged.

**Comment by nhooyr** [comment]
E.g. see https://github.com/fsnotify/fsnotify/pull/205

**Comment by gmccue** [comment]
@nhooyr it looks like an issue with `appveyor` building feature branches. My guess is there's something off with the CI config for this repo, or something that needs to be re-configured on the `appveyor` side. Someone with admin access would probably need to fix it, maybe @nathany?

**Comment by gmccue** [comment]
@nhooyr @nathany anything I can do to help here?

**Comment by nathany** [comment]
Apologies for the delay.

I've switched off AppVeyor rather than investigating the issue because Travis CI now supports Windows, so we can do all our CI builds in one place.
