### ISSUE TITLE
Rename problem

### ISSUE THREAD

**Issue by cimstu** [fsnotify/fsnotify#248]
Before reporting an issue, please ensure you are using the latest release of fsnotify.
Yes the latest!
### Which operating system (GOOS) and version are you using?
windows7-64

### Please describe the issue that occurred.
1.add watch to folder A
2.rename  folder A to folder B
3.add file "a.txt" to folder B 
"create event" is notified with file path: "A/a.txt"

**Comment by johngcn** [comment]
@cimstu I've encountered the same issue, did you resove it?

**Comment by johngcn** [comment]
@nathany @howeyc

**Comment by nathany** [comment]
See #26. Closing as duplicate.
