### ISSUE TITLE
Watcher quits listening after file has been changed once

### ISSUE THREAD

**Issue by PopperJuan** [fsnotify/fsnotify#254]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
Linux SLES11, latest

### Please describe the issue that occurred.
Following the example, After i open a file in Vim and modify it, it notifies me that the file has changed. However whenever i do it again, It does not notify me. I am trying to create an on going process that notifies me when the file is change without exiting out on me.
### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

    func ConfigWatcher(ConfigFileName string) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			event := <-watcher.Events
			log.Println("event:", event)
			log.Println("modified file:", event.Name)

		}
	}()

	err = watcher.Add(ConfigFileName)
	if err != nil {
		log.Fatal(err)
	}
	<-done
    }

    func main(){
    //Some functions...
    go utils.ConfigWatcher(config)
    //Functions here, this is a restful service that runs in the background. 
    }

I start my restful service, validate that its running
In Vim, I modify a configuration(modify, ESC, :wq), validate
     event: "/u/file.json": RENAME
     modified file: /u/file.json
     event: "/u/file.json": CHMOD
     modified file: /u/file.json
     event: "/u/file.json": REMOVE
     modified file: /u/file.json
After, i go on Vim and change back the configuration, however i don't receive anything back from my function.

**Comment by nhooyr** [comment]
can you try turning it into a standalone program without your rest service and seeing if that works?

**Comment by caibirdme** [comment]
same problem

**Comment by radu-munteanu** [comment]
It's normal behavior.

> fsnotify is based on the file system and OS features. For example, on GNU/Linux, inotify is taking the info from the inode of the file, and not the file name. If a file is deleted and it is created again, it may have a different inode.

Either watch the parent directory and check for the events that have your file or create a new watch when the file is overwritten.

Relates to #214, #255

**Comment by caibirdme** [comment]
Got it, that's why I edited the file by VIM and didn't receive the signal, vim use filename.swp

**Comment by gdey** [comment]
dup #17
