### ISSUE TITLE
Edit file but it trigger Rename Event

### ISSUE THREAD

**Issue by Tangocc** [fsnotify/fsnotify#255]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: lsb_release -a
macOS: sw_vers
Windows: systeminfo | findstr /B /C:OS

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

system: Mac OS
issue: when edit the watched file ( such as config.conf) with vi or vim , I wish it will trigger Write Event. But, actually, it will trigger Rename , and thus result to the original file invalid.

**Comment by radu-munteanu** [comment]
vim actually creates a temporary file, removes the existing file and replace it with the temp file when you save.

Non issue, can be closed.

**Comment by radu-munteanu** [comment]
Relates to #214, #254

**Comment by dylan-bourque** [comment]
Same issue as #17. Closing
