### ISSUE TITLE
panic: runtime error: slice bounds out of range while debugging with breakpoint

### ISSUE THREAD

**Issue by kausal-goibibo** [fsnotify/fsnotify#258]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

### Please describe the issue that occurred.
When debugging using Goland, my project is giving me the below error. However, I don't get the error when not using any breakpoint.

panic: runtime error: slice bounds out of range

goroutine 4 [running]:
github.com/fsnotify/fsnotify.read(0x8, 0xc42003ce88, 0xa, 0xa, 0x5525560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/apple/Projects/MyProject/vendor/src/github.com/fsnotify/fsnotify/kqueue.go:497 +0x1f7
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc420060060)
	/Users/apple/Projects/MyProject/vendor/src/github.com/fsnotify/fsnotify/kqueue.go:284 +0x1ef
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/apple/Projects/MyProject/vendor/src/github.com/fsnotify/fsnotify/kqueue.go:62 +0x436

Debugger finished with exit code 0

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.
Yes, I keep a breakpoint anywhere while initializing my modules inside main.go and this happens. Ot runs smoothly if I don't use any breakpoint.
Golang version 1.9.2
Goland version 2018.1.5
Importing fsnotify directly from github, so the latest version

**Comment by kausal-goibibo** [comment]
Can someone help here please?

**Comment by nhooyr** [comment]
See #212

**Comment by kausal-goibibo** [comment]
I saw that already, Is a fix for this available?

**Comment by nhooyr** [comment]
No, thats why that issue is open.
