### ISSUE TITLE
Renaming folder which already added to watch 

### ISSUE THREAD

**Issue by gohelraj1111** [fsnotify/fsnotify#259]
### Operating system and version.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

### Here is the description of the issue that occurred.

While creating new folder if I rename that folder to any custome name and than if I will create any files into that folder  at that time watcher try to find that files into old folder path which was created by system not on the given custome name

1) Output when I first create folder with custome name.
It adds both the folder path into watches
![creatrenamedir](https://user-images.githubusercontent.com/42057556/44095122-9f0edd5e-9ff5-11e8-9069-45f770a55fb2.PNG)
 
2) When I create any file into renamed folder it try to finds that file into old name folder.
![creatrenamedir2](https://user-images.githubusercontent.com/42057556/44095292-0f0782aa-9ff6-11e8-97f6-a27ebb100b08.PNG)

I also tried removing old directory path from watcher but it not removing it actually..!

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

1. Add a directory to watch
2. Create new folder in that directory by right clicking in windows explorer and give it name you like
3. When watcher fires create event then add newly created directory to watch

**Comment by arnegroskurth** [comment]
We are also experiencing this issue on Windows 10.

@dylan-bourque Any update on this?

**Comment by arnegroskurth** [comment]
Same issue: https://github.com/fsnotify/fsnotify/issues/243

**Comment by nathany** [comment]
Thanks for reporting the issue. Have you managed to find a workaround? Is it possible to detect the rename? Possibly to remove the old watch and set up a new watch when the rename happens?

If you find a work around, it would be great to get a failing test case and fix upstreamed into fsnotify.

Though word of warning, the fsnotify code for Windows could use some love. It was pulled from winfsnotify that initially mapped Windows to Linux inotify before being further wrapped in the fsnotify common interface.
