### ISSUE TITLE
MacOS CI-Tests failing

### ISSUE THREAD

**Issue by gfrey** [fsnotify/fsnotify#264]
### Which operating system (GOOS) and version are you using?

```bash
#  sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
```

```bash
# go version
go version go1.10.3 darwin/amd64
```

### Please describe the issue that occurred.

During CI-Build for pr #263 the tests on MacOS failed with a RaceCondition. I tried to reproduce locally and reran the tests around a dozen times and noticed two things:

* `TestExchangedataInWatchedDir` and `TestExchangedataInWatchedFile` fail entirely on my machine ("integration_darwin_test.go:92: [1] exchangedata failed: operation not supported").
* `TestFsnotifyDeleteWatchedDir` has flakes. It worked like 75% of the times in my tests. This is also the test that failed in the CI build.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

I just ran `go test -v --race ./...` and the first issue shows all the time, the second only every now and then.

**Comment by nathany** [comment]
It is failing on 10.13+:

> A exchangedata() function call appeared in Darwin 1.3.1 (Mac OS X version 10.0).  It was deprecated in macOS 10.13. https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/exchangedata.2.html

The call to `func Exchangedata(path1 string, path2 string, options int) (err error)` from x/sys/unix.

**Comment by bep** [comment]
I added that test etc. which was a way to support Sublime Text 3 in Hugo.

**Comment by nathany** [comment]
Working on a skip test now.

**Comment by nathany** [comment]
@bep #267 does a skip of the test for now, though perhaps there is another way to write this test that doesn't depend on Exchangedata?

**Comment by arp242** [comment]
> does a skip of the test for now, though perhaps there is another way to write this test that doesn't depend on Exchangedata?

This test specifically tests Exchangedata, so if that's not available then I don't think there's anything to test?
