### ISSUE TITLE
Ensure watchers are cleaned up when directories or files are removed

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#268]
Some operating systems may clean up for us, others may not.
Removing the watch explicitly could return an error.

IMO, the behaviour we want is to clean up in the library if the OS doesn't, so that the caller doesn't need to worry about cleaning up watchers for removed folders or files.

Brought up in #223 
On Windows #208

**Comment by Jacalz** [comment]
Any news on this? Would be great seeing this as we are currently running in to this error in [fyne-io/fyne](https://github.com/fyne-io/fyne/pull/758).
