### ISSUE TITLE
Permission denied when try to watch for dir with one of files which have `--wx------` permissions

### ISSUE THREAD

**Issue by achernetsky** [fsnotify/fsnotify#270]
Hello,

I am sorry, I don't know this is a bug or something.

### Which operating system (GOOS) and version are you using?
```
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```
###  Steps to reproduce

1. `cd /tmp && mkdir fsnotify_permission_denied`
1. `cd fsnotify_permission_denied`
1. `touch test1.log test2.log`
1. `chmod 0300 test2.log`
1. `go run main.go`

```go
// main.go

package main

import (
	"log"

	"github.com/fsnotify/fsnotify"
)

func ExampleNewWatcher() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	err = watcher.Add("/tmp/fsnotify_permission_denied")
	if err != nil {
		log.Fatal("fatal: ", err)
	}
}

func main() {
	ExampleNewWatcher()
}
```
As result
```bash
$ go run main.go
2018/10/02 16:21:08 fatal: permission denied
exit status 1
```

Why is it try open file with `0700` permissions?https://github.com/fsnotify/fsnotify/blob/c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9/kqueue.go#L218

Thank you.

**Comment by arp242** [comment]
kqueue requires opening a file descriptor for every file (unlike Linux, you can't open a file descriptor for just the directory). If the file doesn't have read permissions, you can't open a file descriptor.

The 0700 here is basically meaningless AFAIK; it's only used when creating files, but we never do that.

I'm not sure what behaviour makes sense; we could skip the file, but that may be surprising (and is also inconsistent with how inotify behaves). I think that simply returning an error is probably the best behaviour, although the error could be clearer.
