### ISSUE TITLE
Spurious symlink CREATE events on macOS when watching a directory

### ISSUE THREAD

**Issue by creachadair** [fsnotify/fsnotify#277]
### Please describe the issue that occurred.

While watching a directory that contains symbolic links, creating, deleting, or renaming a file or directory inside the watched directory generates spurious CREATE events for all of the symlinks.

Version info:
```
$ grep fsnotify go.sum 
github.com/fsnotify/fsnotify v1.4.7 h1:IXs+QLmnXW2CcXuY+8Mzv/fWEsPGWxqefPtCP5CnV9I=
github.com/fsnotify/fsnotify v1.4.7/go.mod h1:jwhsz4b93w/PPRr/qN1Yymfu8t87LnFCMoQvtojpjFo=
```

### Which operating system (GOOS) and version are you using?

```
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.14.2
BuildVersion:   18C54

$ go version
go version go1.11.4 darwin/amd64
```

### Repro Instructions

Setup:

```
$ mkdir repro; cd repro; go mod init repro
$ goimports > watchme.go <<EOF
package main

import (
 "flag"
 "log"

 "github.com/fsnotify/fsnotify"
)

func main() {
 flag.Parse()
 if flag.NArg() != 1 {
  log.Fatal("Usage: watchme <path>")
 }

 w, err := fsnotify.NewWatcher()
 if err != nil {
  log.Fatal("New: ", err)
 }
 defer w.Close()

 if err := w.Add(flag.Arg(0)); err != nil {
  log.Fatalf("Add %q: %v", flag.Arg(0), err)
 }

 for {
  select {
  case evt, ok := <-w.Events:
   if !ok {
    return
   }
   log.Printf("EVENT: %v", evt)

  case err, ok := <-w.Errors:
   if !ok {
    return
   }

   log.Printf("ERROR: %v", err)
  }
 }
}
EOF
$ ln -s go.mod a; ln -s go.sum b
$ go run . .
```

In another terminal:

```
$ cd repro
$ touch foo
$ rm foo
$ mkdir apple
$ mv apple pear
$ rmdir pear
```

Expected (modulo log timestamps):

```
2018/12/31 15:38:21 EVENT: "foo": CREATE
2018/12/31 15:38:21 EVENT: "foo": REMOVE
2018/12/31 15:38:21 EVENT: "apple": CREATE
2018/12/31 15:38:21 EVENT: "pear": CREATE
2018/12/31 15:38:21 EVENT: "apple": REMOVE|RENAME
2018/12/31 15:38:21 EVENT: "pear": REMOVE
```

Observed (modulo log timestamps):

```
2018/12/31 15:39:05 EVENT: "a": CREATE
2018/12/31 15:39:05 EVENT: "b": CREATE
2018/12/31 15:39:05 EVENT: "foo": CREATE
2018/12/31 15:39:05 EVENT: "foo": REMOVE
2018/12/31 15:39:05 EVENT: "a": CREATE
2018/12/31 15:39:05 EVENT: "b": CREATE
2018/12/31 15:39:05 EVENT: "a": CREATE
2018/12/31 15:39:05 EVENT: "apple": CREATE
2018/12/31 15:39:05 EVENT: "b": CREATE
2018/12/31 15:39:05 EVENT: "a": CREATE
2018/12/31 15:39:05 EVENT: "b": CREATE
2018/12/31 15:39:05 EVENT: "pear": CREATE
2018/12/31 15:39:05 EVENT: "apple": REMOVE|RENAME
2018/12/31 15:39:05 EVENT: "pear": REMOVE
2018/12/31 15:39:05 EVENT: "a": CREATE
2018/12/31 15:39:05 EVENT: "b": CREATE
```

It's worth noting that the events for the test probes are correct, it's just that they're stippled with incorrect spam from the symlinks.

**Comment by creachadair** [comment]
> I think the simplest possible fix would involve making `sendDirectoryChangeEvents` repeat the link expansion that is done when the paths are registered, but it's possible there is a better solution.

Upon reflection, I think that's not the right solution. The core issue is (I believe) that `pathInfo` is overloaded: At the time of registration it captures the resolvent path for a file whose descriptor was registered with kqueue, but at the time of update it is being used to verify the presence of entries in the directory. It can't do both in the presence of symlinks.

Another possible solution would be to extend `pathInfo` with some additional data: For example, it could be given a `link string` field which is set to nonempty when the path denotes the target of a link. This is known at the point of registration, and would not interfere with the other existing uses of the struct.

**Comment by creachadair** [comment]
The above is again partly wrong: It's not the path in `pathInfo` that matters, but what is entered in the `fileExists` map. That may be easier to fix: At kqueue.go:405 it is set to the resolvent path, but should be set to the _origin_ path (I believe). It constructs the spelling location at line 398 but then replaces it (`w.internalWatch` → `w.addWatch` → `filepath.EvalSymlinks`).

**Comment by creachadair** [comment]
I'm coming around to the view that it may be a mistake to use the same logic for symlinks that are explicitly registered, as those appearing inside a directory watch:

* When watching a directory, what I care about is that the link itself is created, deleted, renamed.
* When watching a link, what I care about is that the _target_ of the link is created, deleted, renamed.

Right now the library re-uses the explicit registration path for both cases. I think if it handled links in the `watchDirectoryFiles` arm as links _qua_ links, rather than resolving them, it would be better. That's a bigger change, so it'll take me a while to test whether it (a) works, and (b) helps.

**Comment by arp242** [comment]
Added a failing test case `TestWatchSymlink/277` for this in #522 (currently skipped), which is essentially your repro case in test form. It fails on all kqueue platforms.

The whole symlink behaviour on kqueue platforms is less than ideal right now; partly because people depend on the current (inconsistent) behaviour so we can't "just" change it; it was changed before and ended up being reverted. Need to carefully look at it (also: #227).
