### ISSUE TITLE
Problems when rewatching removed directories

### ISSUE THREAD

**Issue by mauricioabreu** [fsnotify/fsnotify#279]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: CentOS 6.8

### Please describe the issue that occurred.

- Started a watcher on a path like `/myuser` (recursively) it notifies events for anything create inside it.
- Events are notified for any existent path on `/myuser` (I add them recursively using `walk` approach)
- Created new directory on `/myuser` named `foo`
- Create a file named `bar.txt` on `foo`
- Removed directory `foo`
- Create directory `foo`
- Now `foo` does not receive events, neither `

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

Commands on a docker I created:

```
➜  ~ docker exec -it 060865152c1c touch /go/bin/a.txt
➜  ~ docker exec -it 060865152c1c mkdir /go/foo
➜  ~ docker exec -it 060865152c1c touch /go/foo/a.txt
➜  ~ docker exec -it 060865152c1c rm -f /go/foo
➜  ~ docker exec -it 060865152c1c rm -r /go/foo
➜  ~ docker exec -it 060865152c1c mkdir /go/foo
➜  ~ docker exec -it 060865152c1c touch /go/foo/a.txt
➜  ~ docker exec -it 060865152c1c touch /go/foo/a.txt
➜  ~ docker exec -it 060865152c1c touch /go/bin/a.txt
```

Output from my program:

```
INFO[0010] [handlers/watcher] Waiting for events...
INFO[0115] Received event /go/bin/a.txt CREATE
INFO[0115] [handlers/watcher] Found new `create/close write` event /go/bin/a.txt
INFO[0115] Received event /go/bin/a.txt CHMOD
/go/bin/a.txt
INFO[0115] Received event /go/bin/a.txt CLOSE_WRITE
INFO[0115] [handlers/watcher] Found new `create/close write` event /go/bin/a.txt
/go/bin/a.txt
INFO[0123] Received event /go/foo CREATE
INFO[0123] [handlers/watcher] Found new `create/close write` event /go/foo
INFO[0132] Received event /go/foo/a.txt CREATE
INFO[0132] [handlers/watcher] Found new `create/close write` event /go/foo/a.txt
/go/foo/a.txt
INFO[0132] Received event /go/foo/a.txt CHMOD
INFO[0132] Received event /go/foo/a.txt CHMOD
INFO[0132] Received event /go/foo/a.txt CLOSE_WRITE
INFO[0132] [handlers/watcher] Found new `create/close write` event /go/foo/a.txt
INFO[0132] Received event /go/foo/a.txt CLOSE_WRITE
/go/foo/a.txt
INFO[0132] [handlers/watcher] Found new `create/close write` event /go/foo/a.txt
/go/foo/a.txt
```

**Comment by mauricioabreu** [comment]
One thing that solves my problems is calling `Add` everytime a `Create` happens, and `Remove` everytime a `Remove` happens. Is it ok?

**Comment by radu-munteanu** [comment]
This is normal behaviour, already discussed.

> It's not as easy as it seems. fsnotify is based on the file system and OS features. For example, on GNU/Linux, inotify is taking the info from the inode of the file, and not the file name. If a file is deleted and it is created again, it may have a different inode.

Relates to #17, #214, #254, #255

**Comment by mauricioabreu** [comment]
@radu-munteanu thanks for the answer. About inotify and inode, ok, I got it and I knew it before opening this issue.
I made some tests using `inotify-tools` and now I am curious on how `inotify-tools` can keep track of deleted directories.

**Comment by radu-munteanu** [comment]
Perhaps they open watches on all the parents of the given directory.

**Comment by mauricioabreu** [comment]
I solved it by adding any creation of new dir to the watcher.
`watcher.Add(event.Name)`

Also, I removed the code where I `remove` watchers because `fsnotify` does it internally.
