### ISSUE TITLE
Why not support IN_ACCESS events?

### ISSUE THREAD

**Issue by wcc526** [fsnotify/fsnotify#295]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: lsb_release -a

### Please describe the issue that occurred.

/* Supported events suitable for MASK parameter of INOTIFY_ADD_WATCH.  */
#define IN_ACCESS         0x00000001        /* File was accessed.  */
#define IN_MODIFY         0x00000002        /* File was modified.  */
#define IN_ATTRIB         0x00000004        /* Metadata changed.  */
#define IN_CLOSE_WRITE         0x00000008        /* Writtable file was closed.  */
#define IN_CLOSE_NOWRITE 0x00000010        /* Unwrittable file closed.  */
#define IN_CLOSE         (IN_CLOSE_WRITE | IN_CLOSE_NOWRITE) /* Close.  */
#define IN_OPEN                 0x00000020        /* File was opened.  */
#define IN_MOVED_FROM         0x00000040        /* File was moved from X.  */
#define IN_MOVED_TO      0x00000080        /* File was moved to Y.  */
#define IN_MOVE                 (IN_MOVED_FROM | IN_MOVED_TO) /* Moves.  */
#define IN_CREATE         0x00000100        /* Subfile was created.  */
#define IN_DELETE         0x00000200        /* Subfile was deleted.  */
#define IN_DELETE_SELF         0x00000400        /* Self was deleted.  */
#define IN_MOVE_SELF         0x00000800        /* Self was moved.  */

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

https://sites.uclouvain.be/SystInfo/usr/include/sys/inotify.h.html

https://github.com/fsnotify/fsnotify/blob/85de84ff31f8451e102be43b4efeed7b99ae89a0/fsnotify.go

Only Write DELETE and so on,there is not ACCESS to support file open?

**Comment by nathany** [comment]
The trouble is adding event types that are only supported on a single platform. Please see #22.

One solution may be to split out individual libraries that can support additional events, even if fsnotify only supports the minimum common denominator. See #75.
