### ISSUE TITLE
Can't get USB device unmount event

### ISSUE THREAD

**Issue by pathing** [fsnotify/fsnotify#297]
If watching a directory in a USB storage, it can't get USB device unmount event when the USB device is pull out

**Comment by nathany** [comment]
Yeah, I think it's a separate event (on some, maybe all platforms) that fsnotify doesn't currently support.

**Comment by arp242** [comment]
I created a new issue to track adding additional events: #519 Bit easier to have one issue instead of a bunch for every possible event.
