### ISSUE TITLE
Client receives all previous sent events from server when restarting client. Is it correct behavior?

### ISSUE THREAD

**Issue by Muddz** [fsnotify/fsnotify#301]
I have Server program which sends events via SSE to the Client program.

Suppose that the Server program has sent 4 events and the Client program successfully received all 4 events, but when restarting the Client program it gets all the previous 4 events at once again even though the Server didn't send anything.

Is this a behavior that should exist or maybe defined in the SSE specifications? I find it odd

**Comment by AnberChian** [comment]
I encoutered the same problem and seems that it is more offen if the program is not stop correctly.

**Comment by Muddz** [comment]
@AnberChian When you say "program" are you referring to the Client program or Server program?

and how do you stop it incorrectly and correctly. I would like to test your suggestion

**Comment by Muddz** [comment]
Sorry! This is a big fail from my side. This issue was supposed to be created for another repository!
