### ISSUE TITLE
fsnotify lost fs events and comes up with an error event on Windows 7

### ISSUE THREAD

**Issue by AbnerChian** [fsnotify/fsnotify#302]
My program watches a directory and the sub directories at the same time with fsnotify. I moved a folder with many files and sub folders to the directory, no file system events reveived and the watcher came up with an error event.

**Comment by nathany** [comment]
What error event did you receive? Can you provide a minimal example to demonstrate the issue?

**Comment by arp242** [comment]
I'm closing this due to lack of feedback; feel free to add more information and it can be reopened.
