### ISSUE TITLE
How do I properly pause and resume fsnotify?

### ISSUE THREAD

**Issue by Muddz** [fsnotify/fsnotify#303]
I have the following case where I want to pause `fsnotify` from watching a file and then resume it. 
The code below here should do what I want, but its seems like a  call to `fileWatcher.Remove()` is blocking the thread to be able to continune its work. I also tried `go pauseFileWatcher()` which didn't stop `fsnotify` from watching the file

```
func saveFile(content string) {
	pauseFileWatcher()
	b := bytes.NewBufferString(content).Bytes()
	if err := ioutil.WriteFile(path, b, 0644); err != nil {
		log.Println("Error: Couldn't save file", err)
		return
	}
	resumeFileWatcher()
}

func pauseFileWatcher() {
	if err := fileWatcher.Remove(desktopFilePath); err != nil {
		log.Println("ERROR: Couldn't pause FileWatcher:", err)
	}
}

func resumeFileWatcher() {
	if err := fileWatcher.Add(desktopFilePath); err != nil {
		log.Println("ERROR: Couldn't resume FileWatcher:", err)
	}
}
```

**Comment by nathany** [comment]
I'm not sure why your example doesn't work.

Please provide more detail, such as which operating system you are using.

I suppose the other alternative is to leave it running but swallow the event when a "paused" flag is set, but really it would be good if this worked.

**Comment by Muddz** [comment]
OS: Windows 10
Go version: Go 1.12.9

I will upload a simple demo project trying it out in a isolated case. But yes the logic should let fnotify to stop and resume again.

**Comment by nathany** [comment]
Thanks. Yes, an isolated demo project or a failing test case would help as the next step.

**Comment by Muddz** [comment]
I solved it.

What I did wrong:

```
var globalWatcher fsnotify.Watcher //Wrong
var globalWatcher *fsnotify.Watcher //Correct

func main() {
startFileWatcher() 
...
}

func startFileWatcher() {
	watcher, err := fsnotify.NewWatcher()
	globalWatcher = watcher //Remember to assign the global variable
....
...
..
}

func pauseFileWatcher() {
	if err := globalWatcher .Remove(desktopFilePath); err != nil {
		log.Println("ERROR: Couldn't pause FileWatcher:", err)
	}
}

func resumeFileWatcher() {
	if err := globalWatcher .Add(desktopFilePath); err != nil {
		log.Println("ERROR: Couldn't resume FileWatcher:", err)
	}
}
```
