### ISSUE TITLE
Fsnotify's listener fires 2x times when ioutil.WriteFile() is called. WITH DEMO PROJECT

### ISSUE THREAD

**Issue by Muddz** [fsnotify/fsnotify#304]
I have a case where I has to write to a file I'm already watching from code with` ioutil.WriteFile()`. But when that happends, Fsnotify fires its listener 2x times. 

I have provided a very simple demo project with logs demonstrating the problem https://github.com/Muddz/Fsnotify_bug

Windows 10
Go 1.12.9

**Comment by Muddz** [comment]
@grvlle So in the code is `O_TRUNC` clearing the entire content of the file and then writing the new content into the file?

**Comment by grvlle** [comment]
That's correct!

https://golang.org/src/io/ioutil/ioutil.go?s=2534:2602#L69

**Comment by Muddz** [comment]
@grvlle Shouldn't `fsnotify` only registrer a file-change when the file has been saved?
Forexample when I open the file in notepad, edits something in it and save it, only then will `fsnotify` see it as a change and only 1 change and not two changes as `ioutil.WriteFile()` do

**Comment by nathany** [comment]
Thanks @grvlle.

@Muddz Saving is just another way of writing a file. There is no distinction between the two as far as I know.

Do you think we should document this behaviour?

**Comment by Muddz** [comment]
@nathany No I just wondered why truncation and writing was registered as two events. Its because when I open a .txt file in notepad and edits something in it and then saves it, only then and once is fsnotify triggered about a filechange. i.e 1 file changes. That was my confusion
