### ISSUE TITLE
Content of WRITE event?

### ISSUE THREAD

**Issue by emailtovamos** [fsnotify/fsnotify#305]
### Which operating system (GOOS) and version are you using?

macOS: High Sierra

### Problem
How to get the content of a WRITE event if something gets written in a file? I want to know what exactly was written in case of WRITE event and if possible, what was deleted in case of delete event which also happens to be named WRITE

**Comment by nathany** [comment]
Sorry, that's not possible with the underlying notification events.

You will need to open the changed file and inspect it with your own code to determine the difference.
