### ISSUE TITLE
Change Events and Errors from attributes to functions

### ISSUE THREAD

**Issue by sidh** [fsnotify/fsnotify#307]
Events and Errors channels are exposed as struct attributes instead of functions returning those channels. This prohibits creation of a simple Watcher interface which in turn makes it harder to mock Watcher.

**Comment by nathany** [comment]
Yeah. I agree that exposing the channels directly isn't the best.

I don't think we want to making breaking changes to the API right now though, so for now you're probably best off wrapping fsnotify with your own functions.
