### ISSUE TITLE
undefined: unix.InotifyInit

### ISSUE THREAD

**Issue by fcddk** [fsnotify/fsnotify#320]
vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:39:15: undefined: unix.InotifyInit

env:
Linux master1 3.10.0-862.9.1.ns7_4.37.mips64el.debug #1 SMP PREEMPT Tue Feb 26 19:47:08 CST 2019 mips64el mips64el mips64el GNU/Linux

**Comment by arp242** [comment]
The reference was changed from `unix.InotifyInit` to `unix.InotifyInit1` in 2016, so it seems you're using a pretty old version of this library, possibly with an outdated x/sys/unix package.

I'll close this for now; we can reopen if you can reproduce it with a more recent version.
