### ISSUE TITLE
exception about ‘short read in readEvents()’

### ISSUE THREAD

**Issue by adelina2kx** [fsnotify/fsnotify#327]
OS Type:Windows Server 2016

I had a problem when using SELECT to monitor 'Watcher.Events'. If the logical processing took too long, a panic showed up in 'Watcher.Events'【‘short read in readEvents()’】 and many events were missed. My current solution to bypass this problem is 【Put tasks in a queue by use golang's chan ,  and Let a thread handle it, so that can Increase the throughput of SELECT listening】. However I wonder if there is better solution to this?

抱歉，我的英文说的不好，上面那段话是找人帮忙写的，不知道他翻译的对不对。我再留一段中文版本的↓↓↓
我遇到一个问题，当我使用SELECT监听'Watcher.Events'时，如果逻辑处理耗时太长，将会收到一个异常‘short read in readEvents()’，并且会有一部分事件被抛弃，虽然我不知道这个异常是因为什么而产生的，但是经过我自己的研究，发现只要缩短SELECT里的逻辑耗时，就不会遇到这个问题。

**Comment by mauricioharley** [comment]
Facing the same issue with Windows 10.  Could you please share your code in English, @adelina2kx?
