### ISSUE TITLE
proposal: new interface

### ISSUE THREAD

**Issue by andrzejd-pl** [fsnotify/fsnotify#342]
Hi,

I want to propose creating an interface (e.g. `Watchdog`) which could be implemented by `Watcher` structure. This interface could look that
```go
type Watchdog interface {
    io.Closer
    Add(string) error
    Remove(string) error
    Errors() chan error
    Events() chan Event
}
```
It helps to create code with dependency injection and helps to test code using this package.

Advantages:
- testable code
- can use dependency injection
- keeps open-close principle (from SOLID)

Disadvantages:
- have to write 2 extra function that returns fields `Events` and `Errors`

**Comment by arp242** [comment]
We can't change this in a compatible way, and personally I think there isn't much value "mocking" a library like this in the first place. What *would* be valuable is providing an alternative filesystem with fs.FS, but that's a different thing. I'll have to look if adding fs.FS support can be done in a compatible way.

In a potential future v2 the Events and Errors fields should be changed to fields, yeah, but I'd like to avoid creating an incompatible v2 release if at all possible, and for the time being solving bugs people are encountering has higher priority.

At any rate, I don't think there's much value in keeping an issue for this so I'll close this for now.
