### ISSUE TITLE
multiple write event on single write

### ISSUE THREAD

**Issue by coanor** [fsnotify/fsnotify#344]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

```
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

### Please describe the issue that occurred.

To shield the editor factor, following code write some string to sepcified file:

``` golang
package main

 import (
   "flag"
   "io/ioutil"
   "log"
   "os"
 )

 var (
   fFile = flag.String("file", "", "file path")
   fData = flag.String("data", "", "data to write")
 )

 func main() {
   flag.Parse()

   if err := ioutil.WriteFile(*fFile, []byte(*fData), os.ModePerm); err != nil {
     log.Fatal(err)
   }
 }
```

following fsnoitfy loop will throw multiple write event (**BUT sometimes only one!!!**), this confused me.

``` golang
for {
       select {
       case event, ok := <-watcher.Events:
         if !ok {
           return
         }

         log.Println("event:", event)
         if event.Op&fsnotify.Write == fsnotify.Write {
           log.Println("modified file:", event.Name)
         } 
       case err, ok := <-watcher.Errors:
         if !ok {
           return
         }
         log.Println("error:", err)
       }
     }
```

with two write event comming:

```
2020/08/14 09:41:25 fsnotify.go:26: event: "/home/tan/go/src/demo/tmp/abc": WRITE
2020/08/14 09:41:25 fsnotify.go:29: modified file: /home/tan/go/src/demo/tmp/abc
2020/08/14 09:41:25 fsnotify.go:26: event: "/home/tan/go/src/demo/tmp/abc": WRITE
2020/08/14 09:41:25 fsnotify.go:29: modified file: /home/tan/go/src/demo/tmp/abc
```

**Comment by christoth** [comment]
multiple events being fired for a single write is also occurring for me on windows 10

**Comment by dominikbraun** [comment]
Confirming this bug in Windows 10 Pro 1909.

**Comment by benoitTK** [comment]
After reading inotify documentation on linux, (https://man7.org/linux/man-pages/man7/inotify.7.html)

           write(fd, buf, count);
                  Generates IN_MODIFY events for both dir and dir/myfile.

So depending on the size of the data, a write from go you may need multiple write system calls, generating multiple events in fsnotify.
A potential solution would be to track IN_CLOSE_WRITE to determine when the file is closed

**Comment by dominikbraun** [comment]
For those who really need that functionality: `radovskyb/watcher` works just fine for me.

**Comment by arp242** [comment]
Using this to write `/tmp/xxx/file`:

	func main() {
		err := os.WriteFile("/tmp/xxx/file", []byte("hello"), os.ModePerm)
		fmt.Println(err)
	}

I get the following in the latest main branch with the `./cmd/fsnotify` command:

	[~cg/fsnotify](main)% go run ./cmd/fsnotify /tmp/xxx/
	14:76:58.5449 watching; press ^C to exit

	[ run write ]
	14:76:01.9961   1 CREATE                "/tmp/xxx/file"
	14:76:01.9962   2 WRITE      (modified) "/tmp/xxx/file"

	[ run write again ]
	14:76:11.9698   3 WRITE      (modified) "/tmp/xxx/file"
	14:76:11.9699   4 WRITE      (modified) "/tmp/xxx/file"

However, with the following I get only one WRITE:

	func main() {
		fp, err := os.OpenFile("/tmp/xxx/file", os.O_WRONLY|os.O_APPEND, os.ModePerm)
		if err != nil {
			panic(err)
		}
		_, err = fp.Write([]byte("asd"))
		if err != nil {
			panic(err)
		}
		err = fp.Close()
		if err != nil {
			panic(err)
		}
	}

The issue is that `os.WriteFile()` contains:

	f, err := OpenFile(name, O_WRONLY|O_CREATE|O_TRUNC, perm)

`O_TRUNC` will truncate the file, so that's the first write, and the second write is the `Write()` call; you can verify with:

	func main() {
		fp, err := os.OpenFile("/tmp/xxx/file", os.O_WRONLY|os.O_TRUNC, os.ModePerm)
		if err != nil {
			panic(err)
		}
		err = fp.Close()
		if err != nil {
			panic(err)
		}
	}

Which doesn't contain any Write() calls, but still triggers a WRITE event due to the O_TRUNC.

---

I think this is behaving as expected: there really *are* two writes here to be reported. You can open a file with O_TRUNC and never write to it, or write to it in an hour later.
