### ISSUE TITLE
Support passing a file descriptor to Add()

### ISSUE THREAD

**Issue by cannon73** [fsnotify/fsnotify#345]
I have some doubts about the fs-notify software. There is no way to pass in a file descriptor that was opened before. Would that not be a problem for writing secure software that drops capabilities? Kindly add a constructor that allows caller to pass file descriptor.

**Comment by arp242** [comment]
#352 should be done first, as many people don't care about read events. Also need to look in to cross-platform support.

**Comment by arp242** [comment]
I had a bit of a think about this, and I don't think I'll add this. Many platforms don't actually accept a file descriptor; only kqueue and Windows do, and the types/methods for that are different (Windows requires a "handle", not an os.Open() descriptor).

So adding it in a cross-platform way is hard, or even impossible, and there doesn't seem to be a huge demand for it as no one seems to have asked aside from this issue.
