### ISSUE TITLE
Error: reference to undefined identifier 'syscall.SizeofInotifyEvent'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [fsnotify/fsnotify#348]
Hi.
I can't build your package.

Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
Ubuntu 20.04.1 x86_64

> github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:161:18: error: reference to undefined identifier 'syscall.SizeofInotifyEvent'
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:206:18: error: reference to undefined identifier 'syscall.SizeofInotifyEvent'
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:229:34: error: reference to undefined identifier 'syscall.SizeofInotifyEvent'
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:231:21: error: reference to undefined identifier 'syscall.InotifyEvent'
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:244:74: error: reference to undefined identifier 'syscall.SizeofInotifyEvent'
> ../go/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go:261:22: error: reference to undefined identifier 'syscall.SizeofInotifyEvent'
> 

I am using 

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

and my environment is described below:

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build499307086=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

You can reproduce this yourself by taking my "release" build of [gollvm](https://go.googlesource.com/gollvm/) [out here](https://drive.google.com/file/d/1goBZhc2st89x4LswJivTFOpIbydJUi50/view?usp=sharing)

**Comment by arp242** [comment]
I'm not sure which version of this package you're using, but it seems pretty old. 

References to `syscall.SizeofInotifyEvent` were replaced with `golang.org/x/sys/unix.SizeofInotifyEvent` in 2016: 30411db

So I think you're just using quite an old version.

**Comment by arp242** [comment]
That hpcloud/tail repo hasn't been maintained in years btw; seems like https://github.com/nxadm/tail is a maintained fork.
