### ISSUE TITLE
Can't determine REMOVE event correctly on MacOS

### ISSUE THREAD

**Issue by JerryngtonD** [fsnotify/fsnotify#365]
fsnotify v1.4.9

MacOS BigSur 11.0.1

ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B50

How can I detect that file on MacOS have been deleted. I can't determine it, because i get only Chmod(16) event and nothing fsnotify.Remove happened ? It works now only for windows OS.

It looks like something like this: 

`
func syncState(event fsnotify.Event, pathFrom string, pathTo string) {
	if event.Op == fsnotify.Create {
		go copyFile(pathFrom, pathTo)
	} else if event.Op == fsnotify.Remove {
		go deleteFile(pathTo)
	}
}
`

**Comment by marklr** [comment]
Hi,

You'll need to 'AND' the Op with the desired flag to check equality - the following code should work correctly:

`if event.Op&fsnotify.Remove == fsnotify.Remove { go deleteFile(pathTo); }`
