### ISSUE TITLE
There is a race in inotify.go:watcher.Close()

### ISSUE THREAD

**Issue by zeripath** [fsnotify/fsnotify#367]
Hi!

Thanks a lot for this library.

Looking at the code I'm suspicious that there is a race in Close():

https://github.com/fsnotify/fsnotify/blob/7f4cf4dd2b522a984eaca51d1ccee54101d3414a/inotify.go#L72-L80

Is it possible that two concurrent goroutines running Close() could both pass the check function `w.isClosed()` and then both call `close(w.done)`? That would result in two closes of the channel and a panic. 

One solution would be to lock the `w.mu` at least around the `w.IsClosed` and `close(w.done)` calls.

**Comment by nathany** [comment]
🤔  Good question. `isClosed()` uses a channel function, which has an implied lock, but maybe it could still be an issue?

Writing a test case for this situation might prove challenging though. Hmm.
