### ISSUE TITLE
Travis-ci.org has been shut down

### ISSUE THREAD

**Issue by shogo82148** [fsnotify/fsnotify#373]
Two months ago, Travis CI announced the org domain will shut down.

- https://blog.travis-ci.com/2021-05-07-orgshutdown

> Here’s the TL;DR version:
> - Travis-ci.org shut down will occur on May 31, 2021
> - This change is to ensure product updates and fixes can be implemented for all users, at the same time
> - All your repositories on travis-ci.org should be migrated to travis-ci.com before May 31, 2021 to avoid builds not running
> - All repositories – private, and public – will continue to build as expected on travis-ci.com once migrated
> - Your historic build data on travis-ci.org will remain available in a read-only state for an indefinite period

And https://travis-ci.org/github/fsnotify/fsnotify is now closed and in read-only mode.

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.
> Travis CI - Test and Deploy Your Code with Confidence is in read-only mode. The historical data can be downloaded to external file storage.

We need some actions about it.

- Use other CI services
- Migrating to the com domain and upgrade to the paid plan
  - The lowest concurrency based plan is 1 Concurrent plan: $69/month
  - ref. https://docs.travis-ci.com/user/billing-overview/#travis-ci-plan-types
- Migrating to the com domain and upgrade to the OSS plan
  - we need to contact the Travis CI support team
  - ref. https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

However, it looks that any CI is working currently.

travis-ci: https://travis-ci.com/github/fsnotify/fsnotify

![image](https://user-images.githubusercontent.com/1157344/126037978-d2d9fead-01ec-466c-8d28-384bec6b10ce.png)

Check status on recent commit: https://github.com/fsnotify/fsnotify/pull/370#ref-pullrequest-930269021

![image](https://user-images.githubusercontent.com/1157344/126038072-4f706e24-5a2c-4379-a992-8cc08fe1ba2c.png)

Is there any plan to re-work CI?

**Comment by nathany** [comment]
There isn't a plan to rework CI yet, but thanks for bringing this up.

It may make sense to switch to GitHub Actions -- they have support for Linux, Windows, and macOS -- and support build matrixes.

**Comment by nathany** [comment]
resolved with #378
