### ISSUE TITLE
Confusion about Remove when combined with Add vs AddRaw

### ISSUE THREAD

**Issue by nshalman** [fsnotify/fsnotify#387]
### Please describe the issue that occurred.

While porting #371 to support AddRaw from #289 I run into the following conundrum:

If I AddRaw a symlink, I can Remove that symlink from being watched just fine.
If I Add a symlink, I cannot Remove the symlink directly, but would have to resolve it first.

What should fsnotify do?

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

See the test case added in #388

**Comment by nathany** [comment]
It does seem like a bug if Remove doesn't resolve symlinks the way Add does. Is that across every OS?

I'm not sure if we should go as far as `Remove` and `RemoveRaw` APIs.

To be honest, for the simplicity of the API, I'm starting to wonder if we should've made a breaking change (major version) that pushes the responsibility for `EvalSymlinks` up to the caller. 🤔 Probably not, but I had that thought.

@Code0x58 What do you think?

**Comment by Code0x58** [comment]
I added a comment on https://github.com/fsnotify/fsnotify/pull/388#discussion_r693552563. I'm not sure that a major change is worth it at the moment, as removing `Add`/`Remove` or replacing them with `AddRaw`/(presumably)`RemoveRaw` - there's still hope that `Add`/`Remove` could be incrementally improved to the point that they don't come with old caveats, so could be a nice transparent upgrade in the future.

**Comment by nshalman** [comment]
Fixed by #394
