### ISSUE TITLE
pipe[0] event unix.EPOLLHUP  loops forever

### ISSUE THREAD

**Issue by xvnuna** [fsnotify/fsnotify#395]
pipe[0] already read about event unix.EPOLLHUP，but stuck in an infinite loop here, why this occur and how should I handle this?
if event.Events&unix.EPOLLHUP != 0 {
	// Write pipe descriptor was closed, by us. This means we're closing down the
	// watcher, and we should wake up.
}

fsnotify version:1.4.9  
Go version:Go 1.14
arm64 linux

**Comment by arp242** [comment]
Since #434 we no longer use epoll, so this is no longer relevant (and the problem should be fixed with that).
