### ISSUE TITLE
Encounter an I/O exception when using fsnotify

### ISSUE THREAD

**Issue by TENX-S** [fsnotify/fsnotify#396]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Windows: 
```shell
OS Name:                   Microsoft Windows 10 Professional
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

### Please describe the issue that occurred.
Hi,

I use fsnotify to monitor a folder and calculate its SHA256 checksum whenever there is a new file. When I put the new files into the folder one by one, it works well. But when I moved many files at once (217 files, 5.5GB), I encountered the following exception:
```shell
panic: open C:\Users\Ares\Downloads\test\7 Years - Lukas Graham.flac: The process cannot access the file because it is being used by another process.

goroutine 20 [running]:
main.CalcFileSHA256({0xc000058140, 0xc000086600})
        D:/Developer/Projects/go_test/main.go:106 +0xa5
main.UploadFile({0xc000058140, 0x38}, 0x0)
        D:/Developer/Projects/go_test/main.go:113 +0x2d
main.main.func1()
        D:/Developer/Projects/go_test/main.go:146 +0xe7
created by main.main
        D:/Developer/Projects/go_test/main.go:138 +0x125
```
```go
// import ..
func CalcFileSHA256(FilePath string) string {
	data, err := os.ReadFile(FilePath)
	if err != nil {
		panic(err)
	}

	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		panic(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				if event.Op&fsnotify.Create == fsnotify.Create {
					FileHash := CalcFileSHA256(FilePath)
	                                fmt.Printf("%s : %s\n", FilePath, FileHash)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				panic(err)
			}
		}
	}()
	err = watcher.Add(os.Getenv(`C:\Users\Ares\Downloads\test`))
	if err != nil {
		panic(err)
	}
	<-done
```

**Comment by TENX-S** [comment]
Another corner case for this: when I moved a very large file (9.5 GB) to the target folder, the program immediately gave the SHA256 checksum, but the copy has not been completed yet, and the value is wrong.

**Comment by TENX-S** [comment]
close as resolved

**Comment by Cian911** [comment]
Hi @TENX-S 

Your comment here:
> Another corner case for this: when I moved a very large file (9.5 GB) to the target folder, the program immediately gave the SHA256 checksum, but the copy has not been completed yet, and the value is wrong.

I'm having the same problem myself. Did you manage to work around this or find a better solution? Could you offer it here if so?

**Comment by TENX-S** [comment]
> Hi @TENX-S
> 
> Your comment here:
> 
> > Another corner case for this: when I moved a very large file (9.5 GB) to the target folder, the program immediately gave the SHA256 checksum, but the copy has not been completed yet, and the value is wrong.
> 
> I'm having the same problem myself. Did you manage to work around this or find a better solution? Could you offer it here if so?

Hi @Cian911 
When copying this large file starts, there will be a `Create` event immediately, but this does not mean that the copying process has ended, so we must wait for the end of this process to calculate the SHA256 checksum. Unfortunately, fsnotify does not provide events like `CopyDone`. My workaround is to continuously poll the `CalcFileSHA256` until it does not return an error. But it assumes that the copy operation will always succeed.

**Comment by Cian911** [comment]
Interesting @TENX-S thanks for your explanation. The unique scenario I've run into is similar to this, the only difference being the file is being downloaded, so the file is not complete. I think I could do something similar to what you have done however, and poll for `WRITE` events to a file. Then after a period of no write events (x number of seconds or something like that) process the file.

Thanks for making me think about it!
