### ISSUE TITLE
Not work on a windows `net use` disk

### ISSUE THREAD

**Issue by lunny** [fsnotify/fsnotify#398]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Windows 7  6.1.7601 Service Pack 1 Build 7601

### Please describe the issue that occurred.

When watch a directory which is a `X:` disk but in fact mapping via `net use`, no any event fired.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

Yes, it's always.

**Comment by r-darwish** [comment]
Tried running the tests in Windows 10 accessing an Linux SMB servers and I do get events. Which operating system does the SMB server run?

**Comment by lunny** [comment]
The OS is running in vmware and mounting a disk from folder share feature by vmware.

**Comment by nathany** [comment]
I think this is the same or similar to #408 -- 

need to improve the documentation.

**Comment by arp242** [comment]
SMB isn't supported in the underlying API. It would work with a polling fallback if #326 gets implemented (although that might be slow).
