### ISSUE TITLE
It can not add twice without removing

### ISSUE THREAD

**Issue by 74302** [fsnotify/fsnotify#399]
in the file inotify.go: lines:115-121, function:

    func (w *Watcher) Add(name string) error {

	if watchEntry == nil {
		w.watches[name] = &watch{wd: uint32(wd), flags: flags}
		w.paths[wd] = name
	} else {
		watchEntry.wd = uint32(wd)
		watchEntry.flags = flags
	}

Is it missing to update the w.paths in case the file already in watch?

I guess each time after adding same path(file) should get same result, right?
But now in case add twice there would be no notification at all.

BRs,

**Comment by 74302** [comment]
I verified that 
wd, errno := unix.InotifyAddWatch(w.fd, name, flags)
the wd not has save value each time even the name of path are same.

**Comment by arp242** [comment]
`watchEntry` is a pointer, so updating it should also update the map.

I did a test where it updates the value, and it seems updated in both cases.

I'll close this for the time being. Let me know if you're still having problems and we can reopen it. It would be best if you can provide some example code to show the issue.
