### ISSUE TITLE
Emits multiple of the same events on change

### ISSUE THREAD

**Issue by jameygleason** [fsnotify/fsnotify#401]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: 
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute

### Please describe the issue that occurred.

Emits multiple of the same events on change

I've tried to debounce, but it didn't work. 

I'm trying to have it do only emit one event, say on save or a file being deleted.

The goal is to run a function once on a save/create/delete event.

**Comment by abenz1267** [comment]
this is a common "issue" and is solved creating a batcher of some kind. the implementation is up to you. look [here](https://github.com/gohugoio/hugo/blob/master/watcher/batcher.go) for an example.

This is not an "issue" per se.

**Comment by nathany** [comment]
Maybe all these "multiple events" issues should be addressed with documentation in the README?

Maybe a built-in batcher is a reasonable feature request as well?
