### ISSUE TITLE
Docker Volume Windows folder

### ISSUE THREAD

**Issue by iweixubin** [fsnotify/fsnotify#402]
Window10
Hyper-X
Docker-Desktop

docker image:  ubuntu:20.04

win10
watcher.Add("D:\\test")

the D:\\test folder has files aaa.deb; bbb.deb; ccc.deb; xxx.deb

docker 
watcher.Add("/app/test")

docker run container vol /app/test to D:\\test

when i delete xxx.deb(press Delete button)

the app log in win10:
**event: "D:\\test\\xxx.deb": REMOVE**

the app log in docker:    nothing

you can try copy  xxx.deb to D:\\test again, the app in docker only op.Write; not op.Create

if press Shift + Delete to delete file in D:\\test;  docker and win10  both  ok

**Comment by arp242** [comment]
"Special" filesystems such as shared volumes tend to not work all that well. Not sure there's much we can do about it. Also see the FAQ: https://github.com/fsnotify/fsnotify#why-dont-notifications-work-with-nfs-smb-fuse-proc-or-sys
