### ISSUE TITLE
Example incorrect?

### ISSUE THREAD

**Issue by dnj12345** [fsnotify/fsnotify#403]
Trying to understand if the example on the main page has an error. This line does not make sense to me:

```
if event.Op&fsnotify.Write == fsnotify.Write {
```

should it be?

```
if event.Op & event.Op == fsnotify.Write {
```

**Comment by shogo82148** [comment]
The example is correct.

`event.Op` might have some multiple operations e.g. `fsnotify.Create | fsnotify.Write`.
In this case, we want to know about only write operations, and don't need create options and other operations.
So we use `event.Op&fsnotify.Write` to omit other operation flags.
`event.Op&fsnotify.Write` will be `0` or `fsnotify.Write`, even if `event.Op` is `fsnotify.Create | fsnotify.Write`.

see https://en.wikipedia.org/wiki/Bitwise_operation
