### ISSUE TITLE
fsnotify.org domain no longer

### ISSUE THREAD

**Issue by benduncan** [fsnotify/fsnotify#407]
### Please describe the issue that occurred.

Looks like the fsnotify.org domain is no longer, picked up by an auto-renew bot. Might want to update the reference on the account profile in Github

**Comment by nathany** [comment]
Thanks for the note. I've removed the reference.

**Comment by shogo82148** [comment]
`fsnotify.org` is still in the About section.

![image](https://user-images.githubusercontent.com/1157344/145924007-2223d5e7-9238-4371-a901-c891cc6260e9.png)

**Comment by nathany** [comment]
Thanks. I've updated the sidebar.
