### ISSUE TITLE
watching for changes on SMB shared folder

### ISSUE THREAD

**Issue by ramigg** [fsnotify/fsnotify#408]
Is it possible to watch for shared folder changes. 
I mounted a windows shared smb folder to my mac and I don't receive events when modifying the folder from the windows machine. It works only when modifying the shared folder on the mac.

Thanks
Rami

**Comment by nathany** [comment]
No, shared folders aren't supported by the underlying Windows event system.

It may be possible with polling, but fsnotify doesn't have built-in polling as a fallback right now.
