### ISSUE TITLE
Dealing with Issues

### ISSUE THREAD

**Issue by Techassi** [fsnotify/fsnotify#417]
The purpose of this issue is to discuss how to deal with open issues as well as to track any issues being worked on.

### Issue Triage

My proposed process is:

1. Start from the back. It is recommended to start working through issues from oldest to newest.
2. Close any duplicates:
   - Old issues will get closed and labeled with `duplicate`
   - The most recent issue is kept open and should reference the old issues marked as `duplicate`
3. Now the remaining issues have to be labeled with labels like `bug`, `feature-request` or `improvement`. The priority is as follows: Bug > Improvement > Feature Request. They should also get labeled with the appropriate adapter and OS.
4. If there are any remaining issues which are not covered by the above process individual triage may be needed.

### Feature Requests

Each feature request should be carefuly considered as many projects use this library in the wild. Points to consider:

- Will this feature introduce any breaking change(s)?
- Will this feature be backwards compatible?
- Do we need this feature? Or can it be done with an already existing solution?

#### Bug Fixes

Insert a list of tracked bug fix issues

#### Improvements

Insert a list of tracked improvement issues

#### Features Requests

Insert a list of tracked feature request issues

@fsnotify/fsnotify Please let me know about the proposed process. This comment will be updated with any discussed changes.

**Comment by nathany** [comment]
This all sounds good to me

**Comment by horahoradev** [comment]
This sounds fine to me.

**Comment by pbnjay** [comment]
Related issue (happy to separate) - What are the plans for a v2 ? Is there a timeline, roadmap, or design document started?

We could start collecting some of these breaking changes and backwards-incompatible features there to provide more direction.

**Comment by nathany** [comment]
@pbnjay Maybe we could use a v2 label for issues? 

Some of the [API label](https://github.com/fsnotify/fsnotify/issues?q=is%3Aopen+is%3Aissue+label%3AAPI) may fall into that, but API just means new API, not necessarily breaking API changes.

A separate document could work to, though it may be nice to keep everything on GitHub in some form.

**Comment by arp242** [comment]
I think most duplicates should be closed now, as well as most issues that are already fixed or are unclear enough to not be actionable.

There are probably still some duplicates remaining, for example there are a bunch of issues for duplicate events. But this may get triggered under several distinct scenarios, so it requires deeper investigation.

So most open issues require actual work to be done to close them.
