### ISSUE TITLE
When a directory is removed, cleanup w.watches (internal)

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#42]
As reported in #41.

**Comment by timshannon** [comment]
FYI, I'm seeing this same behavior in my [project](https://bitbucket.org/tshannon/freehold-sync) and can readily duplicate it.

I'm going to look at synchthing's inotify library as they seemed to have fixed it.

**Comment by timshannon** [comment]
I've been able to duplicate this in a stand alone piece of code.

There is a gist here (https://gist.github.com/timshannon/603f92824c5294269797) that you can run to see this issue.

**Comment by nathany** [comment]
Thanks. Is this specifically occurring on Linux?

**Comment by timshannon** [comment]
No, it only happens on Windows.

Works fine on linux, i expect because linux doesn't hold onto file handles like windows.
