### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by Mattie112** [fsnotify/fsnotify#428]
Hi,

I'm using the code exactly as how it is listed in the readme (https://github.com/fsnotify/fsnotify#usage)

For path I used:
- `"C:/test"`
- `"C:\\test"`
- `"C:/test/test.txt"`
- `"C:\\test\\test.txt"`

It does not matter if I change a file or create a new one nothing is logged. The problem is not the logger as also the debugger does not break in the `select` statement.

I'm running Windows:
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1469
Experience	Windows Feature Experience Pack 120.2212.3920.0

Are there any known issues or tips how I can debug/test this further?

**Comment by mattn** [comment]
Could you please provide code to reproduce?

**Comment by Mattie112** [comment]
Yes, its just a copy/paste from the readme (with some logging changes and a send to channel)

```
func setupFileReader() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.WithField("eventName", event).Debug("event")
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.WithField("eventName", event.Name).Debug("modified file")
					readLogFile <- true
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
				log.WithError(err).Error("Unable to watch Factorio log file for changes")
			}
		}
	}()

	err = watcher.Add("C:\\test")
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by Mattie112** [comment]
Ah ****, I see it already I close the watcher. Sorry perhaps I was a bit to easy copying the entire example. Sorry for wasting your time!
