### ISSUE TITLE
cannot receive write event on windows

### ISSUE THREAD

**Issue by iamryanchia** [fsnotify/fsnotify#432]
When running following codes on windows, no write event received by fsnotify. However, when swapping the order of execution of `watch()` and `write()`, a write event will be received. I wonder is there any problem running on windows? Thank you.

I also found some differences between windows and linux: on windows, write will only be received once, while on linux, every time a line is written to the file, a write event will be received. Is this determined by OS?

windows version: windows 11 (21H2, 22000.493)
fsnotify version: 1.5.1

```go
package main

import (
	"log"
	"os"
	"time"

	"github.com/fsnotify/fsnotify"
)

func write() {
	f, _ := os.Create("log/a.log")
	for {
		time.Sleep(6 * time.Millisecond)
		t := time.Now().Format("20060102150405.000")
		f.WriteString(t + " test log\n")
	}
}

func watch() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Add("./log")
	if err != nil {
		log.Fatal(err)
	}
	<-done
}

func main() {
	go write()
	time.Sleep(time.Second) // let write run first
	watch()
}
```

**Comment by horahoradev** [comment]
It seems like you're writing, then subscribing to changes, in which case no event would be expected. I don't think there's any issue there.

Fsnotify is an API over the platform-specific FS event notification mechanisms; I'm not familiar with the Windows code, but for Linux fsnotify is a thin layer above inotify. If inotify sends an event, so does fsnotify. It would make sense that the event generation behavior on Windows would differ.

**Comment by horahoradev** [comment]
Feel free to respon if the above doesn't resolve your questions.
