### ISSUE TITLE
Add Github Action Tests for Minimum Supported OS Versions

### ISSUE THREAD

**Issue by horahoradev** [fsnotify/fsnotify#435]
**Is your feature request related to a problem? Please describe.**
We currently have rigid requirements around minimum supported OS versions, but have no automated tests running against these versions.

**Describe the solution you'd like**
We should add github actions for compilation and testing on all minimum supported platform versions.

**Describe alternatives you've considered**
We could:
1. not test, which in the best case degrades the feedback loop for contributors, and at worst will break our support for whatever platform
2. test in some other way than Github actions, which is legitimate, but Github actions are already in use and are fairly convenient

**Additional context**
n/a

**Comment by arp242** [comment]
I did some updates in #469.

Looking through the issues, it's rare someone reports an issue where it doesn't work on $older_version of a platform and the CI already takes quite a while to run; testing older versions of OpenBSD or whatnot probably has diminishing returns.

I think what we have now is "good enough" for the time being.
