### ISSUE TITLE
How many file descriptor is registered ?

### ISSUE THREAD

**Issue by anotherhope** [fsnotify/fsnotify#437]
**Is your feature request related to a problem? Please describe.**
i need to know how many file descriptor is registered in fsnotify to add a warning if the kernel limit is coming

**Describe the solution you'd like**
a method in struct Watcher that return the len(w.watches)

**Describe alternatives you've considered**
an inspector metod that expose data around the watcher struct

**Comment by tkan145** [comment]
Wouldn't it be a lot easier if you kept a map of the registered files?

**Comment by anotherhope** [comment]
> Wouldn't it be a lot easier if you kept a map of the registered files?

i see some problems:
- If i register a directory, all files/directories in this directory is registered in the watcher without i need to make a readDir to add them individually
- This consume memory for nothing it's already registered

**Comment by tkan145** [comment]
Do you mind if I ask which platform are you using?

on Linux, a call to Add will call 

```
func (w *Watcher) AddWithFlag(name string, flags uint32) error {
    name = filepath.Clean(name)                                 
    .....
    wd, errno := unix.InotifyAddWatch(w.fd, name, flags) 
    if wd == -1 {                                        
       return errno                                     
    }              
   if watchEntry == nil {                                      
      w.watches[name] = &watch{wd: uint32(wd), flags: flags}  
      w.paths[wd] = name                                      
   } else {                                                    
      watchEntry.wd = uint32(wd)                              
      watchEntry.flags = flags                                
   }
}
```                                                      
which means if you add a directory to watch, it will only add a single watch descriptor to the fsnotify watch list

On BSD it actually checks if the path is a Dir and manually register all the files within the Dir

```
func (w *Watcher) addWatch(name string, flags uint32) (string, error) {
   if isDir {                                                                              
      // Watch the directory if it has not been watched before,                           
      // or if it was watched before, but perhaps only a NOTE_DELETE (watchDirectoryFiles)
      .....                                                                       
                                                                                            
      watchDir := (flags&unix.NOTE_WRITE) == unix.NOTE_WRITE &&                           
         (!alreadyWatching || (w.dirFlags[name]&unix.NOTE_WRITE) != unix.NOTE_WRITE)     
        ....                                                                                                                                                   
      if watchDir {                                                                       
         if err := w.watchDirectoryFiles(name); err != nil {                             
            return "", err                                                              
         }                                                                               
      }                                                                                   
   }                                                                                       
   return name, nil                                                                        
}
```

Also, note that `InotifyAddWatch` returns a watch descriptor, not file descriptor

**Comment by anotherhope** [comment]
> Do you mind if I ask which platform are you using?

```
TARGET_OS = "linux" "darwin" "openbsd" 
TARGET_ARCH = "amd64" "arm64"
```

Window come later.

I try to create a tool like [syncthing](https://github.com/syncthing/syncthing), but with all communication protocol, [rclone](https://github.com/rclone/rclone) doing the job well.

I just need to wrap around this tool a way to trigger it regularly, in the first version it work like a cron task not really optimise so i use this project to detect any change and copyto / remove file if any manipulation was detected.

In my test a make a folder with 300 000 files inside, when i use Add on the folder `watchDirectoryFiles` is used and add in internalWatch all file inside the folder and make me 300 001 files descriptors

But with the kernel limitation i got "too many open files", at this point i would like to catch how many file is registered to give a warning if we reach the limit and maybe trigger another way to audit the file but less efficient way.

**Comment by horahoradev** [comment]
I would say that this isn't really fsnotify's responsibility. Monitoring the number of open fds is a general problem without specific relevance to fsnotify, and the general case should be solved.
