### ISSUE TITLE
v1.5.3 released from `master` instead of `main`

### ISSUE THREAD

**Issue by radeksimko** [fsnotify/fsnotify#445]
**Describe the bug**

https://github.com/fsnotify/fsnotify/releases/tag/v1.5.3 points to a commit from February on the `master` branch.

**Expected behavior**

https://github.com/fsnotify/fsnotify/releases/tag/v1.5.3 to point to the latest commit on `main`

**Additional context**

https://github.com/fsnotify/fsnotify/tags

![Screenshot 2022-04-22 at 06 54 24](https://user-images.githubusercontent.com/287584/164612114-5869c30c-ccc9-426d-ad61-5a30f47c797d.png)

**Comment by mattn** [comment]
Ah, I tagged commit provided from pull-request which was filed before we switched to main from master.

**Comment by mythi** [comment]
for github repos using dependabot, `v1.5.3`  gets proposed automatically which is probably not want people want so it'd nice to have this fixed

**Comment by mattn** [comment]
Fixed.

**Comment by radeksimko** [comment]
@mattn Would you mind cutting this as a separate 1.5.4 release/tag?

I think that all the caching layers incl. Go proxy will not appreciate force-pushed tag which was already cached and points to an existing hash. It also makes it hard for those who have already upgraded to the "previous" 1.5.3 to upgrade to the "new" 1.5.3.

**Comment by shogo82148** [comment]
I just release v1.5.4 and retracted v1.5.3.
Please get the latest version.

```
go get github.com/fsnotify/fsnotify@latest
```


And more, I updated v1.5.3 to the previous commit.
Getting v1.5.3 is now working, but you will see a warning message.

```
go get github.com/fsnotify/fsnotify@v1.5.3
go: warning: github.com/fsnotify/fsnotify@v1.5.3: retracted by module author: Published an incorrect branch accidentally https://github.com/fsnotify/fsnotify/issues/445
go: to switch to the latest unretracted version, run:
	go get github.com/fsnotify/fsnotify@latest
```
