### ISSUE TITLE
Missing defer in windows.go@WatchList

### ISSUE THREAD

**Issue by Sojamann** [fsnotify/fsnotify#446]
**Location**
windows.go line 103 of ref 8fa037fc336e718b89600a83712df72041cf851b (current HEAD) introduced in ceba4ef83ad7912d1ccf0b59e1ed8a13176f23b3

**Problem**
The mutex is unlocked right after locking it. It seems like somebody forgot to put it there. Both kqueue.go and inotify.go perform a defer.
```GO
func (w *Watcher) WatchList() []string {
   w.mu.Lock()
   w.mu.Unlock()
   // ....
}
```

**Should be**
```GO
func (w *Watcher) WatchList() []string {
   w.mu.Lock()
   defer w.mu.Unlock()
   // ....
}
```

**Comment by shogo82148** [comment]
fixed by #447
