### ISSUE TITLE
verifying module: checksum mismatch

### ISSUE THREAD

**Issue by CuteReimu** [fsnotify/fsnotify#449]
**Describe the bug**
When I upgrade it,
```bash
go get -u github.com/fsnotify/fsnotify
```
then end up with a failure,
```
go: downloading github.com/fsnotify/fsnotify v1.5.3
go get github.com/fsnotify/fsnotify@latest: github.com/fsnotify/fsnotify@v1.5.3: verifying module: checksum mismatch
        downloaded: h1:mZ5/lxbP3PUbatYYEagfAjj9NP2dYY39d64g0mjLWXI=
        sum.golang.org: h1:vNFpj2z7YIbwh2bw7x35sqYpp2wfuq+pivKbWG09B8c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Expected behavior**
To upgrade it correctly.

**Which operating system and version are you using?**
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.19044 暂缺 Build 19044
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free

**Additional context**
![image](https://user-images.githubusercontent.com/77955264/165379239-342ea1f4-3312-46f3-9d8a-857058447a4d.png)

**Comment by shogo82148** [comment]
v1.5.3 is published on an incorrect branch accidentally.
I just release v1.5.4 and retracted v1.5.3.
Please run `go get` again.

```console
go get github.com/fsnotify/fsnotify@latest
```

See also https://github.com/fsnotify/fsnotify/issues/445
