### ISSUE TITLE
Refactor code to better support both cross-platform and platform-specific features

### ISSUE THREAD

**Issue by NitroCao** [fsnotify/fsnotify#473]
This issue is a suggestion on how to refactor code to better support cross-platform and platform-specific features. And the idea comes from another project called [fswatch](https://github.com/emcrisostomo/fswatch), which is a cross-platform file change monitor with multiple backends written in C & C++.

First I would like to give a brief introduction to the implementation of fswatch:
* fswatch has a base class `monitor` (https://github.com/emcrisostomo/fswatch/blob/459d621164229fde685318eeefd6671e248ae595/libfswatch/src/libfswatch/c%2B%2B/monitor.hpp#L147). Each monitor implementation inherits from the base class, `inotify_monitor` (https://github.com/emcrisostomo/fswatch/blob/459d621164229fde685318eeefd6671e248ae595/libfswatch/src/libfswatch/c%2B%2B/inotify_monitor.hpp#L49), for example.
* fswatch defines common flags for notification event types (https://github.com/emcrisostomo/fswatch/blob/459d621164229fde685318eeefd6671e248ae595/libfswatch/src/libfswatch/c/cevent.h#L63). For those platform-specific types, fswatch requires each implementation to map them to `PlatformSpecific`. This is how inotify_monitor deals with event types: https://github.com/emcrisostomo/fswatch/blob/459d621164229fde685318eeefd6671e248ae595/libfswatch/src/libfswatch/c%2B%2B/inotify_monitor.cpp#L214-L236. Comments from the source code:
> A monitor implementation is required to map implementation-specific flags into API flags.  Sometimes, though, a perfect match is not possible and the following situation may arise:
>  - One platform-specific flag must be mapped into multiple API flags.
>
>  - Multiple platform-specific flags must be mapped into a single API flag.
>
>  - A mapping is not possible for some flags, in which case they should be mapped to `fsw_event_flag::PlatformSpecific`.  The API currently offers no way to retain a platform-specific event flag value in this case.
* fswatch has a factory function called `create_monitor()` (https://github.com/emcrisostomo/fswatch/blob/459d621164229fde685318eeefd6671e248ae595/libfswatch/src/libfswatch/c%2B%2B/monitor_factory.cpp#L40-L64) to select a default monitor implementation according to the platform.

A few suggestions based on fswatch:
* Define an interface `Watcher`, any monitor implementation must implement this interface. For example:
``` go
type Watcher interface {
    Add(name string) error
    Remove(name string) error
    WatchList() []string
}
```
* Add a field `SpecificOps` for `Event` struct to store platform-specific event types in order to give users a chance to decide how to deal with those events:
``` go
type Event struct {
    Name string
    Op Op
    SpecificOps int64
}
```
* Support monitoring directories recursively. Add directories manually in user space for those platforms which doesn't support built-in recursive monitor such as inotify.

**Comment by arp242** [comment]
> Define an interface Watcher

Unfortunately this is not a compatible change, so this isn't something we can just change.

> Add a field SpecificOps for Event struct to store platform-specific event types in order to give users a chance to decide how to deal with those events

What is your use case for this? I'd like to avoid doing this, since much of the purpose of this library is to provide *cross-platform* capabilities.

> Support monitoring directories recursively. Add directories manually in user space for those platforms which doesn't support built-in recursive monitor such as inotify.

There's an issue for this: #18. I did some work for inotify (#472) and there's a PR for Windows as well (#339); still quite some work left for this though.

**Comment by arp242** [comment]
Since most points raised here are duplicates of existing issues – as well as backwards-incompatible changes – I'll close this for now.
