### ISSUE TITLE
inotify blocks

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#5]
readEvent() currently blocks.

See https://code.google.com/p/go/issues/detail?id=5536

@howeyc attempted to change this in 3bfa915bde2415222d8dc048945f701353508160 but reverted it 7beb45183d2ab48bfc9616d9a019513a123a4983 due to reports of no new events https://github.com/howeyc/fsnotify/issues/52.

>  This was something I added to stop readEvent from blocking forever.
> Basically calling close would mean no new data came to the file descriptor
> and Read would block forever.
> 
> This was an attempt to use select with a timeout so it would return after
> the timeout stating whether there was new data.

**Comment by matthias-stone** [comment]
This appears to have been fixed a while ago. Watcher.Close() is returning in our tests, which waits for readEvents to when closed.
