### ISSUE TITLE
Open and Close events

### ISSUE THREAD

**Issue by baryluk** [fsnotify/fsnotify#504]
I would like the ability to watch for Create, Open and Close events.

These are possible to watch on Linux.

**Comment by arp242** [comment]
I don't know what the cross-platform capabilities here are? It needs to be supported by all platforms (kqueue on BSD and macOS, FEN on Solaris, Windows) to add `fsnotify.[…]` events.

There's an issue for exposing things in a non-portable way: #67

Also closely related: #7, #297, #346.

**Comment by arp242** [comment]
I created a new issue to track adding additional events: #519 Bit easier to have one issue instead of a bunch for every possible event.
