### ISSUE TITLE
Basic example does not work (readme.md)

### ISSUE THREAD

**Issue by a-menshchikov** [fsnotify/fsnotify#513]
Event has no method `Has`, so the basic example does not work.

**Comment by jenswegar** [comment]
If you installed fsnotify using ```go get github.com/fsnotify/fsnotify``` then you probably downloaded fsnotify 1.5.4, which has a different example compared to the latest in the main branch. If you switch to the 1.5.4 branch here on github you see the old example, which should work (at least it compiled on my machine)

**Comment by arp242** [comment]
^ Yup, that.

It's mentioned in the README:

> It's best to read the documentation at pkg.go.dev, as it's pinned to the last released version, whereas this README is for the last development version which may include additions/changes.
