### ISSUE TITLE
On MacOS, removing watched directory produces series of wrong create/remove events

### ISSUE THREAD

**Issue by SergeyTsalkov** [fsnotify/fsnotify#514]
**Describe the bug**
On MacOS, there is a weird behavior if you use `rm -fr` to delete a watched directory. You get a flurry of REMOVE events in no particular order. After the REMOVE event for the directory itself is processed, any subsequent REMOVE events for files in that directory are not processed correctly.

**To Reproduce**
1. Create a test folder: `mkdir ~/testdir && cd ~/testdir`
2. Use the demo code under README to watch that folder. Keep watching while you do the remaining steps.
3. Create some files in test folder: `touch a b c d e f g`
4. Delete folder: `cd .. && rm -fr testdir`
5. The demo code will produce incorrect removal events:

```shell
% go run test.go
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/a"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/b"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/c"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/d"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/e"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/f"
2022/10/10 15:25:23 event: CREATE        "/Users/sergey/testdir/g"
2022/10/10 15:25:44 event: REMOVE        "/Users/sergey/testdir/g"
2022/10/10 15:25:44 event: REMOVE        "/Users/sergey/testdir/a"
2022/10/10 15:25:44 event: REMOVE|WRITE  "/Users/sergey/testdir"
2022/10/10 15:25:44 modified file: /Users/sergey/testdir
2022/10/10 15:25:44 event: REMOVE        ""
2022/10/10 15:25:44 event: CREATE        "."
2022/10/10 15:25:44 event: REMOVE        ""
2022/10/10 15:25:44 event: CREATE        "."
2022/10/10 15:25:44 event: REMOVE        ""
2022/10/10 15:25:44 event: CREATE        "."
2022/10/10 15:25:44 event: REMOVE        ""
2022/10/10 15:25:44 event: CREATE        "."
2022/10/10 15:25:44 event: REMOVE        ""
2022/10/10 15:25:44 event: CREATE        "."
```

**Which operating system and version are you using?**
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

**Comment by arp242** [comment]
Removing the watched directory is kinda borked on several platforms. I'm not even sure it's easily fixable on some of them; you get a file descriptor to a directory and when you remove that directory the file descriptor is gone – so what do we do then? Poll the filesystem until a path with that name appears again? This is what e.g. `tail -F` (or `tail --retry`) does. We'll have to deal with errors, add options for the poll interval, etc.

Something that should be added at some point probably, but it's more than "just a simple bug". For now, the directory should be unwatched before removing it, although that's not easy if it's removed outside of the applications' control. It might be easy to automatically remove the watch if the directory disappears.

**Comment by arp242** [comment]
Actually it's documented as "A watch will be automatically removed if the path is deleted", so that part is definitely a bug.
