### ISSUE TITLE
illumos build fails in CI

### ISSUE THREAD

**Issue by arp242** [fsnotify/fsnotify#515]
CI build on main fails for illumos with:

    --- FAIL: TestAdd (0.00s)
        --- FAIL: TestAdd/permission_denied (0.23s)
            fsnotify_test.go:918: error is nil

Bit odd, because it works for me if I run it in illumos 🤔

```
[~/fsnotify]% go test -run TestAdd/permission_denied -v
=== RUN   TestAdd
=== RUN   TestAdd/permission_denied
=== PAUSE TestAdd/permission_denied
=== CONT  TestAdd/permission_denied
--- PASS: TestAdd (0.00s)
    --- PASS: TestAdd/permission_denied (0.20s)
PASS
ok      github.com/fsnotify/fsnotify    0.213s
[~/fsnotify]% uname -a
SunOS omnios 5.11 omnios-r151042-2a01bcc289 i86pc i386 i86pc
```

Maybe an illumos version thing? Two builds failed on this error, so doesn't seem like a fluke in the CI.

@nshalman

**Comment by nshalman** [comment]
This is due to the CI test running as root. The permissions don't stop root from accessing things. We probably need an improved CI solution for illumos...

https://github.com/fsnotify/fsnotify/pull/371#issuecomment-1246794269

**Comment by arp242** [comment]
Ah, right; I actually fixed that before for the BSD builds by adding a user and then using `su` to run it like that: https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml#L109 – I should have remembered.

Should do the same for illumos. I'll look in to it later.
