### ISSUE TITLE
Renamed operation instead of Remove

### ISSUE THREAD

**Issue by msoft-dev** [fsnotify/fsnotify#529]
**Describe the bug**
When handling `fsnotify.Event` for removed file, the `event.Op` is equal to `fsnotify.Rename` instead of `fsnotify.Remove`.

**To Reproduce**
1. Create directory with a file A.txt
2. Add this directory to `fsnotify.Watcher`
3. Subscribe for events:
```
go func() {
		for {
			select {
			// watch for events
			case event := <-watcher.Events:
				log.Printf("%+v", event)
			case err := <-watcher.Errors:
				panic(err)
			}
		}
	}()
```
5. Run the program
6. Remove file A.txt
7. You will see in the logs `event.Op` equal to `Rename`

**Expected behavior**
`event.Op` should be equal to `Remove`

**Which operating system and version are you using?**
macOS: 12.5 (21G72) (Apple M1 Pro)

**Comment by arp242** [comment]
How do you remove the file? Is it possible that the "remove" really *does* actually rename the file (e.g. move it to the trash bin)?

**Comment by msoft-dev** [comment]
It doesn't matter how, either using `CMD+Backspace` or `Send to bin` command on mac os. And why moving to bin does rename?

**Comment by arp242** [comment]
Renaming a file to a special "Trash" directory is a lot faster than copying all the data and then removing the original file. This is how Finder works; if you use `os.Remove()` from Go you should get a Remove event.

I'd have to check and verify, but I think this is more of a documentation problem than a bug; I don't think there's any way we can improve on this, and the behaviour isn't neccisarily "wrong" either, it's just that Finder does something different under the hood that you expect. For most cases, you can probably treat a Rename even identical to Remove.
