### ISSUE TITLE
Unable to build on AppEngine due to unsafe code

### ISSUE THREAD

**Issue by arp242** [fsnotify/fsnotify#534]
Reported here https://github.com/spf13/viper/issues/538

> Viper imports github.com/fsnotify/fsnotify, which imports unsafe, which is not allowed on appengine.

The unsafe.Pointer is used to get unix.InotifyEvent and the pathname out of the buffer; but maybe that's not needed?

Otherwise fiddle with build tags a bit so it uses backend_other.go; not sure if inotify even words on AppEngine

**Comment by sagikazarmark** [comment]
I copied the build tags from backend_other.go to the wrapper we have in Viper. If you figure out how to disable/make fsnotify on appengine, I can update the build tags or upgrade to the next version when it becomes available.

Thanks!

**Comment by arp242** [comment]
I've seen the `appengine` build tag used for this in some golang.org/x/... packages. I don't think Go sets that automatically like `linux`, `amd64`, etc. but it's the best we have.
