### ISSUE TITLE
Why not use buffered channels on other operating systems other than windows?

### ISSUE THREAD

**Issue by hkhere** [fsnotify/fsnotify#536]
On windows the `Events` is a cap 50 buffered channel, as the code below shows. But on other operating systems the `Events` is unbuffered(`make(chan Event)`). May I know the rationale behind this design? Sometimes I want to be able to handle all events in on iteration in my case.
```go
// NewWatcher creates a new Watcher.
func NewWatcher() (*Watcher, error) {
	port, err := windows.CreateIoCompletionPort(windows.InvalidHandle, 0, 0, 0)
	if err != nil {
		return nil, os.NewSyscallError("CreateIoCompletionPort", err)
	}
	w := &Watcher{
		port:    port,
		watches: make(watchMap),
		input:   make(chan *input, 1),
		Events:  make(chan Event, 50),
		Errors:  make(chan error),
		quit:    make(chan chan<- error, 1),
	}
	go w.readEvents()
	return w, nil
}

```

**Comment by arp242** [comment]
I don't know if there's a specific reason for this; if there is, it's been lost to the mists of time as this code goes back quite a way. The Windows backend came from Go's stdlib exp/winfsnotify package, and always had a buffer size of 50: https://github.com/golang/go/commit/7ecf6c997e786b4812ae5d5f6afade15a3717fa9

We could maybe add an option to control the buffer size, although I'm not sure what use case exactly you have where you want this?

**Comment by hkhere** [comment]
@arp242 Thanks for the reply.
In my case I am monitorying a file, if the file has changed I will take some actions. The file I am monitoring may change so frequently, I want to do something like the code below, which may save some cpu cycles because I can `take_some_actions()` in respect to multiple events instead of one event one `take_some_actions()` in case when the file has so many change in a short period of time.
```go
case event, ok := <-watcher.Events:
    if !ok {
        return errors.New("watcher.Events not ok")
    }
    time.Sleep(time.Second)
    elen := len(watcher.Events)
    for i := 0;  i < elen ; i++ {
        event, ok := <-watcher.Events
        if !ok {
            return errors.New("watcher.Events not ok")
        }
    }
    take_some_actions()
```

**Comment by arp242** [comment]
> I want to do something like the code below, which may save some cpu cycles

Does that make a big difference in terms of performance?

**Comment by hkhere** [comment]
> > I want to do something like the code below, which may save some cpu cycles
> 
> Does that make a big difference in terms of performance?

Yes, the `take_some_actions` is expensive.

**Comment by arp242** [comment]
Right, so the performance issues isn't in the receiving of the events but in the actions you take? Or, to rephrase your question is a more open-ended way: "how can I use fsnotify to run an action only once every *n* seconds at the most, rather than for every event?"

Right now, you can solve it with a second channel, something like:

```
events := make(chan fsnotify.Event, 50)

go func() {
	for {
		select {
		case event, ok := <-watcher.Events:
			if !ok {
				close(events)
				return errors.New("watcher.Events not ok")
			}
			events <- event
		}
	}
}()

go func() {
	for event <- events {
		time.Sleep(time.Second)
		elen := len(watcher.Events)
		for i := 0;  i < elen ; i++ {
			event, ok := <-events
			if !ok {
				return errors.New("watcher.Events not ok")
			}
		}
	}
}()
```

Which is arguably a little bit ugly.

I need to think a bit about the best way to solve this; there's probably a better way to solve this than just setting the buffer size. We already have the [dedup example](https://github.com/fsnotify/fsnotify/blob/main/cmd/fsnotify/dedup.go) which is similar, and ideally that should be easier too.

**Comment by hkhere** [comment]
Thanks. The code you provided is good enough for my use case.

**Comment by hkhere** [comment]
Although I do think it is good to have buffered channels in other operating systems too, which also seems to be more consistent.
