### ISSUE TITLE
Watching a path more than once may not return an error

### ISSUE THREAD

**Issue by NitroCao** [fsnotify/fsnotify#548]
Before reporting an issue, please ensure you are using the latest release of `fsnotify`, and please
search for existing issue to avoid duplicates.

**Describe the bug**
From the doc of `Add()` method, `A path can only be watched once; attempting to watch it more than once will return an error`. But after testing, the second watch operation works well and no error occurs.  
Also from the manual of `inotify_add_watch()` function, `If pathname was already being watched, then the descriptor for the existing watch is returned`.  
So should we update the doc of `Add()` method?

https://github.com/fsnotify/fsnotify/blob/5f8c606accbcc6913853fe7e083ee461d181d88d/backend_inotify.go#L208-L213

**Comment by arp242** [comment]
I added a test and it seems to behave identical on all platforms. I don't know where that line came from; but it seems like it has behaved like this for at least two years, so I updated the documentation.
