### ISSUE TITLE
Deadlock due to unbuffered channel

### ISSUE THREAD

**Issue by clipperhouse** [fsnotify/fsnotify#55]
Mac OS 10.10.1, go version go1.4 darwin/amd64, pulling from tip which as of this writing is https://github.com/go-fsnotify/fsnotify/commit/f582d920d11386e8ae15227bb5933a8f9b4c3dec

This program will deadlock, even though I believe it's a correct use of the API:

```
package main

import (
    "fmt"

    "github.com/go-fsnotify/fsnotify"
)

func main() {
    watcher, err := fsnotify.NewWatcher()

    if err != nil {
        panic(err)
    }
    defer watcher.Close()

    watcher.Add("./")

Loop:
    for {
        select {
        case event := <-watcher.Events:
            fmt.Println(event)
            break Loop
        case err := <-watcher.Errors:
            fmt.Println(err)
            break Loop
        }
    }
}
```

(Save a file in the current directory to trigger an event and see the deadlock.)

It is fixed by giving the internal done channel a buffer of 1 (which seems to be the case in `inotify.go`).

**Comment by mjibson** [comment]
@clipperhouse FYI I also can't repro this (with either versions posted here) on my mac.
