### ISSUE TITLE
Make Op.Has check all provided flags

### ISSUE THREAD

**Issue by acetylen** [fsnotify/fsnotify#551]
When filtering events, the implementation of [Op.Has](https://github.com/fsnotify/fsnotify/blob/edf810edc9954847115bf68c800336edcfa0cb43/fsnotify.go#L96)  (`o&h == h`) means that the check needs to be

```go
if event.Has(fsnotify.Create) || event.Has(fsnotify.Write) || event.Has(fsnotify.Remove) {
```

to handle multiple cases.
Why is the check not `o&h > 0` or `o&h != 0`? Then a filter check would be much more terse:

```go
if event.Has(fsnotify.Create | fsnotify.Write | fsnotify.Remove) {
```

Or is this case uncommon enough that there's no demand?

**Edit:**
I just noticed PR #544. This is apparently not something you want.

**Comment by acetylen** [comment]
I just noticed PR #544. This is apparently not something you want.

**Comment by arp242** [comment]
That PR is about something else: it just changes the expression, but is still identical in behaviour.

I'm not strictly opposed to this, although it's in a tagged release so changing the behaviour needs to be considered carefully with regards to compatibility. What if someone wrote `event.Has(fsnotify.Create | fsnotify.Write)` to check if it has *both* flags set? I suspect no one has done this though, as in reality practically all events have just one event set.

I'm also not entirely convinced `event.Has(fsnotify.Create | fsnotify.Write | fsnotify.Remove)` is entirely clear. `event.HasAny(Event, ...Event)` might be better: `event.HasAny(fsnotify.Create, fsnotify.Write, fsnotify.Remove)`.

**Comment by arp242** [comment]
I think the biggest question is:

> Or is this case uncommon enough that there's no demand?

And I don't know. Would be nice to quantify this a little bit by checking *how* people are using fsnotify. Unfortunately it's not very easy to get fsnotify users by GitHub stars so we can see what the top-n users of fsnotify are doing (I looked at this before).

**Comment by acetylen** [comment]
It may just be because of personal experience, but whenever I see a bitmask in a library I assume that it's a bitmask _because I should_ combine flags into it. I think there's value in "doing the obvious thing", but as you say we don't really know what the obvious thing is here.

Maybe looking at popular Go packages and how they handle bitmasks can give a hint as to the most common approach?

**Comment by acetylen** [comment]
The first thing I found is the standard library's [`os.OpenFile(name string, flag int, perm FileMode)`](https://pkg.go.dev/os#OpenFile), where both `flag` and `perm` are bitmasks that can be (and most commonly are) combined.

Then again, I've been away from the Go ecosystem for a while, maybe these aren't recommended anymore...

**Comment by acetylen** [comment]
Also, that PR _does_ change the behavior of Has slightly; it implements the same change I suggested above by allowing combined flags. But the base case of one flag per call is still available.

**Comment by arp242** [comment]
> Also, that PR _does_ change the behavior of Has slightly; it implements the same change I suggested above by allowing combined flags. But the base case of one flag per call is still available.

Looking at it again, you're right. It was presented as a "no op" change so I never really looked beyond that. Judging from the added tests and PR description, it seems that any change of behaviour was accidental.

Either way, the only reason that got closed as it seemed like replacing one thing with another identical thing. The author closed it themselves, but if they had come back with "this changes the behaviour to be more useful" then we'd be having this discussion on that PR.

**Comment by acetylen** [comment]
They did add tests for multiple-flag arguments, but you're right that it should probably have come with a comment for clarification. At least this means that I won't have to write a new PR for this :smiley:

**Comment by arp242** [comment]
It only tests things one-way: for `event.Has(check)` it has multiple events in `event`, but only ever one for `check`. The tests pass on the current main branch.

Anyway, `os.OpenFile(name string, flag int, perm FileMode)` is different because it doesn't check if a value contains a specific bitmask, but rather passes a set of flags. As far as I can recall, I don't think there's anything in stdlib that checks for the presence of flags.

I had a bit of a think about this, and `Has(fsnotify.Create | fsnotify.Write)` checking if it "contains any one of" seems unintuitive to me, I'd expect it to check "contains all of" instead. But maybe that's just me.

**Comment by acetylen** [comment]
Yeah that example was not as relevant as i first thought.

In my mind, bitwise OR signifies "check if op is in the set `{a|b|c}`", aka "this OR this OR this", while an AND would be "check if  op == the set" (not that it would actually work with a bitwise AND), but i don't know what interpretation is the most common.

**Comment by arp242** [comment]
I applied #544; I don't think it will do any harm, and I agree it's more consistent with what people would expect.
