### ISSUE TITLE
How to know by which user the Changes/deleted/added are done ? 

### ISSUE THREAD

**Issue by themeswordpress** [fsnotify/fsnotify#555]
Dears,

Per my notice the fsnotify doesn't told my anything about who the did the changes why?

**Comment by arp242** [comment]
Most operating systems provide no facility for this, so it's not something that can be added (fanotify on Linux is the exception, but we have no support for that yet, and there are some caveats with that too).

**Comment by themeswordpress** [comment]
is there any workaround, I,e how cimcore solution can detect by which user and who did the changes?
