### ISSUE TITLE
Inconsistent behavior watching a file on MacOS

### ISSUE THREAD

**Issue by vmpstr** [fsnotify/fsnotify#560]
There are some situations where I am editing a file in vim, and the watch events stop happening after a "RENAME".

I'm using cmd/fsnotify from this repo like this:
`$ ./fsnotify file /var/log/test.log`

Note that on my machine `var` is a symlink to `/private/var`. This seems relevant because I've only experienced this problem in directories that have a symlink in their path.

Here are the steps I take (or take a look at the video: https://www.youtube.com/watch?v=9UhJI_XMItY):
1. Open vim: `$ vi /var/log/test.log`
2. Save the new file: `:w`
3. (another terminal) Run fsnotify to watch the file: `$ ./fsnotify file /var/log/test.log`
4. Type something into the file: `ihello world!<esc>`
5. Save the file: `:w`
6. (another terminal) observe msg: `21:17:22.5129   1 RENAME        "/var/log/test.log"`
7. Save the file again: `:w`
8. (another terminal) observe no new messages
9. Type more text and save
10. (another terminal) no more messages
11. (third terminal) verify contents of file have changed: `cat /vaar/log/test.log` -- they have.

Here's another interesting bit:

12. Exit vim: `:q`
13. (another terminal) observe message: `21:19:19.5928   2 CREATE        "/var/log/test.log"`
14. Repeat steps 1 and 2 (edit the file again and save it)
15. (another terminal) observe expected messages:
```
21:20:03.5746   9 RENAME        "/var/log/test.log"
21:20:03.5909  10 CREATE        "/var/log/test.log"
21:20:03.6041  11 CHMOD         "/var/log/test.log"
```

From here, I can exit and edit and save the file with all of the expected message. The problem seems to be limited to creating a file in vim. If I `touch /var/log/test.log` then open fsnotify, then edit, everything works.

As I'm typing this, I realize what I should in my workflow: create the file first, then set up the watch, then edit.

However, I am still filing this for posterity, and in case there's some bug that could be fixed

**Which operating system and version are you using?**

ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68

**Comment by nal** [comment]
Confirm the same behaviour on MacOS and Rocky Linux 9.
Used example from here: https://github.com/fsnotify/fsnotify#usage

**Which operating system and version are you using?**
ProductName: macOS
ProductVersion: 12.6.7

ProductName: Rocky Linux release 9.2 (Blue Onyx)
KernelVersion: 5.14.0-284.11.1.el9_2.x86_64 x86_64 GNU/Linux

**Comment by arp242** [comment]
from the Watcher.Add() docs:

> Watching individual files (rather than directories) is generally not recommended as many tools update files atomically. Instead of "just" writing to the file a temporary file will be written to first, and if successful the temporary file is moved to to destination, removing the original, or some variant thereof. The watcher on the original file is now lost, as it no longer exists.
>
> Instead, watch the parent directory and use [Event.Name] to filter out files you're not interested in. There is an example of this in cmd/fsnotify/file.go

I'll add it back to the README I guess because people keep running in to this.

**Comment by vmpstr** [comment]
> There is an example of this in cmd/fsnotify/file.go

The repro steps listed in the original comment use `cmd/fsnotify`. I've just verified with the latest version that the problem still persists. I agree that watching a directory is correct, but there seem to be no events with this name after the initial rename

**Comment by vmpstr** [comment]
I've also tried the directory watch to get all events on `/var/log` and I still only get the `RENAME`. I suspect symlink directory here is to blame, but I'm not sure what the solution is.
