### ISSUE TITLE
Add minimum permissions to workflows

### ISSUE THREAD

**Issue by gabibguti** [fsnotify/fsnotify#561]
**Is your feature request related to a problem? Please describe.**
This feature request is related to a security improvement in order to avoid some types of supply-chain attacks. The GitHub workflows are given a GITHUB_TOKEN to execute the workflow actions. The problem is that this GITHUB_TOKEN, by default, is granted higher access than necessary, making way to supply-chain attacks.

**Describe the solution you'd like**
The solution I'd like is for us to set least-privilege access to the GITHUB_TOKEN in workflows. We can do that by checking which actions are used in the workflow jobs and granting them only the access they need. For example, the `build` workflow uses `actions/setup-go` and `actions/checkout` actions, so granting `contents: read` access would be enough to perform the work :)

**Describe alternatives you've considered**
None.

**Additional context**
Adding minimum permissions to workflows is considered good-practice and recommended by [GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) itself and by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

About me, I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

If you agree, I can open a PR so you can see the modifications.

**Comment by arp242** [comment]
I set "Workflow permissions" to read-only in the settings; I think that's enough?

**Comment by gabibguti** [comment]
Hi @arp242! Yes! That's enough. Thank you!
