### ISSUE TITLE
watcher.Events undefined and watcher.Errors undefined

### ISSUE THREAD

**Issue by jameygleason** [fsnotify/fsnotify#562]
`watcher.Events` and `watcher.Errors` are undefined.

Linux: PopOS
Go: 1.20.2
Go VSCode Ext: 0.38.0
Gopls: 0.11.0
VSCode: 1.76.2

```
watcher.Events undefined (type *fsnotify.Watcher has no field or method Events)

watcher.Errors undefined (type *fsnotify.Watcher has no field or method Errors)
```

```go
	// File watcher
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	// Start listening for file system events
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}

				fmt.Println("EVENT:", event)

				if event.Has(fsnotify.Chmod) {
					fmt.Println("Changed file:", event.Name)
				}

				if event.Has(fsnotify.Rename) {
					// Rename file
					// Removed file
					fmt.Println("Renamed file:", event.Name)
				}

				if event.Has(fsnotify.Write) {
					fmt.Println("Modified file:", event.Name)
				}

				if event.Has(fsnotify.Create) {
					// Rename file
					fmt.Println("Created file:", event.Name)
				}

				if event.Has(fsnotify.Remove) {
					fmt.Println("Removed file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				fmt.Println("error:", err)
			}
		}
	}()
```

**Comment by arp242** [comment]
Which version of fsnotify are you using? Does it still happen with the latest main build?

**Comment by arp242** [comment]
Does it still happen with the latest main branch?

**Comment by jameygleason** [comment]
I cloned the latest main and added the following to my go mod.

```go
require github.com/fsnotify/fsnotify v1.6.0

replace github.com/fsnotify/fsnotify v1.6.0 => ../../fsnotify
```

That fixes the undefined error for both. Not sure what might cause that? But thank you.

I'm also seeing interesting behavior around file events. For instance:

1. A "save" fires two write events
2. Deleting a file fires a rename event, .
3. Creating a file fires create > write > chmod > write > chmod

Is this expected?

**Comment by arp242** [comment]
I'm not sure off-hand which change would have fixed it for you; my guess it has something to do with the Errors and Events fields being added to the fallback no-op backend.

File operations are often more complex than "just" a system call; for example a "delete" action from the UI can trigger moving the file to the trash bin, which shows up as rename; some editors and tools also have "tricks" to make sure files are written atomically, which can show up as a series of events. It really depends on how you're operating on files. There isn't really a good way to fix this: all we see are the operations on system call level.
