### ISSUE TITLE
Non-deterministic behavior for file and directory creation events on Mac OSX

### ISSUE THREAD

**Issue by shrinandj** [fsnotify/fsnotify#565]
Before reporting an issue, please ensure you are using the latest release of `fsnotify`, and please
search for existing issue to avoid duplicates.

**Describe the bug**
When a file and directory were created in a directory that was watched, `fsnotify` delivered events for the file twice instead of an event for a file and a directory.

**To Reproduce**
Setup a watch on a directory. Create a file, say F, in the directory. `fsnotify` correctly delivered an event. Then create a subdirectory in the directory that was watched. `fsnotify` delivered an event for F instead of the newly created directory.

This only happens when the file and directory are being created programmatically. When I did this from the command line, everything worked just as expected.

Here's the sample code:
```
	dir, err := os.MkdirTemp("/tmp", "dirtest")
	if err != nil {
		t.Error(err)
	}
	defer os.RemoveAll(dir)

	data := []byte("some file data goes here")
	err = ioutil.WriteFile(filepath.Join(dir, "f1"), data, 0)
	if err != nil {
		t.Error(err)
	}

	time.Sleep(1 * time.Second)

        // OBSERVATION: FILE creation notification gets delivered just fine.

	subdir, err := ioutil.TempDir(dir, "subdir")
	if err != nil {
		t.Error(err)
	}
	t.Log("created subdir: " + subdir)
	time.Sleep(5 * time.Second)
        // OBSERVATION: AGAIN, a FILE creation notification gets delivered. Not the directory creation event
```

Stdout of the program that's using fsnotify:
```
2023/05/06 17:37:28 INFO starting operations on cache dir=/tmp/dirtest2804732643
2023/05/06 17:37:28 INFO file/dir to watch path=/tmp/dirtest2804732643
2023/05/06 17:37:28 INFO watching directory path=/tmp/dirtest2804732643
2023/05/06 17:37:28 INFO file event op=CREATE name=/tmp/dirtest2804732643/f1 address=0x1400000f620
2023/05/06 17:37:28 INFO created filename=/tmp/dirtest2804732643/f1
    operate_test.go:67: created subdir: /tmp/dirtest2804732643/subdir2462348104
2023/05/06 17:37:29 INFO file event op=CREATE name=/tmp/dirtest2804732643/f1 address=0x140003100d8
2023/05/06 17:37:29 INFO created filename=/tmp/dirtest2804732643/f1
```

**Expected behavior**
There should've been events for the file AND a directory.

**Which operating system and version are you using?**
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68

**Additional context**
```
 github.com/fsnotify/fsnotify v1.6.0
```

**Comment by arp242** [comment]
Can you try using the latest `main` branch? It's possible it's already fixed there; there have been a number of improvements.

Unfortunately my macOS VM refuses to run at the moment; I'll have to look at this later.
