### ISSUE TITLE
Windows  received two write events 

### ISSUE THREAD

**Issue by HuckOps** [fsnotify/fsnotify#567]
**Describe the bug**
A file watcher by fsnotify on windows   received two write events when i edit the file.The frist time func Read return empty.

**Expected behavior**
Received only one event while editing a file

**Which operating system and version are you using?**

Windows: Windows 11

**Additional context**
```go
type watcher struct {
	f  *file
	fw *fsnotify.Watcher
}
func NewWatcher(f *file) (source.Watcher, error) {
	fswatcher, err := fsnotify.NewWatcher()
	if err != nil {
		return nil, err
	}
	fswatcher.Add(f.path)
	return &watcher{
		f:  f,
		fw: fswatcher,
	}, nil
}
func (w *watcher) Next() (*source.ChangeSet, error) {
	select {
	case event, _ := <-w.fw.Events:
		if event.Op == fsnotify.Rename {
			// check existence of file, and add watch again
			_, err := os.Stat(event.Name)
			if err == nil || os.IsExist(err) {
				err := w.fw.Add(event.Name)
				if err != nil {
					return nil, err
				}
			}
		}
		fmt.Println(event)
		c, err := w.f.Read()
		if err != nil {
			return nil, err
		}
		return c, nil
	case err := <-w.fw.Errors:
		return nil, err
	}
}
```
![image](https://github.com/fsnotify/fsnotify/assets/39844451/eec2afde-47a0-461a-829b-e4bd65698858)

**Comment by arp242** [comment]
Yes, this can happen. It's how the Windows kernel delivers the events; there is no guarantee that a single "write" from a user perspective corresponds to a single "Write" event in fsnotify (also because some tools actually *do* write more than once).

Either way, there isn't enough information here to debug and reproduce the issue; you'll need to come up with some code that I can run to *fully* demonstrate the issue, including whatever generates the write events.

**Comment by HuckOps** [comment]
> Yes, this can happen. It's how the Windows kernel delivers the events; there is no guarantee that a single "write" from a user perspective corresponds to a single "Write" event in fsnotify (also because some tools actually _do_ write more than once).
> 
> Either way, there isn't enough information here to debug and reproduce the issue; you'll need to come up with some code that I can run to _fully_ demonstrate the issue, including whatever generates the write events.

Okay, I will perform a processing in my code. Thank you
