### ISSUE TITLE
[AIX] When I call Watcher.Add method, the program can not listen to the new directory, file changes

### ISSUE THREAD

**Issue by mym-bug** [fsnotify/fsnotify#569]
When I call Watcher.Add method, the program can not listen to the new directory, file changes

I would like to share my own tested methods as follows:

file backend_aix.go 

1. add global variable

```
var eChan = make(chan Event, 1)
```

3. readEvents method

```
func (w *Watcher) readEvents() {
        // no longer needed here
        // c := make(chan Event, 1)
	for _, wa := range w.watches {
                 // Instead, use the global variable eChan
		// go wa.GetEvents(c)
                 go wa.GetEvents(eChan)
	}
	for {
		select {
                // Instead, use the global variable eChan
		case ahaevt, ok := <-eChan:
			if !ok {
				continue
			}
			w.Events <- ahaevt
		}
	}
}
```

5. Add method 
```
  func (w *Watcher) Add(name string) error {
	  name = filepath.Clean(name)
	  w.mu.Lock()
	  defer w.mu.Unlock()
	  wa := w.watches[name]
	  if wa != nil {
		  return fmt.Errorf("Object %s is already monitored", name)
	  }
	  wa, err := newWatch(name)
	  if err != nil {
		  return err
	  }
	  w.watches[name] = wa

          // new add
	  go wa.GetEvents(eChan)
	  return nil
  }
```

I just started to learn go, if there is anything wrong, please help to point out, thank you! These are my problems and solutions! Thanks again!

**Comment by arp242** [comment]
Are you using the `aix` branch? AIX is not supported in any release, but there's a branch with some preliminary code in that branch, but I can't test or support that as I don't have access to an AIX machine.

The branch: https://github.com/fsnotify/fsnotify/tree/aix

You can use it with `go get github.com/fsnotify/fsnotify@aix`.

Also see: #353

**Comment by mym-bug** [comment]
yes i'm using the aix branch! 
I will continue to test on aix in the next few days, and if I encounter other problems, I will continue to come back to share feedback
