### ISSUE TITLE
cannot use &key (value of type *uintptr) as *uint32 value in argument to windows.GetQueuedCompletionStatus

### ISSUE THREAD

**Issue by xiexiaoming05** [fsnotify/fsnotify#574]
### Describe the bug

goland idea Console error:

# github.com/fsnotify/fsnotify
D:\workspace_go\pkg\mod\github.com\fsnotify\fsnotify@v1.6.0\backend_windows.go:566:57: cannot use &key (value of type *uintptr) as *uint32 value in argument to windows.GetQueuedCompletionStatus

Compilation finished with exit code 1

### To Reproduce

github.com/fsnotify/fsnotify v1.6.0 // indirect

### Which operating system and version are you using?

OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free

### Which fsnotify version are you using?

github.com/fsnotify/fsnotify v1.6.0

### Did you try the latest main branch?

No

**Comment by arp242** [comment]
In https://github.com/golang/sys/commit/683adc9 the type for `GetQueuedCompletionStatus` was changed from uint32 to uintptr, but fsnotify 1.6.0 has golang.org/x/sys commit 2771309, which includes this change.

It looks like there is something in your build system that causes you to use an older version of golang.org/x/sys: maybe you're using GOPATH mode, or a replace directive, or something else?

**Comment by arp242** [comment]
Closing due to lack of feedback; this seems like an issue in your build (something with `replace` directives?)

Please supply a complete reproducible example and we can reopen and investigate.
