### ISSUE TITLE
Review infogulch/watch package

### ISSUE THREAD

**Issue by infogulch** [fsnotify/fsnotify#583]
Hi!

I made a small module that wraps fsnotify with a simple interface for my use case (initially part of [xtemplate](https://github.com/infogulch/caddy-xtemplate/blob/03776b3453891fa1d0e6bb9ea9475c3c6829faaf/templates.go#L172)), and I'd like to hear your feedback on it if you're willing.

https://github.com/infogulch/watch

In particular, I'm curious if you think it's reasonable to ignore the content of the events and rebuild the watcher after events are received.

Thanks for making fsnotify!

Joe

**Comment by arp242** [comment]
> I'm curious if you think it's reasonable to ignore the content of the events and rebuild the watcher after events are received.

I guess it's okay?

To be honest I don't really have the time to do an in-depth evaluation, taking the full context and platforms in to account. Maybe it will work fine on Linux and macOS but be horrible slow on Windows? Or maybe not? I don't know.

My main advice would be to *test* on the platforms you want to support, and run the tests tons of times (`-count=1000` or whatever is still fast enough to be reasonable).

**Comment by infogulch** [comment]
Extensive testing is good advice. Thank you for your time.
