### ISSUE TITLE
illumos CI broke

### ISSUE THREAD

**Issue by arp242** [fsnotify/fsnotify#586]
Always fails with:

    Downloading gha-serial: http://lightsandshapes.com/gha-serial
    ##[error]Unexpected HTTP response: 404

lightsandshapes.com being the website of papertigers. So looks like he removed that file GitHub Actions needs (it's not referenced in the repo, not sure where it gets any of that from).

I removed it for now, but should add it back: maybe as a fork or use something else.

FYI @nshalman @papertigers

**Comment by papertigers** [comment]
Sorry about that. Let me get it recompiled and put back up.

**Comment by arp242** [comment]
Ah cheers; I kind of assumed it was unmaintained because there hadn't been any changes in quite a few years 😅

**Comment by papertigers** [comment]
It has been...neglected haha. 
Has it been useful to this project?

**Comment by nshalman** [comment]
> It has been...neglected haha. Has it been useful to this project?

It's nice having a way to do any sort of illumos CI with github actions...

**Comment by arp242** [comment]
> Has it been useful to this project?

It has; most of the code here is extremely platform-specific, and the only way to test it is against a real system.

illumos is a fairly small system and not many people use it.  For Linux/macOS/Windows most serious problems would be noticed almost immediately, but even serious bugs could potentially go undetected for quite a while. Certainly for me the illumos CI is *more* useful than the more commonly used platforms.

I have a local illumos QEMU VM, but it's effort and I don't run it for every change, and most other contributors don't even have that.

**Comment by papertigers** [comment]
I put the version built from GitHub actions back at this location. I can't recall if this was supposed to be an arm or intel build. Do you mind attempting to run CI again?
```
❯ curl -I https://lightsandshapes.com/gha-serial
HTTP/2 200
... snip ...
```

I will try and find some time soon to update the version of OmniOS and make sure it pulls from the GitHub release page rather than my personal blog URL.

**Comment by nshalman** [comment]
Looks like it worked:
https://github.com/nshalman/fsnotify/actions/runs/6562112622/job/17823355508?pr=2

**Comment by arp242** [comment]
Yup, it works again; thanks!

**Comment by arp242** [comment]
GitHub changed something in the VM runners, and using Vagrant on macOS is now very unreliably. I don't think it's working for anyone.

I switched to https://github.com/vmactions/omnios-vm, which uses linux/qemu. Seems to work well!

FYI @papertigers.

**Comment by papertigers** [comment]
That's great news as I haven't had much time to maintain my hacked up macOS runner. Glad there's a better solution.
