### ISSUE TITLE
Add dependabot to update your GitHub Actions

### ISSUE THREAD

**Issue by pnacht** [fsnotify/fsnotify#597]
### Describe the bug

I've noticed fsnotify is using some older versions of GitHub Actions (i.e `actions/checkout@v3`, when `v4` is available). These can be kept up-to-date with dependabot, ensuring you run the latest versions of Actions after a new major version. The status of the CI tests will ensure there are no breaking changes.

I'll send a PR setting up dependabot to update these dependencies so you can take a look.

### To Reproduce

See [this PR](https://github.com/keras-team/keras/pull/18855) for an example of what you'll receive from Dependabot.

### Which operating system and version are you using?

N/A

### Which fsnotify version are you using?

N/A

### Did you try the latest main branch?

Yes

### Disclosure

My name is Pedro and I work with Google and the [Open Source Security Foundation](https://openssf.org) to improve the supply-chain security of projects critical to the open-source ecosystem.

**Comment by arp242** [comment]
What value does this add? It works fine as it is – I don't need constant spam to update things that don't need updating.
