### ISSUE TITLE
Can we add a polling interval to the watcher to scan the mentioned directory after a particular time interval and not continuously? 

### ISSUE THREAD

**Issue by aashakabra** [fsnotify/fsnotify#603]
Hello,

Can we add a polling interval to the watcher to scan the directory after a particular time interval and not continuously? 
How can we add it?

Thanks in Advance.

**Comment by arp242** [comment]
What would this fix? What problem are you experiencing? What platform are you using?

I can't really add a feature without understanding what problem this addresses.

**Comment by aashakabra** [comment]
I have a requirement of listening to events after certain polling interval.
I was wondering if such parameter is already available and I am unaware ? Can you let me know about this?

I am using Windows for development right now, but the app we deploy can run either on Windows, Linux or Mac.

**Comment by arp242** [comment]
fsnotify uses events from the kernel to watch for files; it doesn't really "poll" for anything.

If there is no concrete problem, then I think there is nothing to fix?

**Comment by Huzaifa-MS** [comment]
Hello Hope you are doing well : )

I have a concrete issue for this:
I am editing files using vscode on windows. 
I am running the cli that watches these files on wsl.
The events from windows are not seen by wsl cli. So a polling feature would be convenient for development.

**Comment by aashakabra** [comment]
Hello @arp242 , as per FAQ, notifications wont work with NFS, SMB, FUSE, /proc, or /sys.
linked issue - https://github.com/fsnotify/fsnotify/issues/9

says polling is the solution for this.

So, what is the plan to support the feature on mentioned filesystems?

**Comment by arp242** [comment]
So it's just a duplicate feature request of that issue? Closing as such.
