### ISSUE TITLE
Proposed approach for a different type of fanotify backend

### ISSUE THREAD

**Issue by andrewmoise** [fsnotify/fsnotify#605]
Hello! So I just ran into a need to monitor a deeply-nested directory for changes on Linux from a Go program, and I'm sure you will not be surprised to hear that I found it a little difficult. IDK if I missed some solution, but to me it looks like at this stage there still isn't one that's easy, because of the nature of the interfaces Linux gives us. What I settled on to solve the problem was to make a little setuid helper for fanotify that can then be run securely as a subprocess, and present events it sees to the calling program over stdout:

https://github.com/andrewmoise/fanotify-helper

I think we basically *have* to run a helper program in some capacity to solve a lot of instances of this problem on Linux, because otherwise the entire program has to run either as root or with cap_sys_admin, which seems like a bad idea to do for most server software. So that being the case, it seems like having a skinny little layer like this that just exposes fanotify in a secure fashion is the way to do it (better than running as root and better than doing inotify on every single directory with all the resource-consumption and races that entails.)

If I made up a backend for fsnotify that parsed the output of this tool and presented events from it using fsnotify's interface, would that be something y'all would be open to? Or does anyone have other feedback / suggestions on this approach?

I also saw the fanotify backend that's already been made -- I think using that as a starting point or doing them both as two separate backends might be useful, as there'll be some overlap in what we do with the events once we have them obviously, and they each have advantages in some scenarios.

I'm wanting to integrate fanotify-helper into my program anyway, and it seems better to obey the interface for something like fsnotify if I'm doing that, and if I'm making it compatible with fsnotify, then it might as well be in fsnotify. But LMK what you think and if you're open to collaborating on this separate-setuid-tool kind of approach.

**Comment by arp242** [comment]
This seems like the sort of thing that should be done by the application, rather than here, especially because you don't *need* extra permissions for fanotify. The system interface should just provide the system interface: how to use it (e.g. with privsep) is an application concern.

**Comment by andrewmoise** [comment]
Hm? You need extra permissions (cap_sys_admin) in order to run fanotify on a filesystem, and you need to run fanotify on a filesystem in order to realistically monitor a deeply nested directory in full. Don't you? Maybe I have missed something.

**Comment by andrewmoise** [comment]
(Actually, I should clarify - I definitely agree with you that this isn't something fsnotify should have to worry about; it should just expose the underlying interface to the programmer to let them get their work done. In this case though, the underlying interface doesn't seem sufficient for "recursive watch on a decent size directory tree" case that is a large percentage of what people need to do with the library, so it seems like it'd be nice to be able to present something working to the programmer. On Mac/BSD/Windows it seems like it's not an issue. If you decide you don't want to fool with trying to fix up the Linux notify interface on anyone's behalf, I can understand that; I'm just coming from the POV of someone trying to get this working on a Linux machine.)

**Comment by arp242** [comment]
According to fanotify_init(2): "Since Linux 5.13, users may call fanotify_init() without the CAP_SYS_ADMIN capability to create and initialize an fanotify group with limited functionality." It then lists the limitations, most probably aren't a big deal in many use cases.

But that's not all that important – even if you always need SYS_ADMIN it would still be something that's really best suited for the application layer, rather than the library here.

**Comment by andrewmoise** [comment]
Yeah. The critical one for me is:

> The user is limited to only mark inodes.  The ability to mark a mount or filesystem via fanotify_mark() through the use of FAN_MARK_MOUNT or FAN_MARK_FILESYSTEM is not permitted.

Basically, I need to be able to monitor a large directory recursively, which AFAICT simply isn't possible on Linux without something like this.

Again, if you're saying that that's not your problem I can understand that. 🙂

**Comment by andrewmoise** [comment]
Actually, maybe a better / less weird way to do it:

* An fswatch backend for fsnotify that works similar to what I was talking about
* I can worry about trying to get an fanotify backend into fswatch
* And if the me or some end-user wants to make fswatch into a setuid binary, then that's their business

That would also solve my immediate problem, while being less of a weird and one-off solution.

**Comment by arp242** [comment]
Recursive watcher is #13. I did some work for that in #472, but haven't really gotten around to finishing it. The problem with the fanotify backend is that I couldn't really run the tests and that in general it didn't really seem to work all that well, but if you want to continue working on it then I can merge if it's ready.

But like I said, special permissions for things like FAN_MARK_FILESYSTEM is really the application's responsibility; this is the kind of thing we can't really do here in a good way, not without a lot of complexity.

**Comment by andrewmoise** [comment]
Want me to close out the issue? It seems like there's not much to do pertaining to fsnotify with this

**Comment by arp242** [comment]
I mean, you can use fsnotify to build all of this with two services and a simple text protocol. That should be a few dozen lines of code. It just doesn't belong in a library.

But it does need fanotify support here, which currently doesn't exist.
