### ISSUE TITLE
Inconsistent behavior of WatchList on Windows and Unix

### ISSUE THREAD

**Issue by artiga033** [fsnotify/fsnotify#609]
### Describe the bug

The `WatchList()` function returns the exact file on linux, while the parent folder on Windows.

### To Reproduce

``` go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watcher, _ := fsnotify.NewWatcher()
	defer watcher.Close()
	f, _ := filepath.Abs("test.txt")
	os.Create(f)
	watcher.Add(f)
	fmt.Printf("WatchList: %v\n", watcher.WatchList())
}
```

``` sh
> go run .
WatchList: [F:\tmp\fsnotify_t]
> wsl go run .
WatchList: [/mnt/f/tmp/fsnotify_t/test.txt]
```

### Which operating system and version are you using?

Windows 11 Professional 23H2 (22631.3374)
Arch Linux WSL (kernel 5.15)

### Which fsnotify version are you using?

main branch

### Did you try the latest main branch?

Yes

**Comment by arp242** [comment]
Yeah, it's always been broken: https://github.com/fsnotify/fsnotify/blob/main/fsnotify_test.go#L1554-L1557 – the patch that added this method was not very good and got merged while this was de-facto unmaintained.

I think I will mark this method as deprecated to be removed in a v2; AFAIK there is no real reason to have it (or at least, no one really reported a use case for it). But I'll merge any patch that fixes it.

**Comment by artiga033** [comment]
Actually it's been used by some project and causing some weird platform-specific problem. https://github.com/terrastruct/d2/issues/1767#issuecomment-2031182116

I'll try submit a patch later then, as downstream projects expect the same behavior on Windows.

**Comment by arp242** [comment]
Cheers; in principle it shouldn't be too fix, but to be honest the Windows backend confuses me every time I look at it. 

I think you may need to add a new `userWatches` struct field like is done in `backend_kqueue.go`.

**Comment by artiga033** [comment]
and I wonder do you plan to make a new release so that downstream projects could easily keep up with the patch?

**Comment by arp242** [comment]
Probably not for a while; weeks at least, perhaps months. It's the only meaningful change thus far.

It's been broken for 2 years; I think you're the first to notice. In the meanwhile, you can use `go get github.com/fsnotify/fsnotify@7086bea` to get the version with the fix.
