### ISSUE TITLE
Received an unexpected is to see

### ISSUE THREAD

**Issue by ericzhao007** [fsnotify/fsnotify#613]
### Describe the bug

<img width="1466" alt="image" src="https://github.com/fsnotify/fsnotify/assets/21306882/112e2d71-7fdc-4f28-bffc-9609d76356ec">

### To Reproduce

```
package main

import (
	"log"

	"github.com/fsnotify/fsnotify"
)

func main() {
	// Create new watcher.
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	// Start listening for events.
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Has(fsnotify.Write) {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	// Add a path.
	err = watcher.Add("/Users/ericzhao/Workspace/gop/go-chat/utility/httpopenapi/internal/swaggerui/")
	if err != nil {
		log.Fatal(err)
	}

	// Block main goroutine forever.
	<-make(chan struct{})
}

```
`sudo fs_usage | grep ./utility/httpopenapi/internal/swaggerui/swaggerui-redoc.go`

### Which operating system and version are you using?

ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224

### Which fsnotify version are you using?

v1.7.0

### Did you try the latest main branch?

No

**Comment by arp242** [comment]
This needs more details; what did you do to generate the events? What did you expect?

Please don't post text as screenshots, but copy/paste instead.

**Comment by arp242** [comment]
Closing due to lack of feedback.
