### ISSUE TITLE
documentation: double `to to` in Add method of fsnotify.Watcher

### ISSUE THREAD

**Issue by maranix** [fsnotify/fsnotify#633]
Hi there, I was just going through the docs of the Add function of `fsnotify.Watcher` and noticed that `to` is mentioned twice consecutively here on [Line 304](https://github.com/maranix/fsnotify/blob/bec89034c5c5a875b2077b6b876cb085b527e7ee/fsnotify.go#L304).

Should I open a PR or will you guys update it yourselves?

**Comment by arp242** [comment]
You can send a PR if you want, or I'll commit a fix at some point.

**Comment by maranix** [comment]
@arp242 Opened a PR #634

**Comment by arp242** [comment]
Thanks.
