### ISSUE TITLE
support of CLOSE_WRITE event does not work

### ISSUE THREAD

**Issue by olivan139** [fsnotify/fsnotify#635]
### Describe the bug

In main branch I pointed out that there is a commit with addition of over events like `CLOSE_WRITE` called `fsnotify.xUnportableCloseWrite`. It can not be exported, that is why I forked repository and renamed all such unexported fields/methods to make them exportable. Even checked that `fsnotify.Watcher.Supports(snotify.UnportableCloseWrite)` returns true.

Checked with `inotifywait -e close_write`, getting desired output

### Code to Reproduce

[forked version](https://github.com/olivan139/fsnotify/tree/v1.0.1)

### File operations to reproduce

open new file with vim, edit it and close

### Which operating system and version are you using?

Linux  6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Which fsnotify version are you using?

main

### Did you try the latest main branch?

Yes

**Comment by arp242** [comment]
It's unreported until other platforms with support for this are implemented (specifically, FreeBSD and NetBSD). When this is done, it will be exported and put in a released version.

**Comment by arp242** [comment]
And also filtering Create/Remove/etc. events on other platforms; that's actually the bigger issue.

**Comment by olivan139** [comment]
I do understand, but it would be nice if you tell me where I did wrong

**Comment by olivan139** [comment]
I understand that it is not a bug since it is not opened for anyone, but I found this an only way to contact with you :)

**Comment by arp242** [comment]
Oh right, I didn't realize it was a bug report.

Are you use you added it with `WithOps(Create|Remove|UnportableCloseWrite|...)`?

**Comment by arp242** [comment]
Looks like you didn't export that in your fork; need use `w.AddWith(path, fsnotify.WithOps(events-you-want))`. See: https://github.com/fsnotify/fsnotify/blob/main/fsnotify.go#L452

**Comment by olivan139** [comment]
Not really. I used simple `Add()` and then was checking in loop, if the event is equal to `UnsuppetedCloseWrite` value

**Comment by olivan139** [comment]
Then I will try to modify code with using `AddWith()`

**Comment by olivan139** [comment]
It helped, thanks a lot!!!!!!

**Comment by arp242** [comment]
Cheers.

Note you don't need to replace all import paths; in your go.mod you can do:

    require (
        github.com/fsnotify/fsnotify v1.7.0
    )

    replace github.com/fsnotify/fsnotify => github.com/olivan139/fsnotify

And then it will use your fork, without having to change all the import paths.

**Comment by arp242** [comment]
Or you can even use a local path:

    # Just keep your fork in ./fsnotify directory.
    replace github.com/fsnotify/fsnotify => ./fsnotify

    # Outside of repo; mostly useful for testing/dev
    replace github.com/fsnotify/fsnotify => ../fsnotify
