### ISSUE TITLE
Triggering the Create Op leads to EOF issues

### ISSUE THREAD

**Issue by cyhyyq** [fsnotify/fsnotify#644]
Hello！
         I have encountered a problem here. When I trigger the create op, my program reads the contents of the trigger file, but at this time the file content may not have been fully copied, resulting in frequent EOF errors during reading
         I know this is not a library issue, but as the close_writer op is not currently supported, I would like to ask if there is a more suitable method. Here is my code example
```
	for {
		select {
		case event := <-watcher.Events:
			if event.Op&fsnotify.Create == fsnotify.Create {
				file, err := os.Open(event.Name)
				if err != nil {
					return
				}
				defer file.Close()

				gzipReader, err := gzip.NewReader(file)
				if err != nil {
					return
				}
				defer gzipReader.Close()

				bufReader := bufio.NewScanner(gzipReader)
				for bufReader.Scan() {
					line := bufReader.Text()
					fmt.Println(line)
				}
				if err := bufReader.Err(); err != nil {
					return
				}
			}
		case err := <-s.watcher.Errors:
			fmt.Println("watcher error %s", err.Error())
		}
	}
```

**Comment by arp242** [comment]
I think what you want is to wait until it's done writing? See:

https://github.com/fsnotify/fsnotify/blob/v1.7.0/cmd/fsnotify/dedup.go

**Comment by cyhyyq** [comment]
First of all, thank you for your reply. The waiting method seems to be not suitable for my scenario because copying files from different servers may have network latency issues, so the waiting time cannot be determined

**Comment by cyhyyq** [comment]
Thank you very much for your reply. I have solved the problem by referring to this method
