### ISSUE TITLE
Can "create" be used as a write completion flag?

### ISSUE THREAD

**Issue by notmaster-C** [fsnotify/fsnotify#646]
When dealing with continuously input files, fsnotify frequently triggers write and create events. I'm wondering if there's a way to obtain a signal indicating the completion of writing. Currently, after listening, I print the event string and then output it to nohup.out using nohup, which results in an infinite loop where the event keeps being triggered.

**Comment by arp242** [comment]
On some platforms there's some events that may help, such as "close_write". This assumes it's doing a "create + write + close + create/truncate again, repeat".

But this isn't really exposed at the moment; the issue for that is #519.
