### ISSUE TITLE
Allow non-portable features

### ISSUE THREAD

**Issue by PieterD** [fsnotify/fsnotify#67]
Not all operations are available on every platform. Windows doesn't have attrib, kqueue doesn't have create, etc.

I propose a method to determine the capabilities of the library. This would allow us to introduce more events that are not available on every platform, like Close: https://github.com/fsnotify/fsnotify/issues/22

Perhaps something like `err := fsnotify.Capabilities(fsnotify.Create|fsnotify.Write)`

Similarly, combined with event filtering in https://github.com/fsnotify/fsnotify/issues/7, NewWatcher would of course fail if an event is requested that it does not support:
`err := fsnotify.NewWatcher("/file/name", fsnotify.Create|fsnotify.Write)`

The question then remains, is this filter mandatory? I think it should be.

**Comment by nathany** [comment]
Interesting. 

Another proposal is to have something like `Sys() interface{}` in [FileInfo](http://golang.org/pkg/os/#FileInfo) to retrieve the underlying event data (OS specific bitmask). 

That doesn't address filtering though.

**Comment by arp242** [comment]
Closing as duplicate of #519 (that one is much newer, but has some useful comments).

Also PR at #629.
