### ISSUE TITLE
isClosed is being used without locking

### ISSUE THREAD

**Issue by PieterD** [fsnotify/fsnotify#69]
The use of isClosed in the Kqueue code in remove, add, etc seems very racey.

**Comment by PieterD** [comment]
Er, am I blind? I shouldn't open issues from my phone. Disregard this until i get home to look again lol

**Comment by nathany** [comment]
A failing test on a new branch would be a good way to start. :-)

**Comment by PieterD** [comment]
I know I saw something when I was on my phone, but since I had to switch to the comment thing I lost it. So keep this open for a bit please, I'll look at it this weekend.

**Comment by arp242** [comment]
It looks like this got fixed sometime in the last 7 years; there are locks around isClosed now, and I added a test that Close() doesn't race last week.
