### ISSUE TITLE
Events and Errors vs. goroutines

### ISSUE THREAD

**Issue by johto** [fsnotify/fsnotify#71]
Hi,

The [FAQ](https://github.com/go-fsnotify/fsnotify/wiki/FAQ) claims that Events and Errors must not be read from in the same goroutine.  Then the [NewWatcher](https://godoc.org/gopkg.in/fsnotify.v1#NewWatcher) example goes ahead and does _exactly that_.

If the FAQ is correct, the example should be changed.  If the FAQ incorrect, it should be amended to reflect the current state of affairs.

**Comment by nathany** [comment]
The FAQ should be clarified. 

It means that the main goroutine can't be used because it will block.

**Comment by johto** [comment]
Ah, apparently I misread the FAQ.  I looked into the linked issue reports and the source of the problem isn't exactly clear.  Is the point that watcher.Add() might block indefinitely if nobody's reading from the Event/Error channels concurrently?

**Comment by nathany** [comment]
Not `Add` specifically, but the run loop that NewWatcher kicks off. I think it depends on the OS, whether or not the Kernel is blocking. It would be nice to handle all this better internally, but I haven't looked into it that deeply yet. :disappointed:
