### ISSUE TITLE
Improve documentation / specs and add tests for them

### ISSUE THREAD

**Issue by metakeule** [fsnotify/fsnotify#74]
I think the documentation is totally unclear about when which event will be triggered.
I expect this to be different for each plattform, so either the project aims to unify this behavior or not.

In each case it should be clearly documented.

Examples of what is missing:
- When a file is created and written, will only a `fsnotify.Create` event be fired or a `fsnotify.Create` followed by a `fsnotify.Write`?
- When a directory is created, will only a will only a `fsnotify.Create` event be fired or a `fsnotify.Create` followed by a `fsnotify.Write`
- When a file is created, will it be automatically watched or not?
- When a directory is created, will it be automatically watched or not?
- When a file is deleted, will it be automatically removed from the watch list? 
- When a directory is deleted, will it be automatically removed from the watch list? Will all subdirectories and files be automatically removed from the watch list? Will `fsnotify.Remove` events be fired for each subdirectory and file?
- When a file is renamed, will only the `fsnotify.Rename` event be fired, or also `fsnotify.Remove` and `fsnotify.Create`? How do I get the old name and the new name?
- When a directory is renamed, will only the `fsnotify.Rename` event be fired, or also `fsnotify.Remove` and `fsnotify.Create`? How do I get the old name and the new name? What about subdirectories and files. The paths of them also changes. Are the corresponding events fired for them or am I expected to track all of them?

That is just what i stumbled upon, I am sure there are more cases to be defined.
Without clearing up this specs, I think this package is not of much use.

**Comment by PieterD** [comment]
I agree. It is known. I actually think a radically different api is required. Unifying all the different systems into a single common denominator api is... Well, it's hard.

Unfortunately, there's just the two of us at the moment, and we're pretty busy ourselves. Sorry. When I get back from holiday next week I plan to pick it back up. Until then, feel free to contribute.

**Comment by PieterD** [comment]
I've put up a document on the redesign issue. Feel free to comment.
https://github.com/go-fsnotify/fsnotify/issues/1

**Comment by nathany** [comment]
@metakeule You're right. It does depend on the OS.

#23 is a little project I'd like to do to get a better sense of what each OS is doing. Importantly, that would be done at a lower-level than fsnotify, since fsnotify adds some things on top.

Then I'd like to take that research and write about on the website: https://github.com/go-fsnotify/fsnotify.org So far I've dived into kqueue (BSD, OS X), but have yet to write anything up (other than some notes in #24). There are a few more things I need to look into as well, such as renaming #26.

**Comment by egnor** [comment]
I've attempted to catalog a particularly common set of issues in https://github.com/fsnotify/fsnotify/issues/372 -- any documentation refresh project might want to try to address at least some of these.
