### ISSUE TITLE
Split out packages for each OS

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#75]
Pros:
- Gives access to lower-level APIs when needed.
- Multiple high-level APIs (eg. https://github.com/rjeczalik/notify by @rjeczalik) could share some code, while having a different take on the API or supporting a subset of bindings.

Cons:
- Complicates distribution of fsnotify due to external (or internal/) packages.
- More API surface area to design (low level bindings and high level API).

We have FSEvents bindings by @samjacobson as a start:
https://github.com/go-fsnotify/fsevents

**Comment by omeid** [comment]
There is no reason you can't have the combination of both. -- The `os` and `sys/GOOS` (replacing the confusing syscall) packages are a good example of how to approach a complicated set of APIs that are impossible to make strictly consistent across multiple platforms.

Or the other option is to have all the common feature set in the `fsnotify` as an interface. The package `fsnotify` then imports platform specific implementations of the aforementioned interface under the hood and allow users to cast this implementation to platform specific types if they need platform specific features.

**Comment by nathany** [comment]
What I like most is that fsnotify and other libraries are free to experiment with different APIs and ways of using the underlying bindings. The lowest common denominator interface vs. emulating features in user-land vs. driver-like systems. Meanwhile the bindings themselves can be really solid and reused.

**Comment by nathany** [comment]
#173 seems like a good place to start

**Comment by arp242** [comment]
I think #173 is essentially the same issue, even though it's written to be about inotify, that this applies to other backends too seems like a given, even when not explicitly stated. So I will close this one.
