### ISSUE TITLE
rsync: only REMOVE Event received

### ISSUE THREAD

**Issue by kontrafiktion** [fsnotify/fsnotify#77]
Hi!

With a very simple test (on OS X):

```
package main

import (
    "fmt"
    "strings"
    "gopkg.in/fsnotify.v1"
)


func main() {
    watcher, err := fsnotify.NewWatcher()
    if err != nil {
        fmt.Printf("fsnotify.NewWatcher() creates error=<%v>", err)
    }
    fileorfolder := "/tmp/watchme.dir"
    fmt.Printf("watching %s\n", fileorfolder)
    err = watcher.Add(fileorfolder)
    if err != nil {
        fmt.Printf("watcher.Watch subfolder=<%v> error=<%v>", fileorfolder, err)
    }

    loop:
    for {
        select {
        case ev := <-watcher.Events:
            fmt.Printf("event %s\n", ev)
            if strings.Contains(ev.Name, "Bye") {
                break loop
            }
        case err := <-watcher.Errors:
            fmt.Printf("error: " + err.Error())
            break loop
        }
    }
}
```

and using rsync (rsync -avh /tmp/rsync.test/watchme.dir /tmp) to "copy" files ("foo.txt") to the watched location, I get

```
event "/tmp/watchme.dir/foo.txt": REMOVE
```

but nothing else. I would have expected a MOVE or CREATE for the file. On Linux I get

```
event "/tmp/watchme.dir/.foo.txt.HM02fS": CREATE
event "/tmp/watchme.dir/.foo.txt.HM02fS": CHMOD
event "/tmp/watchme.dir/.foo.txt.HM02fS": RENAME
event "/tmp/watchme.dir/foo.txt": CREATE
```

it doesn't matter whether I put the core loop into a go routine

**Comment by nathany** [comment]
Strange. I was pretty sure the the go routine would make a difference (https://github.com/go-fsnotify/fsevents/issues/11).

l need to find some time to try out your example.

**Comment by amanankur** [comment]
Hi,

Any update on this?
The same thing is happening for me too. Getting a remove signal when using rsync ,and then the file watching stops and no further events are generated

**Comment by arp242** [comment]
I first created /tmp/fsnotify:

	% mkdir /tmp/fsnotify
	
Then I watched that directory with `./cmd/fsnotify`, and in a different terminal I ran:

	% rsync -avh ~/fsnotify/* /tmp/test/

Which results in many events which seem roughly fine to me:

	[~/fsnotify]% go run ./cmd/fsnotify /tmp/fsnotify/
	00:86:13.0110 watching; press ^C to exit
	00:86:19.5773   1 CHMOD                 "/tmp/fsnotify"
	00:86:19.5776   2 CREATE                "/tmp/fsnotify/cmd"
	00:86:19.5807   3 CREATE                "/tmp/fsnotify/.CHANGELOG.md.WQdihs"
	00:86:19.5815   4 CREATE                "/tmp/fsnotify/CHANGELOG.md"
	00:86:19.5822   5 CREATE                "/tmp/fsnotify/CONTRIBUTING.md"
	00:86:19.5826   6 CREATE                "/tmp/fsnotify/.LICENSE.h8dMLN"
	00:86:19.5838   7 WRITE|RENAME|CHMOD (modified) "/tmp/fsnotify/.LICENSE.h8dMLN"
	00:86:19.5839   8 CREATE                "/tmp/fsnotify/.README.md.hSUiq5"
	00:86:19.5842   9 CREATE                "/tmp/fsnotify/LICENSE"
	00:86:19.5842  10 CREATE                "/tmp/fsnotify/README.md"
	00:86:19.5867  11 CREATE                "/tmp/fsnotify/asd"
	00:86:19.5867  12 CREATE                "/tmp/fsnotify/asdzcxzcx"
	…

I played around a bit creating new files and the like, and it all seems to work well at a glance. Tested in macOS and FreeBSD, which behave identical.

---

Since this is an old issue that I can't reproduce, I'll close this for now; please get back to me if you're still experiencing it and we can reopen and investigate further.
