### ISSUE TITLE
Can fsnotify be used to watch virtual filesystem like /proc or /sys ?

### ISSUE THREAD

**Issue by allencloud** [fsnotify/fsnotify#78]
Hi, All,
         I hope to watch /proc to see something changes in the kernel memory, And I wonder if fsnotify can be used to watch /proc and /sys and something like cgroup filesystem?

Thanks in advance.

**Comment by nathany** [comment]
Apparently not. fsnotify uses inotify under the hood when running on Linux:

> /proc is a kernel interface. There are no real files there, hence they can't change. Reading from the handles is a request and the data in the file when you read it is a reply to that. - [StackExchange](http://unix.stackexchange.com/questions/90627/notify-of-changes-on-a-file-under-proc)

> The data that you see when you read from the proc filesystem is generated on-the-fly when you do a read from the begining of a file. That is, doing the read causes the data to be generated by a kernel callback function that is specific to the file you are reading.

**Comment by allencloud** [comment]
Thank @nathany  I think I have got your point.

**Comment by liukaii** [comment]
@allencloud  Have you solved this problem? If I want to watch /sys, Is there any good solution?

**Comment by nathany** [comment]
I'm guessing the only option is to use polling (see #9)?

Does somebody want to document this in the FAQ or start a documentation project?
