### ISSUE TITLE
rename subdir, the event is CREATE? macOS

### ISSUE THREAD

**Issue by guotie** [fsnotify/fsnotify#82]
rename subdir, the event is CREATE?

**Comment by guotie** [comment]
the dir tree is following:

d
--- a
--- b

where d and a is dir, I watch d, and when i rename a to aa, I got event CREATE aa

**Comment by omeid** [comment]
What platform? And how do you rename the directory?

**Comment by guotie** [comment]
OSX 10.10

**Comment by guotie** [comment]
just use mv to rename the directory

**Comment by guotie** [comment]
I have create a pull request to fix it.

**Comment by nathany** [comment]
ref #83

**Comment by arp242** [comment]
I get:

    00:86:25.7484 watching; press ^C to exit
    00:86:32.4964   1 CREATE                "/tmp/watch/x"
    00:86:32.4986   2 REMOVE|RENAME            "/tmp/watch/d"

On `mv d x`.

It seems like #83 was merged for this back in Nov 2015, but this issue was never closed.
