### ISSUE TITLE
watcher.Close() is hanging forever on OSX

### ISSUE THREAD

**Issue by ryanwalls** [fsnotify/fsnotify#89]
I'm using the standard pattern presented in the samples file.  Running the watcher from within a unit test and the unit test never exits when watcher.Close() is called.

Let me know what details would be useful.

**Comment by nathany** [comment]
If you can share some sample code to reproduce the issue, that would be helpful..

**Comment by omeid** [comment]
The example doesn't check if `watcher.Events` so after calling `watcher.Close()` the outer select would block forever, assuming there are no errors.

**Comment by pquerna** [comment]
I was having similar issues on OSX, and PR #124 fixed them for me.

**Comment by nhooyr** [comment]
I believe this is fixed in #230 @nathany

**Comment by nhooyr** [comment]
Never mind, seems unrelated if the OP is following the example.
