### ISSUE TITLE
[BUG] Watchers receive each others events

### ISSUE THREAD

**Issue by purpleidea** [fsnotify/fsnotify#95]
I've got multiple inotify watchers in different go routines... Each is asked to watch for one or more files. Eg:

Watcher one:
watches: /tmp/some_dir/file1

Watcher two:
watches: /tmp/some_dir/file2

Watcher three:
watches: /tmp/some_dir/file3

However, watcher three, in addition to receiving events about file3, also receives events about file1 and file2. The same is the case for the other watchers!

This naturally causes erroneous events to be delivered to the wrong watchers... I haven't yet confirmed if events are ever lost to the watcher that requested the event or not. I think it's possible, but I don't know yet. Might be a different bug in my code.

**Comment by nathany** [comment]
This is on Linux? Do you think you could provide a code snippet that reproduces the issue? Thanks.

**Comment by purpleidea** [comment]
Yes it's on Linux.

I don't have a standalone snippet at the moment, but if you don't mind running a bit of extra code, it's 100% reproducible:

code:
https://github.com/purpleidea/mgmt/

run with:

./mgmt run --file examples/graph1.yaml

If you add some print statements in this else block, you'll see the obvious events from each others events:
https://github.com/purpleidea/mgmt/blob/master/file.go#L137 <-- number number may change in future...

Please excuse the mess in this code base, it's a rough prototype and I'm a golang newbie, but getting better on both counts.

Cheers,
James

**Comment by matthias-stone** [comment]
Wrote a sample application, could not reproduce. Lots has change in the inotify code since this was created, if someone finds this issue again they should reopen this or create a new issue.
