### ISSUE TITLE
Is overflow handled by getting an Op with a value of zero?

### ISSUE THREAD

**Issue by gaillard** [fsnotify/fsnotify#97]

**Comment by gaillard** [comment]
:(

**Comment by nathany** [comment]
I'm not sure if I understand. Op is a bit field with only 5 bits. It should not overflow even an 8-bit int, and it is a 32-bit int.

**Comment by gaillard** [comment]
I am talking about the inotify overflow event. IN_Q_OVERFLOW

**Comment by nathany** [comment]
Oh. I've never heard of it.

**Comment by gaillard** [comment]
As far as I know in order to correctly program against inotify, one _must_ scan after receiving an overflow, which comes out of this library as just the default zero value, just needs to be documented then that any non supported events are caught in the zero value.

In the same line for people to develop with correctness, supporting IN_ONLYDIR in some way is the only way I know to avoid a race condition between a stat and then an add watch for a dir.

**Comment by gaillard** [comment]
I have been trying to force the overflow but still can't seem to. So inotify is documented to give out a wd of -1 on overflow. So my guess is most of the packages are going to panic when it can't look up the wd in the map.

**Comment by gaillard** [comment]
Ok I found this issue in this package. At https://github.com/go-fsnotify/fsnotify/blob/master/inotify.go#L280 because the `e.Name` will not be filled, the `Lstat()` returns an error that `os.IsNotExist()` returns true for and the event is skipped.

Since the overflow event is critical it needs to get into the user code.

**Comment by nathany** [comment]
I'm not entirely sure. A git blame points back to this issue in howeyc/fsnotify https://github.com/howeyc/fsnotify/issues/36.

I don't like the idea of ignoring events either.

**Comment by matthias-stone** [comment]
PR #149 handles this by putting a fsnotify.ErrEventOverflow in the Errors channel.
